### ISSUE TITLE
SPARQL update not performed when multiple updates executed at the same time on the same file

### ISSUE THREAD

**Issue by pheyvaer** [solid/node-solid-server#1018]
Hi,

If I do multiple SPARQL updates to the same file at the same time, i.e., I don't wait till the first update returns a response from the server, the first update is not successful on the server, only the second update. Furthermore, I do not get an error from the server. Both updates do an INSERT, so there should not be any conflicts.

**Comment by RubenVerborgh** [comment]
This is #137: we should implement locks on the file system. Unfortunately, given the many places where the file system is accessed currently, implementing this will not be straightforward. What we really want is a dedicated layer/component responsible for writes, so we can implement it there.

**Comment by pheyvaer** [comment]
OK I see. Is it maybe possible to at least get an error? I can make sure that within a single application I don't do two concurrent calls, but I cannot guarantee that across multiple applications.

**Comment by RubenVerborgh** [comment]
Even for such an error we need locking.

**Comment by RubenVerborgh** [comment]
Following up in https://github.com/solid/node-solid-server/issues/137.
