### ISSUE TITLE
Acknowledge all contributors to this repository

### ISSUE THREAD

**Issue by RubenVerborgh** [solid/node-solid-server#1053]
The current README only lists people who have contributed through lines of code. We should acknowledge people who contributed in various other means, such as through issues, testing, interactions on chat, etc.

**Comment by RubenVerborgh** [comment]
Two possible solutions have been contributed so far:
- #1054, with a sectioned list to explicitly acknowledge non-code contributions
- #1055, with a flat list

**Comment by RubenVerborgh** [comment]
Following up for the Solid project as a whole: https://github.com/solid/solid/issues/243

**Comment by melvincarvalho** [comment]
No strong view on this.  But perhaps some food for thought.  Last time this topic came up, I mentioned the all-contributors standard : 

https://github.com/all-contributors/all-contributors

Which has some guidelines, tooling and bots.  It is used by some other free software projects and contains various [categories](https://all-contributors.js.org/docs/overview#emoji-key) of contribution, each with their own icon.  

Not specifically endorsing this approach, but it may be of interest to see how others go about solving this issue.

**Comment by RubenVerborgh** [comment]
Good point, I linked to it as well in the PR for this issue: https://github.com/solid/node-solid-server/pull/1054#issuecomment-454961331. I'm cautious about the maintenance overhead it might generate, but would be nice to explore. Perhaps #1054 can be a temporary solution, and then be replaced by a more advanced version.
