### ISSUE TITLE
v5 refreshing public page causes fetch url jumble

### ISSUE THREAD

**Issue by rimmartin** [solid/node-solid-server#1068]
Are you wanting testing to be done on v5? If so

1) clone and install v5
```
clone -b release/v5.0.0 https://github.com/solid/node-solid-server.git node-solid-server
cd node-solid-server
npm install
export DEBUG=solid:*
bin/solid-test start --webid --auth oidc --multiuser --port 8443 --ssl-cert /home/roger/NodeProjects/roger-g74s.cert --ssl-key /home/roger/NodeProjects/roger-g74s.key --root ./data 

```
2) register a user and go to public folder view

3) add a sub folder and expand it within the public view; should look good

4) refresh the public view with the browser

5) expand the sub folder again and should see a fetch url jumble
```
Outline.expand: Unable to fetch <https://lisa.localhost:8443isa.localhost/public/bread/>: Failed to load  <https://lisa.localhost:8443isa.localhost/public/bread/> Fetcher: fetch failed: TypeError: https://lisa.localhost:8443isa.localhost/public/bread/ is not a valid URL. status: 999
```
The url <https://lisa.localhost:8443isa.localhost/public/bread/> has a strange insertion of part of itself.  Solside shows it too.
I've seen this with my user name I used repeatedly for testing and with one I never used before.

On ubuntu 16.04 with firefox v64.0 nodejs node-v11.1.0-linux-x64

**Comment by kjetilk** [comment]
> Are you wanting testing to be done on v5? 

Yes, so thanks a lot! We'll have a look!

**Comment by rimmartin** [comment]
@kjetilk , good, I'll keep testing. let me know if there should be anything focused on specifically

**Comment by megoth** [comment]
I'll take this on to determine where the bug is. If it is in the server, we'll take it on, it not, we might postpone this fix.

**Comment by megoth** [comment]
An update: I was able to reproduce the bug, and think I've pinpointed it to a bug in the server. It seems to be something wrong in `lib/ldp-container.js`, but I'm working on figuring out exactly where it goes wrong.

**Comment by rimmartin** [comment]
Hi @megoth , I'll test as you have need.  Glad you narrowed it down!

**Comment by kjetilk** [comment]
Great stuff. We'll roll another beta once this is fixed.

**Comment by megoth** [comment]
I tracked the problem down to the use of relative path in the root property and not handling that in the new ResourceMapper. So this was indeed a regression bug. I'm creating a PR now, should have something ready during the day.
