### ISSUE TITLE
cannot delete /settings/serverSide.ttl

### ISSUE THREAD

**Issue by elf-pavlik** [solid/node-solid-server#1072]
I use `https://elf.solid.community/` as dev Identity Provider account and `https://elf.solidtest.space/` as dev Resource Server. I want to delete everything from the IdP account except the profile card.
When I try deleting `/settings/serverSide.ttl`
```js
SolidAuthClient.fetch('/settings/serverSide.ttl', { method: 'DELETE' })
```
Response shows: HTTP 403
```
You are currently logged in as https://elf.solid.community/profile/card#me,
but do not have permission to access https://elf.solid.community/settings/serverSide.ttl. 
```

When I try to delete `/settings` I get HTTP 409
```
Container is not empty
```

**Comment by kjetilk** [comment]
Indeed, if your user could do that, you could defeat the quota system. So, deleting the `serverSide.ttl` is only something the server administrator can do. So, it is not a bug... :-)

**Comment by elf-pavlik** [comment]
If `serverSide.ttl` doesn't really belong to user's data, why put it in their storage? It might work better to put it under some reserved subdomain/path eg. `admin` or `system` and use user's storage for resources they can control.

**Comment by kjetilk** [comment]
Yes, it is... But it is really a long story, we'd didn't have any other place to put it, without introducing an entirely new element to the stack, and we already spent an awful lot of time on this. We might do it differently in the future.
