### ISSUE TITLE
Home page WebID link breaks browser back button

### ISSUE THREAD

**Issue by gklyne** [solid/node-solid-server#1094]
I'm using a local development deployment of solid-server, as described for #1093.

Starting point is  that the public homepage (https://localhost:8443/) is displayed in my browser (currently using Firefox for this test).

If I click on the "WebID" link (https://localhost:8443/profile/card#me), a new page is displayed at the link location, but I can't click the browser's "back" button to return to the home page - nothing happens.

**Comment by Ryuno-Ki** [comment]
Do you see any additional items when long-pressing the back button?
E.g. could it be related to History API of the browser?

**Comment by gklyne** [comment]
Yes, the home page appears as the second item in the back-button-history list, and if I click on that I return to where I'd expect the back button to take me.

The first item in the list appears to be the WebID page.  (If I click on that, I stay on the same page.)

**Comment by megoth** [comment]
Seems there's a redirect happening, that navigates you from `/profile/card` to `/profile/card#me`. I was able to reproduce this, but uncertain if it's NSS doing it or the data browser. I'll coordinate this with the team at inrupt to find a solution.

**Comment by megoth** [comment]
(But of course open for others to suggest solutions as well - Just wanted to communicate that I want to push this up the queue of what inrupt is working on.)

**Comment by Vinnl** [comment]
Thanks for reporting this. I've submitted a potential fix for review at https://github.com/solid/solid-panes/pull/85.
