### ISSUE TITLE
5.0.0beta7 : clients _key and users _key not created ==> server build but no access

### ISSUE THREAD

**Issue by bourgeoa** [solid/node-solid-server#1096]
## Please describe what you did in reproducible steps
I build with docker a full new version using a config.json file as all previous versions from 4.0 until 5.0.0.beta.6

## How did it work with 4.x series servers?
build with no pb

## What happened when you tried the same with the 5.0.0 beta?
no way to access the url of the pod provider

## Any material that will help, logs, error messages, etc.
provider.json file seems normal

**Comment by kjetilk** [comment]
In beta.7, we had a fix for a problem with the serverUri, in #1084 . Is it possible that it could have caused problems for Docker?
