### ISSUE TITLE
solid-server issues auth tokens for URLs it can't serve

### ISSUE THREAD

**Issue by gklyne** [solid/node-solid-server#1097]
I just had a bit of a tussle with `solid-server` because I had erroneously used an incorrect  `url` value in my auth code.  (See later  comments at https://gist.github.com/gklyne/e9af15dfbcfb7a35bc32dd526b3397db for details.)

It seems to me that in this situation, the server should be declining to offer an auth token at all:  how can it possibly know that I'm authorized to access a resource from some different authority?  A useful side effect would be that errors like mine could be picked up more easily.

**Comment by dmitrizagidulin** [comment]
I think this will be addressed once https://github.com/solid/node-solid-server/issues/1082 is implemented.

**Comment by gklyne** [comment]
Ack.  Per bitter discussion, I now see I was misunderstanding the role of the `url` in the login request - I misunderstood it as referring to the resource being accessed.  But I know understand it's a reference to the origin that uses the token to determine access permissions.  This makes more sense.

Closing issue.

**Comment by gklyne** [comment]
See also Gitter [February 13, 2019 2:47 PM](https://gitter.im/solid/node-solid-server?at=5c642dec28c89123cbc121a1)
