### ISSUE TITLE
/index.html.acl present, /index.html missing: requesting / returns /index.html.acl

### ISSUE THREAD

**Issue by csarven** [solid/node-solid-server#1104]
Issue occurs in v5.0.0-beta.7-6-g217e8e3 .

If index.html is absent and index.html.acl is present, request to / returns the contents of /index.html.acl . *Expected*: return container

If /index.html.acl is also absent, returns container.

How to reproduce:
Fresh install. (Added public read policy on /.acl to simplify)

```
$ bin/solid start
$ mv data/index.html data/foo.html
$ curl -ikL https://localhost:8443/
HTTP/1.1 200 OK
X-Powered-By: solid-server/5.0.0-beta.7
Vary: Accept, Authorization, Origin
Access-Control-Allow-Credentials: true
Access-Control-Expose-Headers: Authorization, User, Location, Link, Vary, Last-Modified, ETag, Accept-Patch, Accept-Post, Updates-Via, Allow, WAC-Allow, Content-Length, WWW-Authenticate
Allow: OPTIONS, HEAD, GET, PATCH, POST, PUT, DELETE
Link: <.acl>; rel="acl", <.meta>; rel="describedBy", <http://www.w3.org/ns/ldp#Resource>; rel="type"
WAC-Allow: user="read",public="read"
MS-Author-Via: SPARQL
Updates-Via: wss://localhost:8443
Content-Type: text/turtle
Date: Mon, 18 Feb 2019 10:20:52 GMT
Connection: keep-alive
Transfer-Encoding: chunked

@prefix acl: <http://www.w3.org/ns/auth/acl#>.
@prefix foaf: <http://xmlns.com/foaf/0.1/>.

<#public>
    a acl:Authorization;

    acl:agentClass foaf:Agent;  # everyone

    acl:accessTo <./index.html>;

    acl:mode acl:Read.
```

**Comment by kjetilk** [comment]
Oh, OK. So, I suppose something went wrong with the #1067 fixing? Could you check, @megoth ?

**Comment by megoth** [comment]
Yes, this sounds like an unexpected outcome of the special handling root...

I'll take a look!

**Comment by megoth** [comment]
So after a bit of research it seems that the problem is in the resourceMapper that picks `index.html.acl` because it tries to find a file that matches with `index`. So nothing to do with #1067. I'll push a PR with a fix soon.
