### ISSUE TITLE
Prevent data  loss in concurrent updates - Using synchronous code

### ISSUE THREAD

**Issue by timbl** [solid/node-solid-server#1105]
The solid system requires that inconsistent changes from concurrent users editing the same thing should never  lose data, returning 409 to the change which failed.  (Semaphore operation).  Currently the server can fail to do this because the second request can come in between the first one reading the file and writing the modified file.  

This issue solves the problem by changing the patch handler so that the 
- target file read
- target file parse
- patch data 
- target file serialize
- target file write 

Are all synchronous, blocking the server from handling other requests in between

**Comment by megoth** [comment]
I suggest closing this issue in favor of https://github.com/solid/node-solid-server/issues/1106.

**Comment by timbl** [comment]
Agreed. Is there a way of expressing that to the system?

**Comment by kjetilk** [comment]
Mentioning the bug number #1106 creates a cross-reference, I think that is the best we can do, so, hereby done. :-)
