### ISSUE TITLE
Prevent data loss in concurrent updates - using file locking

### ISSUE THREAD

**Issue by timbl** [solid/node-solid-server#1106]
The solid system requires that inconsistent changes from concurrent users editing the same thing should never lose data, returning 409 to the change which failed. (Semaphore operation). Currently the server can fail to do this because the second request can come in between the first one reading the file and writing the modified file.

This issue solves the problem by changing the patch handler so that the

* target file read
* target file parse
* patch data
* target file serialize
* target file write

Are all covered by a file lock , blocking the server from handling other requests in between, 
and ALSO the put handler's  file write.

**Comment by csarven** [comment]
https://github.com/solid/node-solid-server/issues/137

https://github.com/solid/node-solid-server/issues/813
