### ISSUE TITLE
Returns 403 instead of 401 for certain requests

### ISSUE THREAD

**Issue by megoth** [solid/node-solid-server#1117]
An error that Jairo in Janeiro Digital figured out what was going wrong.

## Please describe what you did in reproducible steps

Logging in with a v5 server using the [release/profile-branch of generator-solid-react](https://github.com/Inrupt-inc/generator-solid-react/tree/release/profile) and trying to edit profile fields.

## How did it work with 4.x series servers?

It returned 401, which made [solid-auth-client](https://github.com/solid/solid-auth-client) make another request with credentials.

## What happened when you tried the same with the 5.0.0 beta?

The server returns 403 on all PATCH-requests. This stops `solid-auth-client` from sending another request.

**Comment by kjetilk** [comment]
There was a test failure when I merged #1118 into the v5 branch, which made me take another look at the tests. There are [two failing tests](https://travis-ci.org/solid/node-solid-server/jobs/503870654#L1800) now that I think should work, one is different from previous branch. I have branched it out in [fix/new-branch-faulty-403](https://github.com/solid/node-solid-server/tree/fix/new-branch-faulty-403) as I had to revert the merge from #1118.

**Comment by kjetilk** [comment]
Now the fix is in #1140
