### ISSUE TITLE
Make redirect working

### ISSUE THREAD

**Issue by y0va** [solid/node-solid-server#1124]
On my platform, ubuntu 18.04, node 11.10.1 the command line switch `--redirect-http-from [port]`does not work without any errors in the debug logs.

**Comment by megoth** [comment]
Which version of the server are you working with?

**Comment by megoth** [comment]
And could you provide some of the errors you're seeing perhaps?

**Comment by megoth** [comment]
Oh, great, you have a fix already! Awesome 😸

**Comment by y0va** [comment]
There had been no errors. I'm using master.

 :gift:

**Comment by megoth** [comment]
This should be easy to merge into [release/v5.0.0](https://github.com/solid/node-solid-server/tree/release/v5.0.0) as well I think. Will talk to @kjetilk about it when he's back from conference.
