### ISSUE TITLE
NN5 breaks streaming of mp3s

### ISSUE THREAD

**Issue by timbl** [solid/node-solid-server#1129]
```
solid:ACL Permissions on https://timbl.com/Media/Music/iTunes/iTunes%20Music/Arlo%20Guthrie/In%20Times%20Like%20These/06%20Last%20To%20Leave.mp3 for public:  +0ms
  solid:get /Media/Music/iTunes/iTunes%20Music/Arlo%20Guthrie/In%20Times%20Like%20These/06%20Last%20To%20Leave.mp3 on timbl.com +0ms
  solid:get GET -- Error: undefined "options" must be a string or an object, got number instead. +1ms
  solid:server Error page because of: TypeError: "options" must be a string or an object, got number instead.
    at getOptions (fs.js:75:11)
    at new ReadStream (fs.js:1942:24)
    at Object.fs.createReadStream (fs.js:1931:10)
    at Promise (/devel/github.com/solid/node-solid-server/lib/ldp.js:376:29)
    at new Promise (<anonymous>)
    at LDP.get (/devel/github.com/solid/node-solid-server/lib/ldp.js:375:22)
    at <anonymous> +0ms
```

**Comment by timbl** [comment]
A public file  does the same thing: https://timbl.com/timbl/Public/Test/Music/Jason%20Shaw/Audionautix%20Acoustic/Jason_Shaw_-_RIVER_MEDITATION.mp3

**Comment by kjetilk** [comment]
The code in question changed with the recent lockfile integration: https://github.com/solid/node-solid-server/blame/release/v5.0.0/lib/ldp.js#L376 but I don't know it is directly related. @RubenVerborgh , do you think you could have a look?

It seems to me that the `start && end && {start, end}` will result in a boolean, and that shouldn't work: https://nodejs.org/api/fs.html#fs_fs_createreadstream_path_options Or am I missing something?

**Comment by RubenVerborgh** [comment]
> It seems to me that the `start && end && {start, end}` will result in a boolean

Not how JS works :-) `1 && 1 $$ {}` results in `{}`.

But I made a faulty assumption: I thought start/end would be undefined or a positive number. Fixing.

**Comment by kjetilk** [comment]
Whooaah. OK!
