### ISSUE TITLE
500 error when testing NSS5

### ISSUE THREAD

**Issue by michielbdejong** [solid/node-solid-server#1134]
Running the latest head of the release/v5.0.0 branch on localhost, I'm seeing a 500 response on /profile/card, with the response body `request to https://localhost:8443/.well-known/openid-configuration failed, reason: self signed certificate`, even though I am running it with the `--no-reject-unauthorized` flag and I can view https://localhost:8443/.well-known/openid-configuration in my browser without problems (apart from the 'Not secure' warning in the address bar).

**Comment by michielbdejong** [comment]
The error was caused at https://github.com/solid/oidc-rs/blob/master/src/ProvidersCache.js#L61 and the way to avoid it is to use either `./bin/solid-test start` or `NODE_TLS_REJECT_UNAUTHORIZED=0 node ./bin/solid start --no-reject-unauthorized` instead of `node ./bin/solid start --no-reject-unauthorized`.

**Comment by GayanDushantha** [comment]
Hi I'm new to this and How do I execute those commands in windows?
