### ISSUE TITLE
Unclear how to add trusted apps

### ISSUE THREAD

**Issue by michielbdejong** [solid/node-solid-server#1135]
I ended up editing the .ttl source of my profile by hand (haven't been able to check whether it worked yet), but we should probably have some UI for adding trusted apps?

**Comment by melvincarvalho** [comment]
Does this help : 

https://github.com/solid/solid-panes/issues/58

**Comment by michielbdejong** [comment]
Ah yes, thanks! I created a version of mashlib that includes that pane. It seems to get registered now although I don't see the `A` icon show up on https://localhost:8443/profile/card (yet).

**Comment by michielbdejong** [comment]
OK, got it working! If others want to test this as well (would be good to do this on dev.inrupt.net, for instance), the trusted-apps branch on my fork [pulls in a built version of mashlib](https://github.com/michielbdejong/node-solid-server/commit/431feae9124dfa2ef4032b41c8feabc32d2705ca) that already contains  the trustedApps pan.
