### ISSUE TITLE
Do not use Google Analytics

### ISSUE THREAD

**Issue by akuckartz** [solid/node-solid-server#1153]
Noted in https://github.com/solid/node-solid-server/issues/1152#issuecomment-475908016 by @melvincarvalho

**Comment by melvincarvalho** [comment]
@akuckartz 	thanks for raising this.  I think there will be a range of views on this one.

I'll note that this is not native to node solid server.

It is however part of solid dot inrupt dot com.  Which is now linked to the code base.

There will be differing views on GA.  As a self professed "privacy fundamentalist", I would consider it harmful.  

So while I think it's up to individual companies or pods to use that technology, we should not in our code base, and we should not in any of sites that are marked as "official".

Whether it should be used in general, (eg in a pod or app) really is an open question.  Possibly should be up front and in the T&C.  I personally would avoid.  But I can see why a business would go that route.  Should we allow apps and pods that use tracking software -- maybe.  Should they be part of the "benificent" eco system, maybe not, that could be up for debate.

I also believe there are a few open source alternatives to GA.

**Comment by akuckartz** [comment]
One alternative is https://matomo.org (fka Piwik).

**Comment by gobengo** [comment]
@akuckartz I empathize with the utility of web analytics for helping website operators understand what part of their sites are getting used and how such that they can improve the product, and I agree that it's unfortunate when, in doing so, they share the surveillance data only with Google.

[Matomo](https://permanent.cloud/apps/matomo) is pretty good at it. I use it for [permanent.cloud], but self-hosted (on permanent.cloud). You and everyone else can see the results here: https://matomo.permanent.cloud/

**Comment by justinwb** [comment]
Hi all - just want to point out that https://solid.inrupt.com does use Matomo, and has been now for several months. Will figure out what's pulling in that GA script and make sure it is stripped out immediately. Thanks for raising this.

**Comment by justinwb** [comment]
> Hi all - just want to point out that https://solid.inrupt.com does use Matomo, and has been now for several months. Will figure out what's pulling in that GA script and make sure it is stripped out immediately. Thanks for raising this.

As a quick update - the GA script call has been stripped out.

**Comment by akuckartz** [comment]
This is resolved as far as I am concerned. Thanks to all who helped!
