### ISSUE TITLE
Locks timing out cause server crash (as opposed to 500)

### ISSUE THREAD

**Issue by RubenVerborgh** [solid/node-solid-server#1161]
Locks on files expire too quickly for some operations (which can take several seconds).

**Comment by timbl** [comment]
There may be other compounding issues, such as lockfiles being left after a crash, and then blocking the next run of the server.  Maybe the lock system should ignore & delete any lock file which is older than 20 minutes?  older than the start time of this run of the server?

**Comment by timbl** [comment]
Logfile: 
```
  solid:ACL  checking <http://www.w3.org/ns/auth/acl#Append> +0ms
  solid:ACL   Append required and Write allowed. OK +0ms
  solid:handlers PATCH -- /timbl/Data/Contacts/people.ttl +0ms
  solid:handlers PATCH -- Target <https://timbl.com/timbl/Data/Contacts/people.ttl> (text/turtle) +0ms
  solid:handlers PATCH -- Received patch (375 bytes, application/sparql-update) +0ms
  solid:handlers PATCH -- Read target file (552536 bytes) +2ms
  solid:handlers PATCH -- Reading https://timbl.com/timbl/Data/Contacts/people.ttl with content type text/turtle +0ms
  solid:handlers PATCH -- Parsed target file +2s
  solid:handlers PATCH -- Applying patch +0ms
  solid:handlers PATCH -- Writing patched file +1ms
  solid:fs Setting no quota. While reading serverSide.ttl, got Error: ENOENT: no such file or directory, open '/Library/WebServer/Documents/settings/serverSide.ttl' +10s
/devel/github.com/solid/node-solid-server/node_modules/proper-lockfile/lib/lockfile.js:181
        onCompromised: (err) => { throw err; },
                                  ^

Error: Unable to update lock within the stale threshold
    at options.fs.utimes (/devel/github.com/solid/node-solid-server/node_modules/proper-lockfile/lib/lockfile.js:109:21)
    at FSReqWrap.oncomplete (fs.js:135:15)
Tue Apr  2 11:49:04 EDT 2019
Assumed crashed, restarting in 5s [ hit CTRL+C now to stop]
```
The date at the bottom indicates the server had just crashed.  So it looks as though the exception `Unable to update lock within the stale threshold` was for some reason not caught.  It should for example have returned 500

**Comment by RubenVerborgh** [comment]
> There may be other compounding issues, such as lockfiles being left after a crash, and then blocking the next run of the server. Maybe the lock system should ignore & delete any lock file which is older than 20 minutes?

That functionality is all part of the locking library we use.

> The date at the bottom indicates the server had just crashed

Indeed. This PR aims to fix that, making it a local error instead.
Would you be able to test?
