### ISSUE TITLE
If someone's Card gets corrupted, people who had him as friend can't edit their own Cards anymore

### ISSUE THREAD

**Issue by srensamblador** [solid/node-solid-server#1166]
I encountered this bug while trying to test my application against a test POD i had laying around. If somemone's profile card gets compromised because his card file isn't a valid document anymore it has an impact in other users PODs.
I had this test user added as a friend in my regular use POD and from that moment on I can't edit my card, I can't remove the corrupt friend nor add new ones, for instance. The fix i found is regenerating the card in the other user's POD but this has some serious implications:
This means that if someone corrupts their profile this affects unrelated PODs from the people who added him/her as a friend. And they can't regain full usage of their profile until the first guy fixes his POD.
This also means that a malicious person could corrupt their own POD to mess with all the people who added him as friend with no way for them to fix it.

**Comment by kjetilk** [comment]
OK, this, I think is a side-effect of the `trustedApp` code we introduced in the last minute. Perhaps it should ignore invalid files?

**Comment by jaxoncreed** [comment]
@srensamblador I've created a corrupted user here (https://corrupteduser.solid.community/profile/card#me) and added it as a friend in a local pod. However, I am still able to edit my profile. How did you corrupt your user. Am I corrupting this user correctly?

**Comment by jaxoncreed** [comment]
@srensamblador could you create a test account for a corrupted user, so that I can try to replicate this?

**Comment by srensamblador** [comment]
> @srensamblador could you create a test account for a corrupted user, so that I can try to replicate this?

I'll try to see if i can create it again because I fixed my app during this time.

Meanwhile addressing your first comment.
My corrupted user didnt really look like that, when you tried to check his card's source code with the </> icon it was empty, 
On the "good" pod that had him added as friend the issues i manage to notice were that i couldn't add or remove friends as I said in the original issue's text and also when I went into the home icon in my profile/card#me a JS alert popped up saying something like "Strange: couldn't load your preferences". This on the good pod.

Now the steps I did to originally have the problem were like this:
GP = good pod, CP = Corrupted pod
* GP adds CP as a friend
* CP logs in my then bugged application
* I read the file data from /profile/card
* Parse it and try to add a new RDF triplet with a new contact (was trying to add friends from my app)
* I didn't serialize the data correctly
* Uploaded the new profile/card to the POD, but it wasnt a valid RDF, regardless the file was updated and the POD's profile got broken
* From now on GP starts having the issues until CP regenerates his pod

The POD i originally corrupted was this one: https://patxielvasco.solid.community/profile/card#me, but I regenerated the profile (although I think its still broken). Password is testUser1! if you want to poke around.

I'll try to recreate the bug it, hopefully I can

By the way, I also bricked another POD updating the card but this time this is the result https://samuelcifuentes.solid.community/profile/card#me
This pod can't login anymore tho, looks like the entire card is gone

Hope I can be of help

**Comment by srensamblador** [comment]
Okey the broken pod looked exactly like this:
https://evilpod.solid.community/profile/card
password: testUser1!

But I can't seem to recreate the bug in the friend's pod, maybe I did something else wrong when it happened, maybe I was logged in as a different user and didn't notice with the panic and everything. Tho I'm pretty sure it happened, I dont want anyone to waste time if I was wrong

**Comment by jaxoncreed** [comment]
Okay. I can confirm that I also cannot recreate the bug with the corrupted user. So, I'm going to close this out.
