### ISSUE TITLE
login not working with Chrome

### ISSUE THREAD

**Issue by michielbdejong** [solid/node-solid-server#1195]
when i select my IDP it doesn't redirect to the login page

This is with 5.1.1

**Comment by michielbdejong** [comment]
@RubenVerborgh do you know how https://localhost:8443/common/popup.html is generated? And why is it called popup.html if it’s displayed in the main window rather than in a popup window?

**Comment by michielbdejong** [comment]
Same problem occurs on 5.0.1 and 5.0.0.

**Comment by michielbdejong** [comment]
This problem only occurs when installing fresh from npm, not with the install I have in my local git checkout. Will see if I can find which package changed that could be causing this.

**Comment by michielbdejong** [comment]
I thought this should be impossible with package-lock.json, but it seems that versions that worked in the past, don't work when I install them now.

**Comment by kjetilk** [comment]
Very strange...  I have no ideas... Perhaps if @megoth is on his feet?

**Comment by RubenVerborgh** [comment]
> @RubenVerborgh do you know how [localhost:8443/common/popup.html](https://localhost:8443/common/popup.html) is generated?

Yes, it's imported from `solid-auth-client` here: https://github.com/solid/node-solid-server/blob/969eb4b1f0b5d511cd4e0cf3974dd9f98a8848c2/lib/api/authn/webid-oidc.js#L106

> And why is it called popup.html if it’s displayed in the main window rather than in a popup window?

It will only work as a popup window.

**Comment by michielbdejong** [comment]
Seems to only happen in Chrome, and not always (but i still haven't found a pattern in when it does and doesn't happen).
Note that in Firefox, it's a popup, and in Chrome it's not.

**Comment by RubenVerborgh** [comment]
Steps to reproduce?

**Comment by michielbdejong** [comment]
It's also happening on inrupt.net and on solid.community. I think probably it happens on all recent versions of NSS when you use Chrome version 74.

**Comment by michielbdejong** [comment]
Wait! Upgrading to Chrome Version 74.0.3729.169 (Official Build) (64-bit) seems to have fixed it! :)
