### ISSUE TITLE
Update documentation to include command for generating self-signed certificate

### ISSUE THREAD

**Issue by boulderwebdev** [solid/node-solid-server#1198]
Can the documentation include instructions for generating a self-signed certificate for development purposes? I used the following commands in the root project director to create my SSL certificates

```
mkdir ssl
sudo openssl req -nodes -x509 -newkey rsa:4096 -keyout ./ssl/key.pem -out ./ssl/cert.pem -days 365

```

**Comment by megoth** [comment]
There's already a section on it in the README, https://github.com/solid/node-solid-server#how-do-i-get-an-ssl-key-and-certificate, or am I misunderstanding you?

**Comment by jaxoncreed** [comment]
It might be a good idea to mention https://github.com/njh/gen-webid-cert in there since it's much easier to create a cert this way.
