### ISSUE TITLE
index page shows login required

### ISSUE THREAD

**Issue by ewingson** [solid/node-solid-server#1201]
## Please describe what you did in reproducible steps

I made a npm remove and new install of nss on a debian system in combination with apache2 and reverse proxy

## How did it work with 4.x series servers?

no appropriate answer since switching from 5.0.1. to 5.1.1

## What happened when you tried the same with the 5.x series server?

I had a similar 'catch 22'-problem with 5.0.1 and fixed it by removing a trailing slash in server-Uri in config.json

## Any material that will help, logs, error messages, etc.

guess will include at least config.json and the root-.acl

config.json
```
{
  "root": "/var/www/html/data",
  "port": "8443",
  "serverUri": "https://solidweb.org",
  "webid": true,
  "mount": "/",
  "configPath": "/var/www/html/config",
  "configFile": "/var/www/html/config.json",
  "dbPath": "/var/www/html/.db",
  "sslKey": "/etc/letsencrypt/archive/solidweb.org/privkey1.pem",
  "sslCert": "/etc/letsencrypt/archive/solidweb.org/fullchain1.pem",
  "multiuser": true,
  "enforceToc": false,
  "disablePasswordChecks": true,
  "supportEmail": "meisdata@gmail.com",
  "server": {
    "name": "solidweb.org",
    "description": "free the web",
    "logo": "logo.png"
  }
}
```
and now root-.acl

```
# Root ACL resource for the root
@prefix acl: <http://www.w3.org/ns/auth/acl#>.
@prefix foaf: <http://xmlns.com/foaf/0.1/>.

<#public>
    a acl:Authorization;
    acl:agentClass foaf:Agent;  # everyone
    acl:accessTo </>;
    acl:default </common/>;
    acl:mode acl:Read.
```
any ideas ?

**Comment by boulderwebdev** [comment]
If you dig around there is a bug with the call here https://github.com/solid/node-solid-server/blob/master/lib/acl-checker.js#L72. This issue popped up before in https://github.com/solid/node-solid-server/issues/994

**Comment by ewingson** [comment]
can anyone tell if `localhost:8443` is right or should it be the world-readable URI `solidweb.org:8443` ? seems like completely regular code for me... any hints what might be misconfigured ? what further debug-info can I supply ?

**Comment by jaxoncreed** [comment]
I think I've seen this before with bad cookies. Does the same thing happen in an incognito window?

**Comment by ewingson** [comment]
yeah, still the same

**Comment by michielbdejong** [comment]
I saw a similar thing while we were upgrading inrupt.net. You're in multiuser mode, and the root domain has a special status among the other folders you should see in `ls /var/www/html/data/`. It gets generated from a template when the server starts and should say 'Welcome to the Solid Prototype
'. One thing you can try:
* stop the server
* mv /var/www/html/data/solidweb.org /var/www/html/data/solidweb.org-bak
* start the server

That should hopefully cause the server to create /var/www/html/data/solidweb.org from scratch.

**Comment by ewingson** [comment]
no effect yet. must be possible to get it working with apache and reverse proxy. next thing to try *might* be leave the apache out.

**Comment by ewingson** [comment]
gonna close it. I ran nss directly and got it working (at least manually). concerning the service I stumbled into a prob with the start intervall. that' d be another thang.

**Comment by michielbdejong** [comment]
\o/
