### ISSUE TITLE
TLS fails to work on 5.1.1

### ISSUE THREAD

**Issue by jaxoncreed** [solid/node-solid-server#1207]
Logging in via TLS with an external webId yields a 401 error

Error: Web error: 401 (Could not verify Web ID from token claims) on PUT of https://timbl.com/timbl/Public/Test/Origins/.dummy
Add another tool to the meeting

**Comment by timbl** [comment]
This was when logging in with a TLS-based webid, which used  to work.

**Comment by michielbdejong** [comment]
Possibly related to @melvincarvalho's issue https://github.com/solid/node-solid-server/issues/1149?
Let's see if we can fix this, let me know if I can help!
