### ISSUE TITLE
Consent disrupts the solid-cli workflow?

### ISSUE THREAD

**Issue by kjetilk** [solid/node-solid-server#1208]
Not sure whether this is an issue with NSS or solid-cli (or both), but here goes:

I've been trying to copy one bunch of files from the filesystem into a pod on dev.inrupt.net, and it stopped with the error: `Error logging in : TypeError: Cannot read property 'match' of undefined`, which didn't say a lot, so I started to debug it. 

So far, I've gotten to https://github.com/solid/solid-cli/blob/master/src/SolidClient.js#L184 which ends up `undefined`, because the `authResponse` comes back with a `200` and no `Location`. Looking at `authUrl`, it is at this point 
https://dev.inrupt.net/consent?response_type=id_token%20token&display=&scope=openid&client_id=5310a99531ac471b44b95c7797312d82&redirect_uri=http%3A%2F%2Fexample.org%2F&state=9MMY7bpx9JYCs2c5Tp0CjtcE7EEsvgbCQq0R1IGlVPM&nonce=&request=eyJhbGciOiJub25lIn0.eyJyZWRpcmVjdF91cmkiOiJodHRwOi8vZXhhbXBsZS5vcmcvIiwiZGlzcGxheSI6InBhZ2UiLCJub25jZSI6IkxSNEU1bW5qWDdRd3M4WnBmcWZGdFQ2R3BocnpxODRtVGhnVWstd01aMU0iLCJrZXkiOnsia3R5IjoiUlNBIiwiYWxnIjoiUlMyNTYiLCJuIjoic0JZMnFrckVPeERMZU9vWGtUZ2FiMFZvOUZYbWx2ejhZMEZpdUJ5dXhsUzVITVpzSWNEM0tHdTZQTkdGSGwwY1VqT09QM2V0RHYwUl9hVHJCVEpXOEVRMFppRzU2RHZZYzlIaW9QOW1GaXplaGlJYzB4S3Rsa25oUjNDNUN6T0VEZzVJd3JKU1JDenQ4T3FQV01wRXEtbm9kNG8wVEs1ajFVVnRMZGx0b0thajhpMWxIVjNpR3pXTEZhRTVCS1JoMDd3WE1ERW5fWGpib1lBeS1mMTBWeFNDamJkRHJ4Rmlva2NyVHF6bmR2U1J1cXZmY2hRM0VNUGhqeFJCMmoxVWhwLV9SMklBY1NFRE5aRFZ6cHdwaUVxclFOcVNEUUNrR1lXOTVwOThiWWFzVnJuSWFsYWpwd0gyQWtpcXE2dDdReUQycjZKdS1mVnVoZ1gwNFFrbDlRIiwiZSI6IkFRQUIiLCJrZXlfb3BzIjpbInZlcmlmeSJdLCJleHQiOnRydWV9fQ.

So, it seems like the consent dialog is inserting itself somewhere in the workflow in a way that breaks stuff.

**Comment by jaxoncreed** [comment]
Fixed in https://github.com/solid/solid-cli/pull/6

**Comment by kjetilk** [comment]
Great stuff! :-)
