### ISSUE TITLE
Trust origin on login

### ISSUE THREAD

**Issue by linonetwo** [solid/node-solid-server#1230]
It's very annoying that I have to add new app origin as trusted.

It's better to trust an origin upon login, and choose ACL for this origin.

If I forget to trust an origin, there will be this error:

```
Access to fetch at 'https://linonetwo.solid.authing.cn/public/tiddlywiki/main' from origin 'http://localhost:8080' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'.
```

which can't help user, and even me to understand what happened.

**Comment by jaxoncreed** [comment]
We do want to ensure that a user has the ability to indicate what an app can and cannot have access to. Though a change in the warning text would be nice.

**Comment by linonetwo** [comment]
Is it ok to embed this form inside the login popup?

<img width="965" alt="屏幕快照 2019-06-17 下午8 18 20" src="https://user-images.githubusercontent.com/3746270/59603876-1f8ede00-913d-11e9-9e12-b18c5e1a346e.png">

**Comment by jaxoncreed** [comment]
Node Solid Server Version 5.1.4 has you covered ;)

**Comment by linonetwo** [comment]
Really? I'm using solid 5.1.5, using `const popupUri = 'https://solid.authing.cn/common/popup.html';` but when I login, there is no such a form in the login popup window.

**Comment by jaxoncreed** [comment]
Right now, if this is your first time logging into `solid.authing.cn` and you have not yet set it as a trusted app, there should be a window that allows you to automatically add it after you successfully login.

**Comment by linonetwo** [comment]
I'm not first time logging into it, so there isn't such option.

How to clear this login counter? Is it client side or server side?

**Comment by jaxoncreed** [comment]
It keeps track of it in your login session, so if you clear your cookies you should be able to see it again.

**Comment by linonetwo** [comment]
No...Clearing cookies doesn't work.

Hope this form can show up just like how Github OAuth works.

**Comment by linonetwo** [comment]
Actually current error message is `PUT https://linonetwo.solid.authing.cn/public/tiddlywiki/main.meta 401 (Unauthenticated)`.

Maybe there should be a popup when `solid-auth-client` run in to this error, for user to add trust to origin.

**Comment by michielbdejong** [comment]
A similar situation happens when you've been logged in to an app for longer than 2 weeks, it starts failing silently. You need to log out and back in again.
Opening a popup from a background process isn't always allowed (the popup will be blocked), but at least if solid.auth.fetch encounters a 401, it should give the developer a change to display a 'please log in again' UI.

**Comment by michielbdejong** [comment]
So is our conclusion that this is not a server-side issue?

**Comment by jaxoncreed** [comment]
@linonetwo Do you need any support on this?

**Comment by linonetwo** [comment]
Can't reproduce! Maybe a version mismatch.

It works locally, but not in my deployed server.

So I'm going to look into https://github.com/solid/node-solid-server/pull/1112#issuecomment-502969603

**Comment by linonetwo** [comment]
<img width="659" alt="屏幕快照 2019-07-03 下午3 48 40" src="https://user-images.githubusercontent.com/3746270/60573397-2ad34200-9daa-11e9-9b35-ba6e4c963e02.png">

I know what is going wrong, it trusted the wrong origin.

If I'm using `solid-auth-client` like:

```js
const popupUri = 'https://solid.authing.cn/common/popup.html';
    if (!session) {
      session = await solidAuthClient.popupLogin({ popupUri });
      (session: SoLiDSession);
    }
```

Then it will try to trust the popup window's origin, instead of the App's origin (localhost:3000).
