### ISSUE TITLE
Can not create files in POD.

### ISSUE THREAD

**Issue by xyunp** [solid/node-solid-server#1232]
Describe the bug
Can not create files in POD. It shows "POST https://xyunp.inrupt.net/public/ 500 (Internal Server Error)500 (Internal Server Error) https://xyunp.inrupt.net/public/"

To Reproduce
const fileClient = SolidFileClient;

fileClient.createFile('https://xyunp.inrupt.net/public/zhy',null,'text/turtle').then( fileCreated => {
console.log('Created file ${fileCreated}.');
}, err => console.log(err) );

Expected behavior
In last week , i use "solid-file-client" to create and write folder and file, it works

Screenshots

Desktop (please complete the following information):

Browser [chrome]
Version [75.0.37]
Additional context

**Comment by michielbdejong** [comment]
Thanks for reporting! We are aware and working on a fix; closing this issue as a duplicate of #1228, you can follow progress there.
