### ISSUE TITLE
Cannot delete a Pod

### ISSUE THREAD

**Issue by kevin-howard-jd** [solid/node-solid-server#1233]
When attempting to delete a Pod on inrupt.net (Solid 5.1.4), I receive a message:

**No permission to access this resource**
You are currently logged in as https://mywebid.inrupt.net/profile/card#me but do not have permission to access https://mywebid.inrupt.net/account/delete/

## To reproduce
1. Log into a Pod on inrupt.net (e.g., https://webid.inrupt.net)
2. Navigate to the /account/delete folder for the Pod (e.g., https://webid.inrupt.net/account/delete)
3. Message is displayed.

## How did it work with 4.x series servers?
Yes.

## What happened when you tried the same with the 5.x series server?
Error message is displayed:

**No permission to access this resource**
You are currently logged in as https://mywebid.inrupt.net/profile/card#me but do not have permission to access https://mywebid.inrupt.net/account/delete/

**Comment by michielbdejong** [comment]
Was able to reproduce this on localhost at https://michielbdejong.localhost:8443/account/delete (see https://github.com/solid/node-solid-server/commit/f42fade4dd1f489ced6dc9c9a9612ba414cbc8b3 for localhost multi-user instructions).

The error is 'Not allowed to access top-level APIs on accounts'.
You should not include the subdomain. When I try https://localhost:8443/account/delete it does work, although there I ran into the error that I don't have email set up on localhost.

To make absolutely sure, I went to https://inrupt.net/account/delete and successfully deleted one of my test accounts.
