### ISSUE TITLE
Unexpected behavior when client omits Content-Type on resource creation

### ISSUE THREAD

**Issue by bourgeoa** [solid/node-solid-server#1256]
@RubenVerborgh

There is a code error in the new ressource-mapper.js 

> line 109    path += `$${contentType in extensions ? `.${extensions[contentType][0]}` : '.unknown'}`

should be (only one $) : 

> line 109    path += `${contentType in extensions ? `.${extensions[contentType][0]}` : '.unknown'}`

The consequences are quite bad for all pods under NSS 5.1.6 (solid.community and dev.inrupt and all others) : 
- files are created with `$.unknown` at the end :
 
-- `ressource test.txt => file test.txt$.unknown` 
-- or `ressource index.html => file index.html$.unknown` (app not working)

- repair of the filesystem is needed, because if you only edit ressource-mapper-js, then when the bad files are edited the 2 above exemples are returned as ressources and files : `test.txt.unknown` and `index.html.unknown` (not usable)

- Strangely the error never appear under the databrowser : ressource creation has the correct extension (tested with the actual ressource-mapper.js and a corrected one)

**Comment by RubenVerborgh** [comment]
The `$` is [by design](https://www.w3.org/DesignIssues/HTTPFilenameMapping.html) and this behavior is explicitly asserted in unit tests.

The `unknown` signals the lack of a `Content-Type`.

**Comment by bourgeoa** [comment]
Ok, I misunderstood that it was indeed by design.

Then it should have been specified and largely commented, so as to check consequences, like when change in webId file was introduced in NSS 5.0.0

I found that it revealed consequences (bugs ) when 'content-type' is not set :
- POST is now buggy :
  - fail with 500 on create file in node (not in browser) (that's why I looked at the filesystem on my test server under docker)
- header returns 'plain/text'
- .html ressource are not understood by the pod web server.
- ...

Work on the new solid-file-client has stopped, because it doesn't pass node tests anymore.

For the above points can you explain where the solution lies, in NSS or in APP like solid-file-client and what to do for the pod web server.

Hope it helps

**Comment by RubenVerborgh** [comment]
Thanks for reporting.
Does everything work when you set a Content-Type (and is anything
preventing you from doing so)? If you rely on extensions, you might want to
use a MIME lookup library.

The previous behavior where the content type was guessed from the extension
was unsafe. Returning text/plain ensures that no weird interpretations are
given to content (but no correct ones either though).

**Comment by bourgeoa** [comment]
Actually solid-file-client is doing the following with POST : 
1. slug with no extension and content-type
2. slug with extension and no content-type

Both are still passing tests in browser.
case 1 resource is created with slugname+extension (is it what you expect from NSS ?)
case 2 is not passing tests in node.

For a better understanding have you an explanation of why such a difference on NSS side ? we use the same API.
Due to the fact that solid pod is a web server and is RDF based on turtle. I am inclined to think that  .html and .ttl resources could have a special treatment in ressource-mapper. It's only my opinion.

If one uses PUT for non RDF files. Will all these files be considered as $.unknown ?

Do you think the solid REST-API should be clarified ?

Sorry for all these questions.

**Comment by RubenVerborgh** [comment]
**Summary: always use a `Content-Type` header when sending a body to any HTTP server.**

For clarity, the Solid specifications only cover the contract between clients and server interfaces, not the contract between the server interface and the file layout on disk.

`ResourceMapper` is written such that it will consistently add and remove `$.` extensions in cases where the URL extension does not correspond to the on-disk extension. Users of the HTTP interface will (and should) never know.

If a client does not like that mechanism, the simple solution is to always use a `Content-Type` that is consistent with the extension.

> * slug with no extension and content-type

This behavior is well-defined and supported.

> * slug with extension and no content-type

This behavior is not defined (not in HTTP, LDP, or Solid), and not supported.
(I suppose we could throw an error though.)

Another behavior that is supported:

* slug with extension, and `Content-Type`

> For a better understanding have you an explanation of why such a difference on NSS side ?

I'm not sure what the two different setups are that you're testing. Can you describe "in browser" and "on Node"?

> Due to the fact that solid pod is a web server and is RDF based on turtle. I am inclined to think that .html and .ttl resources could have a special treatment in ressource-mapper.

All resources should have the correct `Content-Type`. A document whose URL has a `.html` extension but is uploaded with `Content-Type: text/turtle` is a _Turtle_ file.

> If one uses PUT for non RDF files. Will all these files be considered as $.unknown ?

Only if they are uploaded without `Content-Type`, or with an unrecognized one.

> Do you think the solid REST-API should be clarified?

The API does not suggest anywhere that meaning should be derived from the extension, so I don't think that should be changed. The old NSS did it, incorrectly, and that was an HTTP spec violation as well as a security risk.

We _could_ change the fact so state that a `Content-Type` MUST be specified when the client sends a body with an HTTP request, and that the server SHOULD reject requests without that header with a 415.

**Comment by bourgeoa** [comment]
Thank you for your clear and detailed comments.
I did not treated the case you added :
- slug with extension and content-type
because it has allways returned :
- slug with extension + content-type extension
So with slug=test.ttl and Content-Type='text/turtle' then the result of POST is actually **test.ttl.ttl**

If I understand you correctly that is wrong it should be **test.ttl**

Or with test.html and 'text/turtle' the result of POST should be **test.ttl** and not **test.html.ttl**

**Comment by kjetilk** [comment]
There's also #1245 . We should throw a 4xx error and not do anything on the file system if there is no `Content-Type`.

**Comment by RubenVerborgh** [comment]
>  with slug=test.ttl and Content-Type='text/turtle' then the result of POST is actually **test.ttl.ttl**

Hmmm, why is the server appending an extension here…
I don't like that behavior.

I understand that it makes sense if the preferred slug is not available and the server has to mint a URI, but just appending it by default… not a big fan.

> If I understand you correctly that is wrong it should be **test.ttl**

Wrong not necessarily, because a slug is a suggestion. So the server is free to do anything.

But yes, just appending an extension is not something I like.

> Or with test.html and 'text/turtle' the result of POST should be **test.ttl**

Extensions in HTTP URLs do not have a defined meaning, so the server should not randomly chop off or replace extensions.


But such behavior is more cosmetic, so I don't have a strong opinion.

**Comment by RubenVerborgh** [comment]
See also: https://github.com/solid/node-solid-server/issues/1246 (should probably follow up in there)

**Comment by TallTed** [comment]
@RubenVerborgh 
> The previous behavior where the content type was guessed from the extension was unsafe. Returning text/plain ensures that no weird interpretations are given to content (but no correct ones either though).

If anything, resources without a definitive content type should be treated and presented as [`application/octet-stream`](https://www.iana.org/assignments/media-types/application/octet-stream), not as `text/plain`.

`text/plain` may lead many file handlers and downloaders to attempt platform-based `CR`/`LF`/`CRLF` substitutions, which would obviously be bad for actual binary content.

`application/octet-stream` should deliver whatever safety is being perceived in `text/plain`, as both are treated as non-executable document types by all automation of which I'm aware, and not lead to any resource corruption in transit.

**Comment by RubenVerborgh** [comment]
> If anything, resources without a definitive content type should be treated and presented as [`application/octet-stream`](https://www.iana.org/assignments/media-types/application/octet-stream), not as `text/plain`.

Agreed.

**Comment by RubenVerborgh** [comment]
@TallTed Fix in https://github.com/solid/node-solid-server/pull/1258

**Comment by jaxoncreed** [comment]
Fixed in #1282
