### ISSUE TITLE
When accessing the the top of a POD as data the server issues status 500

### ISSUE THREAD

**Issue by SimonShapiro** [solid/node-solid-server#1261]
When I issue a `GET` to the POD root, for example `https://anvil1.inrupt.net/` with a content-type header set to `application/turtle`, I expect to get a ttl representation of the container.  At the very least it should return
```
<> a solid:PodRoot ; solid:owner <profile/card#me>.
```

Ideally it should be the have the `ldp:contains` predicates as well so that a directory-tree can be developed for NSS.

Currently, it returns either the standard `index.html` when no content-type is set, or `status 500` when the content-type is set to `application/turtle`.

**Comment by csarven** [comment]
I can reproduce. Use `text/turtle` instead, but yes the main point stands.

**Comment by jaxoncreed** [comment]
Fixed in #1282
