### ISSUE TITLE
Corrupted profile card after accepting app permission

### ISSUE THREAD

**Issue by jairo-campos-JD** [solid/node-solid-server#1262]
When I logged into my pod, screen permission appeared and asked me if I want to add permissions to my apps when I checked all of these permissions and then I clicked to accept button, my profile card got corrupted and now is showing only permissions instead of my profile data.

https://screencast.com/t/o5tS4H4sqx
https://screencast.com/t/8ErZsd8p

**Comment by michielbdejong** [comment]
Your profile was overwritten with a notification. Try restoring your profile with a profile editor such as https://generator.inrupt.com

Maybe the app you're running on localhost has a bug that makes it send notifications to the profile doc instead of to the inbox?

**Comment by jaxoncreed** [comment]
Cannot replicate at the moment.
