### ISSUE TITLE
Remove External WebID from account creation

### ISSUE THREAD

**Issue by megoth** [solid/node-solid-server#1267]
Many users do not understand the use of this field - we should move the field to a more specialized form, where we can explain the purpose of the field.

**Comment by michielbdejong** [comment]
Was this resolved?

In general, just a heads-up that we'll switch developer efforts from this repo to the new TypeScript code at https://github.com/inrupt/pod-server soon.

**Comment by megoth** [comment]
This was resolved in https://github.com/solid/node-solid-server/pull/1273
