### ISSUE TITLE
Redirect users to their newly created Pod after they have created an account

### ISSUE THREAD

**Issue by megoth** [solid/node-solid-server#1268]
After creating an account with no referrer, the user is simply redirect to the front page of the server. This is not very useful for many users. We should redirect them to their newly created Pod instead.

**Comment by michielbdejong** [comment]
Was this resolved?

In general, just a heads-up that we'll switch developer efforts from this repo to the new TypeScript code at https://github.com/inrupt/pod-server soon.

**Comment by megoth** [comment]
This was resolved in https://github.com/solid/node-solid-server/pull/1272
