### ISSUE TITLE
Redirect users to their Pod after logging in via the server's homepage

### ISSUE THREAD

**Issue by megoth** [solid/node-solid-server#1271]
Today we simply replace the login button with a logout button. Most users would probably expect to be redirected to their Pod.

**Comment by michielbdejong** [comment]
Was this resolved?

In general, just a heads-up that we'll switch developer efforts from this repo to the new TypeScript code at https://github.com/inrupt/pod-server soon.

**Comment by megoth** [comment]
This was resolved in https://github.com/solid/node-solid-server/pull/1274
