### ISSUE TITLE
Remove the generated index.html for newly created accounts

### ISSUE THREAD

**Issue by megoth** [solid/node-solid-server#1275]
The strategy to generate an index.html for the root has several disadvantages, like keeping it up to date as things change. I propose to remove this "homepage" in advantage of a dashboard pane that the data browser will only show when people navigate to the root of a Pod.

**Comment by mikeadams1** [comment]
I don’t think I agree with this at all! It appears to be in contravention of a pod owner/user capacity to do whatever they want with their homepage root index.HTML, Unless I’m misunderstanding something, it appears you intend to take away the index.HTML in return for some dashboard for the user, is this correct?

**Comment by megoth** [comment]
For posterity, I'll answer @mikeadams1 here as well ([answered earlier on Gitter](https://gitter.im/solid/node-solid-server?at=5d36fe83d61887416422a378)). Please continue this thread here.

Do note that you can still edit an index.html for a Pods root, enabling you to create a custom homepage for that Pod. You will have to create an index.html though, which you can do by using the PUT method. If you want us to enable that programmatically through the data browser, I suggest you create an feature request in the [solid-panes repo](https://github.com/solid/solid-panes/issues/new), as that is where such a feature probably will be implemented.

**Comment by Vinnl** [comment]
> It appears to be in contravention of a pod owner/user capacity to do whatever they want with their homepage root index.HTML, Unless I’m misunderstanding something, it appears you intend to take away the index.HTML in return for some dashboard for the user, is this correct?

I think there's some misunderstanding here. This issue is not about removing the `index.html` that users currently have in their Pods - it's about not placing it there in the first place when someone creates a new Pod. People who already have it in their Pod will keep it, as far as this Issue is concerned.

**Comment by mikeadams1** [comment]
why not have a user.dev.inrupt.net/home page.

**Comment by Vinnl** [comment]
The URLs currently represent data in a user's Pod. There is no data in `/home`.

Do note that what you currently see at `dev.inrupt.net` is not the final state (hence the `dev.`).

**Comment by mikeadams1** [comment]
so essenitaly your stating that you want to create a user dashboard and serve it up on index.html of a user pod, is that correct?

**Comment by Vinnl** [comment]
Not exactly, I think. It basically works the same way it does today: any resource in your Pod that is not an HTML file, will give you the Data Browser when visited with your Web browser. The only difference is that we would like to no longer write an HTML file to people's Pods when they create an account. The functionality currently provided by it can also be provided by the Data Browser.

Again, nothing is final, so if there's any functionality you think you're going to miss, do let us know.

**Comment by mikeadams1** [comment]
https://github.com/solid/solid-panes/issues/132

**Comment by mikeadams1** [comment]
Ok, I think i understand what your talking about, and am in agreement with it, can I see what the concept of this page looks like? can you provide a link to it>

**Comment by megoth** [comment]
We will have something up on dev.inrupt.net during the next couple of days, you'll see more then.

**Comment by mikeadams1** [comment]
It may be nice to have a bullet to drag and drop profiles into the home page, like you can on /profile/card#me 

Other suggestions can be seen on https://inside.dev.inrupt.net/

**Comment by michielbdejong** [comment]
Was this resolved?

In general, just a heads-up that we'll switch developer efforts from this repo to the new TypeScript code at https://github.com/inrupt/pod-server soon.

**Comment by megoth** [comment]
This was resolved in https://github.com/solid/node-solid-server/pull/1276
