### ISSUE TITLE
Allow write function to root index.html through source code editor in the data browser

### ISSUE THREAD

**Issue by mikeadams1** [solid/node-solid-server#1278]
Allow save edits function of root index.html via "source" feature in data browser.

**Comment by michielbdejong** [comment]
I think this is a databrowser feature request, see linked issue there ^
Please reopen if you think this requires any code changes in node-solid-server.

In general, just a heads-up that node-solid-server is being rewritten in TypeScript, and we'll be switching over to that in a number of weeks from now.
