### ISSUE TITLE
header.test.js : WAC-Allow third test is broken

### ISSUE THREAD

**Issue by bourgeoa** [solid/node-solid-server#1285]
## Please describe what you did in reproducible steps
`npm run test` : on NSSv5.1.1 to NSSv5.1.6
I came to that with PR #1282 

## How did it work with 4.x series servers?
all test passed on NSSv4.4.2

## What happened when you tried the same with the 5.x series server?

>  1) Header handler
>        WAC-Allow
>          a resource that is read/write/append/control for the user, nothing for the public
>            "before all" hook:
>      Error: Timeout of 10000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/volume1/homes/admin/github/awwright/node-solid-server/test/integration/header-test.js)
> 

## Any material that will help, logs, error messages, etc.
Here is the faulty test

`    describeHeaderTest('read/write/append/control for the user, nothing for the public', {
      resource: '/user-rwac-public-0',
      headers: {
        'WAC-Allow': 'user="read write append control",public=""',
        'Access-Control-Expose-Headers': /(^|,\s*)WAC-Allow(,|$)/
      }
    })
`
 I broke the test in two : 
-         'WAC-Allow': 'user="read write append",public=""',
here the test fail saying that a WAC-Allow need to be defined for `public`
-        'WAC-Allow': 'user="read write append control",public="read"',
here the timeout came back.

As it is the test is not pertinent in NSSv5 and should be revisited.

**Comment by michielbdejong** [comment]
Hi @bourgeoa, thanks for reporting!

Just a heads-up, if all goes well, it will now be a matter of just weeks until this code is deprecated in favour of the TypeScript rewrite that is taking place in https://github.com/inrupt/pod-server.

It does remind me though, I should really resolve https://github.com/inrupt/wac-ldp/issues/47 before we switch inrupt.net and solid.community over to the new TypeScript code! :)

Let's talk about the switchover process, are you running node-solid-server on your own server, on localhost, or testing against one of those two main deployments?

**Comment by bourgeoa** [comment]
I am running tests on node-solid-server multiuser on my own server deployment is made with docker. As I explained in PR # 1282 I run thests on v4 and v5 versions including v5.1.6. By the way I don't understand why PR # 1282 receives no comment as last solid.community version is broken for weeks for a good part of users and dev community. Can you check the PR ?

**Comment by michielbdejong** [comment]
@bourgeoa let's have a video chat to discuss how we can proceed!

**Comment by jaxoncreed** [comment]
I'm going to assume that because all tests are working now and #1282 is merged in, this issue is fixed.
