### ISSUE TITLE
reduced solid server/api/microservice

### ISSUE THREAD

**Issue by ludwigschubi** [solid/node-solid-server#1295]
Are there any plans to develop a more reduced node-solid-server, one that doesn't serve html except for the views (account registration, -deletion, -recovery & login)?

It seems to me like the ability to develop your own website by editing index.html is only interesting for some users and not necessarily for everyone that wants to make use of solid to better store data.

Most people that I talked to, in the still ongoing development of a new pod interface, said that they don't know coding. Therefore I don't think that most people are interested in this feature.

Considering the recent bugs around this feature and the amount of time it takes to fix it, it has not been a nice experience for persons who are trying to develop an application that makes use of pods since all the container endpoints containing these index files are broken.

I also think that for the kind of providers who want to decouple the data storage/account management from applications/interfaces it should be enough if every endpoint serves data only (meaning also no databrowser).

Maybe this is the wrong place to ask about something like this but I was just wondering whether there are people who are working on something like this/have already integrated a reduced solid server into their architecture or whether there were plans like this before but they got abandoned.

**Comment by jaxoncreed** [comment]
Yes. We're working on a replacement to Node Solid Server at https://github.com/inrupt/pod-server. This architecture is a lot more modular and you'll be able to build whatever configuration you want. So someone could pick that up and build any user experience they want.
