### ISSUE TITLE
/profile/card should not use searchIndex in resource-mapper.mapUrlTofile

### ISSUE THREAD

**Issue by bourgeoa** [solid/node-solid-server#1297]
since NSSv5.1.6, `searchIndex` is used to check if `index.html` is part of a container.

All files including `/profile/card` should map to file `url with $.extention` 
Actually in resource-mapper.mapUrlToFile, the check is made only if searchIndex is true, that is wrong.

in PR #1282 this exclusive point is corrected in resource-mapper.mapUrlToFile + added test
There should be a test to check that when searchIndex is false and there is an index.html in the folder then `resource-mapper.mapUrlToFile(folder, searchIndex = false)` returns folder and not folder/index.html.

**Comment by michielbdejong** [comment]
I never understood what the `searchIndex` means. The ResourceMapper is one of the most dense files in this entire repo. We're not using any variable by that name in the new code.

**Comment by bourgeoa** [comment]
- If searchIndex value is true and URL is a container then you look for index.html in that container.
- In GET if accept text/html then you set searchIndex to true.

Basically I think that what was wrong in mapFileToUrl is that by default the parameter was set to true. (lmho) It should have been set to false to force to explicitly set it to true by CRUD when needed.

The initial problem I suppose came from the fact that all tests passes, as I suppose there is no test to check that a GET with no accept text/html returns the container URL and not the index.html URL.

**Comment by bourgeoa** [comment]
> 
> 
> I never understood what the `searchIndex` means. The ResourceMapper is one of the most dense files in this entire repo. We're not using any variable by that name in the new code.

@michielbdejong 
The search of Index.html is used to display the web app inside the databrowser dokieli pane
For example a click on /public/test/ containing index.html display the web app in /public mashlib dokieli pane.

In that use case you do not have access to the content of /public/test which is considered to be a web app

hope it helps.
It does not work if index.html is too big see https://github.com/solid/solid-ui/issues/114

**Comment by jaxoncreed** [comment]
I have tested your pull request and it all looks good to me. I've merged it in.
