### ISSUE TITLE
Add support for alternative data stores

### ISSUE THREAD

**Issue by boulderwebdev** [solid/node-solid-server#1299]
## Problem
Right now `node-solid-server` depends on a local filesystem to serve files from user's pod. This creates problems while scaling because it limits my options to fuse based drivers backed on an S3 server. Instead of depending on one of these drivers, which have very limited performance, it would be nice if I could call S3 directly. Since we wouldn't want to limit `nss` maintainers from a single service, it would be better if there was an abstract storage driver and an optional parameter for specifying a custom storage driver.

## Feature Request
Can there be an abstraction over file system based operations so we can build custom drivers for whatever storage service we want to use? I want to build a driver for making S3 calls directly

**Comment by bourgeoa** [comment]
May be you could have a look to https://github.com/jeff-zucker/solid-rest a client-side API which supports any backend for Solid requests. @jeff-zucker

**Comment by boulderwebdev** [comment]
@bourgeoa that looks a little different from what I'm needing. I'm going to close this issue as this problem is discussed [here](https://github.com/solid/node-solid-server/issues/483) and [here](https://github.com/solid/node-solid-server/pull/702).
