### ISSUE TITLE
It is necessary to take into account port number in loginurl

### ISSUE THREAD

**Issue by etcware** [solid/node-solid-server#1302]
## Please describe what you did in reproducible steps
I installed solid-server on a debian server as described in https://solid.inrupt.com/docs/installing-running-nss with a specified domain and a port (8443), without a proxy (at the moment). The loginurl (in https://github.com/solid/node-solid-server/blob/0555e66f35ea0248a45bbe5249a125d4fb15b53e/lib/requests/auth-request.js) doesn't take into account the port so navigation doesn't work. It works if I put in config.json   

    "serverUri": "https://myserverurl:8443",

I think that in auth-request.js line 214 it is necessary combine also the port number in loginurl, and it must be specified that the port number is the front end one.
## How did it work with 4.x series servers?
I don't know.

**Comment by jaxoncreed** [comment]
Hmm, that's very strange. Thanks for pointing that out.

Could you share your config file? Does the server URI include the port like the example config below?

```
{
  "root": "/Users/m/inrupt/node-solid-server/data",
  "port": "8443",
  "serverUri": "https://localhost:8443",
  "webid": true,
  "mount": "/",
  "configPath": "./config",
  "configFile": "./config.json",
  "dbPath": "./.db",
  "sslKey": "../privkey.pem",
  "sslCert": "../fullchain.pem",
  "multiuser": true,
  "enforceToc": false,
  "disablePasswordChecks": false,
  "supportEmail": "",
  "server": {
    "name": "localhost",
    "description": "",
    "logo": ""
  }
}
```

**Comment by etcware** [comment]
> Il giorno 27 set 2019, alle ore 23:00, jaxoncreed <notifications@github.com> ha scritto:
> 
> Hmm, that's very strange. Thanks for pointing that out.
> 
> Could you share your config file?
> 

> Does the server URI include the port like the example config below?
> 
> 

Yes, I correct serverUri with the port number and it works, sorry I didn’t understand that the port must be specified both in port parameter and in serverUri.
Thanks
