### ISSUE TITLE
Solid apps cannot detect that NSS is a Solid server

### ISSUE THREAD

**Issue by Vinnl** [solid/node-solid-server#1314]
If I've understood this correctly, there are two ways for a client app to know whether it can update a resource:

- The resource includes the header `Accept-Patch: application/sparql-update`
- The resource includes the header `MS-Author-Via: SPARQL`

As far as I can see, NSS returns the latter, though not the former. This would be fine, except that client-side code running on a different server cannot access that header unless the server also includes it in the CORS header `Access-Control-Expose-Headers: MS-Author-Via`. Currently, NSS does not do that.

Unfortunately, since rdflib 0.20.3, it is now checking for these two headers before updating a Document. Since it cannot find them, it assumes NSS is not a Solid server, and will error out without updating the Document.

**Comment by michielbdejong** [comment]
Wait, so how does patching an RDF doc work at all with rdflib >=0.20.3 then?

**Comment by jaxoncreed** [comment]
Do you know if this patch to RDFlib was made based on a spec change somewhere?

**Comment by Vinnl** [comment]
@michielbdejong More details can be found at https://github.com/linkeddata/rdflib.js/issues/359, but the gist of it is that rdflib used to check whether it had seen a triple `<url to patch> rdf:type ldp:Resource`.

@jaxoncreed It was not removed based on a spec change. The check mentioned above had the following comment:

    // Hack for the moment @@@@ 2016-02-12

That was then [removed by @timbl](https://github.com/linkeddata/rdflib.js/commit/11519162df4d31067a5c175686a29532552f2bea#diff-0aaa1c3585187a3868b62f3bcdca96f4L103) with the comment `is not the solid protocol`.
