### ISSUE TITLE
user not logged in 2

### ISSUE THREAD

**Issue by michielbdejong** [solid/node-solid-server#1317]
I'm now switching users a lot and often seeing this error in the login dialog. It seems to be coming from https://github.com/solid/node-solid-server/blob/b7b5bffd1b94f4976c04c3cf845854efecc81168/lib/requests/sharing-request.js#L149

**Comment by jaxoncreed** [comment]
Ah interesting. This should be prioritized for NSS bugfixing

**Comment by jaxoncreed** [comment]
Okay I know generally why this problem is happening, but not enough to recreate it.

@michielbdejong Is there a step by step thing that works for you to recreate this problem?

**Comment by michielbdejong** [comment]
I think the way to recreate is to log in as one user and then as another, i'll try it out now

**Comment by michielbdejong** [comment]
Tried but failed to reproduce it now, sorry. I am almost entirely sure that this has something to do with multiple user accounts. It seems to happen when I'm testing an app with multiple webid's that are all at the same pod provider.

**Comment by michielbdejong** [comment]
Got it:
```sh
curl 'https://inrupt.net/sharing?scope=openid&client_id=d08a255b1f2d7cdd1825d95f1c05c508&response_type=id_token%20token&request=eyJhbGciOiJub25lIn0.eyJyZWRpcmVjdF91cmkiOiJodHRwczovL2dlbmVyYXRvci5pbnJ1cHQuY29tL3dlbGNvbWUiLCJkaXNwbGF5IjoicGFnZSIsIm5vbmNlIjoiY2EzdU0yZnhDelpXSUlHOGtDU2ZSUXlaaWwxNmtqZ3lEa2NOTkRsMlFFcyIsImtleSI6eyJhbGciOiJSUzI1NiIsImUiOiJBUUFCIiwiZXh0Ijp0cnVlLCJrZXlfb3BzIjpbInZlcmlmeSJdLCJrdHkiOiJSU0EiLCJuIjoib3Y3MndoQk1FR0s1R1hmaEEwalFuY1ZxN0gtMGdtS1JpR2RoTEhQcDh3T1dIN05VT0ZPcjVWTGxwWFlZQzBEVWtTckhiemZMRmMtWVhZcTAxVlZyYTRoaUZlUWNfSWs3SDFGd19vcTdOOF9wT1N1WFlmZmM3bllIYnIwenFxR20tdmI0ZW1tZ2Z0STdIWkg5VFF3Q3c3RFNUZDJiWDZtSEdYdExOQVF0M0ZrQ1FLT3pxRFpNNV91dkJGMlI5b0NvZlJ5dTJBcnZackpweWRTMXZQVEllWFpmUGVaRmtCNEZJVVFtZGw3MXU2M0Nqa1VCRDVrS2pxT1RwZkFBVEE4NDBpc0NfNzdveVJhR1lfWm4wbld2NERjMkxzS1B4TWczZnF6c2lkdVZkTGEwVDZmbkhwZUJMNW00czFRb2JIRzRJRFlWN1A4UnU2TDV2Y0NNclpsRjd3In19.&state=bSXVv_pteDNxsXmtMFxTlZLx09gghttih0yWl6zV-BU' -H 'Connection: keep-alive' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache' -H 'Upgrade-Insecure-Requests: 1' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.70 Safari/537.36' -H 'Sec-Fetch-User: ?1' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3' -H 'Sec-Fetch-Site: cross-site' -H 'Sec-Fetch-Mode: navigate' -H 'Referer: https://generator.inrupt.com/login' -H 'Accept-Encoding: gzip, deflate, br' -H 'Accept-Language: nl-NL,nl;q=0.9,en-US;q=0.8,en;q=0.7,fr-FR;q=0.6,fr;q=0.5,de-DE;q=0.4,de;q=0.3,es-ES;q=0.2,es;q=0.1,id-ID;q=0.1,id;q=0.1' -H 'Cookie: connect.sid=s%3AaAj3-e7RvsKvVRdDSf_aUlRGQgevVORy.k2lia2B02jQRZiPl9HVheee6KIQ%2FqDxxFRFj0OJBbpo' --compressed

**Comment by michielbdejong** [comment]
It seems to be related to multiple different apps all using https://solid.community/common/popup.html as the popup. If on https://inrupt.net you are already logged in because you used a different app first. Clearing the cookies generally helps.

**Comment by jaxoncreed** [comment]
Right. It generally has to do with the application authorization flow, so it would affect multiple apps.

**Comment by jaxoncreed** [comment]
Able to reproduce it. For some reason during the login request here (https://github.com/solid/node-solid-server/blob/master/lib/requests/login-request.js#L143) The Session is

```
{ "cookie": { "originalMaxAge": 86400000, "expires": "2019-11-05T22:55:56.655Z", "secure": true, "httpOnly": true, "domain": ".dev.inrupt.net", "path": "/" }, "userId": "https://jackson.dev.inrupt.net/profile/card#me", "subject": { "_id": "https://jackson.dev.inrupt.net/profile/card#me" } }
```

But upon doing a request for sharing here (https://github.com/solid/node-solid-server/blob/master/lib/requests/sharing-request.js#L73), the session is:

```
{"cookie":{"originalMaxAge":86400000,"expires":"2019-11-05T22:58:01.441Z","secure":true,"httpOnly":true,"domain":".dev.inrupt.net","path":"/"}}
```

And this only seems to happen when you have an old `cookie.sid`

**Comment by michielbdejong** [comment]
maybe one cookie is on the subdomain and the other is on the root domain?

**Comment by TallTed** [comment]
Using a cookie named `sid` (which I think is what is meant by `cookie.sid`) tends to be problematic, because *everyone* uses it, and because collisions between root and subdomains happen.

Much better to name the cookie with some reference to the app or tool writing it, e.g., `{app}-sid`.

**Comment by jaxoncreed** [comment]
Thanks for the tip @TallTed. Changing the cookie name seemed to help, though we should keep an eye on this in case it comes up again.

**Comment by jaxoncreed** [comment]
Fiexed in #1340
