### ISSUE TITLE
.mp3 files uploaded with dataBrowser as .mp3$.mp3

### ISSUE THREAD

**Issue by bourgeoa** [solid/node-solid-server#1318]
see https://github.com/solid/folder-pane/issues/5 from @timbl 

resource-mapper is creating the file `foo.mp3` as `foo.mp3$.mp3`
contentType of .mp3 is audio/mpeg but iana extension for audio/mpeg is mpga.

So the check is a `false wrong match` and resource-mapper is creating foo.mp3$.mp3
I think it should be foo.mp3

It can be generalized so that resource-mapper.mapUrlToFile returns foo.ext and not foo.ext$.ext

**Comment by jaxoncreed** [comment]
This is a pretty bad problem. Would you like to make a pull request with a fix? Otherwise, I'll get around to fixing this.

**Comment by bourgeoa** [comment]
I am traveling until tomorrow and moving my server, so cannot propose
anything today. If you don't fix it before I shall try to propose a PR
tomorrow

Le mer. 16 oct. 2019 à 21:17, jaxoncreed <notifications@github.com> a
écrit :

**Comment by jaxoncreed** [comment]
@bourgeoa I cannot reproduce this. Could you send me the CURL of the request and the configuration of your NSS

**Comment by bourgeoa** [comment]
I am using NSSv5.2.0 on a docker installation https://alain.bourgeoa.ga/public/music/
there are 3 files created using the + button from the databrowser.
I join a copy of the files in the filesystem. As you can see there is a $.mp3 extension to the mp3 file

![2019-10-18 (2)](https://user-images.githubusercontent.com/2218470/67128775-04240480-f1fd-11e9-9312-2a296543fd00.png)

I don't use curl. Can you send me an example.

I am finalizing a PR fix. I must first test it on my server
it takes in consideration that the file extension as to be one of the allowed extensions for the contentType and not only the first one as it is actually done.

**Comment by Ryuno-Ki** [comment]
You can use the [context menu in Network Monitor](https://developer.mozilla.org/en-US/docs/Tools/Network_Monitor/request_list) to copy a request as cURL.

**Comment by jaxoncreed** [comment]
If you're already working on a fix, then that's fine. But for future reference, as @Ryuno-Ki pointed out, you can usually right-click on the request and copy it as CURL

![image](https://user-images.githubusercontent.com/5464743/67243523-bfc77d00-f425-11e9-9861-cf28a36a69e7.png)

**Comment by bourgeoa** [comment]
see PR #1328
