### ISSUE TITLE
PUT do not store body for .json files

### ISSUE THREAD

**Issue by bourgeoa** [solid/node-solid-server#1339]
There are different problems related to creation of a .json file with PUT : 
You need a valid JSON body but not only : 
- text body return error 400
- JSON body like "{}" or `{"foo":"test"}` return 200 with a `void body` (filesize = 0) whatever the JSON body content

> curl "https://alain.bourgeoa.ga/public/test-folder/test.json" -X PUT -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0" -H "Accept: */*" -H "Accept-Language: en-US,en;q=0.5" --compressed -H "Referer: https://www.bourgeoa.ga/solid-ide-v1/?url=https://alain.bourgeoa.ga/public/test-folder/" -H "Content-type: application/json" -H "authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiI0YTFjNTQzMTRkZGE1OTI5N2U5NTA2MDAyNDE1NzNmMSIsImF1ZCI6Imh0dHBzOi8vYWxhaW4uYm91cmdlb2EuZ2EiLCJleHAiOjE1NzI5NzE3NDgsImlhdCI6MTU3Mjk2ODE0OCwiaWRfdG9rZW4iOiJleUpoYkdjaU9pSlNVekkxTmlJc0ltdHBaQ0k2SW5JMk1WOXNkMnRGVDFBMEluMC5leUpwYzNNaU9pSm9kSFJ3Y3pvdkwySnZkWEpuWlc5aExtZGhJaXdpYzNWaUlqb2lhSFIwY0hNNkx5OWhiR0ZwYmk1aWIzVnlaMlZ2WVM1bllTOXdjbTltYVd4bEwyTmhjbVFqYldVaUxDSmhkV1FpT2lJMFlURmpOVFF6TVRSa1pHRTFPVEk1TjJVNU5UQTJNREF5TkRFMU56Tm1NU0lzSW1WNGNDSTZNVFUyTlRJNE5qVTROeXdpYVdGMElqb3hOVFkwTURjMk9UZzNMQ0pxZEdraU9pSmhNVEZrTXpRd05tVXlaR0V4TmpZeElpd2libTl1WTJVaU9pSmZiMFJWUlhvNGVuRmhWemhmWjNwU1pGZ3pWVjkzVUVkeFNXdFVTekY0VFVOVmNrNWFSek4wY0dkdklpd2lZWHB3SWpvaU5HRXhZelUwTXpFMFpHUmhOVGt5T1RkbE9UVXdOakF3TWpReE5UY3paakVpTENKamJtWWlPbnNpYW5kcklqcDdJbUZzWnlJNklsSlRNalUySWl3aVpTSTZJa0ZSUVVJaUxDSmxlSFFpT25SeWRXVXNJbXRsZVY5dmNITWlPbHNpZG1WeWFXWjVJbDBzSW10MGVTSTZJbEpUUVNJc0ltNGlPaUoyY2xCUGFteFhMVWh6WVVsV1JXbDFSMFZoT0U0M2FFeGFWRzUyYUcxVmVteHhVREJNU1VaaVJ6SjJWV1pLZDBodU9FazNUM0ptVkZsSWVtaFJOMGhVVjI1ZlFqazBURU4yUVV0NmEzWlFjSGxXT0hZM2FVSmtUa1ZhUVhsaVRWbDVZbTlST1hkNVJsaHhNMGRUVmxob2VFRlFSRVJSTm5KM1QzVjBVM2RwWjNaalFWbGZiMWt4Y2xoMU16QmhiWEEyZGxCUlZXdEJjbmhLUld0SFZVdHBZMVJpVjBwUVZUVnlWREp6V2s4eWVWSk5jV04xWVY4eVRXUnBTR1puUVc5ME1GZGtkVWxwYlZkMmNqazBORjlRZDNST2FsRmFZekJZZDB4cGRDMUdTVEIxZDAxNFNUQk1lVUZKYTA5dVJITk1kbHBuWm5SRWJsTmxSbFpmUTAwMWNqVjFNRjk1ZWpaUVJUWktVbXRSYldkVFYyaHRhamhzUzFOMlJGUXhSaTFTVGxOemNYRkVSWGhWYjNsMFQzUm1NR3RSVERGRlJEVkxMVFZzVVhCWlMwWnJhRXhxZVRSM1RIWm1iRkIyYWxORFFtTkNlSGNpZlgwc0ltRjBYMmhoYzJnaU9pSlZWMWRDWVdrMVgzRnpOM1IwVFc1elRuaGZlRWxSSW4wLkV3Q2dXNFlqLWZqbUx5a1BTa2pVUnozbVFhOXVUYTBiWW5HNXk0VGVGLXhOM1FlZ1BEeE1IZGkwRnFNQU44MktMQjJodVRsMmhHdGZGd1l1NTRNMnp5UDVacEJlZTd4LV9FaWRGYWNTdE4xbXRGdjBMTm5jeTdyZllrQ194WW9pZGJLaE9XYnR4MjRuOFFObEt5XzF6LUwyOVllbWhqYjF4ODlmWFcxSVN0QVd0TUdjYVFaT0p3XzhyeEZIVmpCVkVmVWFRVWg2R1RHYlFxUkdneldacm9nWFU3LUUya0pjTlI1cUtQVWNGbXU4ZzVJVUdkdEFSSWJETzhBNXFFVFZrNl9CbmtYOGtZLUJKVXVFYzk3d3FWWDJOWWRBZTJTSm44ZEJvTlNLMTBwRFd2V3BPcXd3cnlWdTIzekV2LTRiUFpMdXZTdVh0eFB5RzZBVHBUNlpFUSIsInRva2VuX3R5cGUiOiJwb3AifQ.t7jg9ATAkssdlY14vMrOmMgsxwD9vBrl78Zvl4urcsZBpYMt9UCBTHFcTFTAVZDqVAs352URcoogIIbWsr7w7Xe7SJS1HDOVAYWITcC2RYkf9pXSrpLGKq2iOOKQg8zwMxcEWNJ_8fIGHRmnEYBFrITId66-cZffzOsjKvm0SuiVPJa6p_HbXGqWkScyqB-nHIKehjMWPKIUlwbDvNcsDjrbyBos2yoRKC97R0s68lGH6Ng69XDLW7byU470OjmShlxAL3xNcWrH8DumxjUSAj4EOWY-wGDW8OfnJEz-pCnP3a3Xww8zqY3LSRpgkgQj6RzmRGEp_CIWBEtoIECEUg" -H "Origin: https://www.bourgeoa.ga" -H "Connection: keep-alive" -H "Cookie: connect.sid=s"%"3ASQZ3s9_FEnuju8xTbb3TTHCm5_mS36DT.zZdozqw03l46CqoPiB"%"2Fxx30LM0zTxNOGOSWJCu7sQcQ" -H "TE: Trailers" --data "{}"

**Comment by TallTed** [comment]
@bourgeoa - For best results with long commands like the above, you should wrap it in backticks -- as some inline characters may otherwise be treated as markdown, among other concerns. The simple `>` quote leader doesn't prevent markdown interpretation.

A full codefence (leading and following lines of triple-backticks) can also be used, but does prevent linewrapping in the webpage rendering.

**Comment by bourgeoa** [comment]
@TallTed thanks I shall try to remember. Backticks added.
@jaxoncreed I tested with POST and there is no problem to create .json resource. It is the way followed by solid-file-client
