### ISSUE TITLE
Profile card contains localhost urls instead of serverUri

### ISSUE THREAD

**Issue by pheyvaer** [solid/node-solid-server#1351]
When creating a new user the corresponding profile card uses localhost urls instead of the url provided by `serverUri`. For example, I get this

```
@prefix solid: <http://www.w3.org/ns/solid/terms#>.
@prefix foaf: <http://xmlns.com/foaf/0.1/>.
@prefix pim: <http://www.w3.org/ns/pim/space#>.
@prefix schema: <http://schema.org/>.
@prefix ldp: <http://www.w3.org/ns/ldp#>.

<>
    a foaf:PersonalProfileDocument ;
    foaf:maker <https://localhost:8443/profile/card#me> ;
    foaf:primaryTopic <https://localhost:8443/profile/card#me> .

<https://localhost:8443/profile/card#me>
    a foaf:Person ;
    a schema:Person ;

    foaf:name "Ash Test" ;

    solid:account </> ;  # link to the account uri
    pim:storage </> ;    # root storage

    ldp:inbox </inbox/> ;

    pim:preferencesFile </settings/prefs.ttl> ;  # private settings/preferences
    solid:publicTypeIndex </settings/publicTypeIndex.ttl> ;
    solid:privateTypeIndex </settings/privateTypeIndex.ttl> .
```

while I expected this
```
@prefix solid: <http://www.w3.org/ns/solid/terms#>.
@prefix foaf: <http://xmlns.com/foaf/0.1/>.
@prefix pim: <http://www.w3.org/ns/pim/space#>.
@prefix schema: <http://schema.org/>.
@prefix ldp: <http://www.w3.org/ns/ldp#>.

<>
    a foaf:PersonalProfileDocument ;
    foaf:maker <https://ash.runi.ilabt.imec.be/profile/card#me> ;
    foaf:primaryTopic <https://ash.runi.ilabt.imec.be/profile/card#me> .

<https://ash.runi.ilabt.imec.be/profile/card#me>
    a foaf:Person ;
    a schema:Person ;

    foaf:name "Ash Test" ;

    solid:account </> ;  # link to the account uri
    pim:storage </> ;    # root storage

    ldp:inbox </inbox/> ;

    pim:preferencesFile </settings/prefs.ttl> ;  # private settings/preferences
    solid:publicTypeIndex </settings/publicTypeIndex.ttl> ;
    solid:privateTypeIndex </settings/privateTypeIndex.ttl> .
```

where `https://ash.runi.ilabt.imec.be` is the value of `serverUri` my `config.json`.

**Comment by jaxoncreed** [comment]
What does your config file look like? If you haven't set your serveruri correctly, it will create profile files with localhost.

**Comment by pheyvaer** [comment]
This is my config:

```
{
  "root": "/users/pheyvaer/ash/data",
  "port": "8443",
  "serverUri": "https://ash.runi.ilabt.imec.be",
  "webid": true,
  "mount": "/",
  "configPath": "./config",
  "configFile": "./config.json",
  "dbPath": "./.db",
  "sslKey": "./ssl-key.pem",
  "sslCert": "./ssl-cert.pem",
  "multiuser": false,
  "server": {
    "name": "ash.runi.ilabt.imec.be",
    "description": "RUNI Solid Server",
    "logo": ""
  }
}
```

**Comment by jaxoncreed** [comment]
I think that these might be related: https://github.com/solid/node-solid-server/issues/1357

If it still doesn't work after restarting your server, could you post your file from /.db/oidc/users/_key_YOUR_WEBID.json

**Comment by pheyvaer** [comment]
This is the content of the requested file:
```
{"username":"ash","webId":"https://ash.runi.ilabt.imec.be/profile/card#me","name":"Ash","email":"pheyvaer.heyvaert@ugent.be","externalWebId":"","hashedPassword":"$2a$10$92i.l9KqmB0uojMtaXG97OQ7/DhQLd56DafYeOX30OILTvlvWlx5C"}
```

**Comment by bourgeoa** [comment]
> I think that these might be related: #1357

It seems your `serverUri` is incorrect it should end with `8443`.
It can be an other port if that other port is redirected to `8443`. NSS runs on that port

**Comment by pheyvaer** [comment]
Why? On localhost it runs on 8443, but https://ash.runi.ilabt.imec.be is on port 80 via Nginx, which is proxied to `http://localhost:8443`.

**Comment by bourgeoa** [comment]
Ok it was the end of my comments, then you shall proxy :
from  https://ash.runi.ilabt.imec.be:443/ 
to https://ash.runi.ilabt.imec.be:8443/

**Comment by pheyvaer** [comment]
But what has that to do with the content of the card file?

**Comment by bourgeoa** [comment]
Have you rebuild from scratch ?
When there is an error with the serverUri webId defaults to localhost:8443

this is my config.json

{
  "root": "./data",
  "port": "8443",
  "serverUri": "https://bourgeoa.ga",
  "webid": true,
  "mount": "/",
  "configPath": "./config",
  "dbPath": "./.db",
  "sslKey": "./sslforfree/privkey.pem",
  "sslCert": "./sslforfree/cert.pem",
  "multiuser": true,
  "corsProxy": "/proxy",
  "useEmail": true,
  "emailHost": "smtp.gmail.com",
  "emailPort": "465",
  "emailAuthUser": "alain.bourgeois10@gmail.com",
  "emailAuthPass": "xxxxxxxxx"
}

As you can see I have no `configFile`, but a `multiUser` and  and a
`corsProxy`
I use a proxy nginx from https://bourgeoa.ga:443 to https://bourgeoa.ga:8443,
I run in a docker but it should not change anything
I don't know if multiUser: false is working with https

That is my best, hope it helps. Never had a problem and running lots of
different NSS versions

Le mer. 20 nov. 2019 à 10:36, Pieter Heyvaert <notifications@github.com> a
écrit :

**Comment by jaxoncreed** [comment]
@pheyvaer Tell me if @bourgeoa 's suggestion worked for you.

I'll close this for now, but will reopen if you're still experiencing a problem.

**Comment by pheyvaer** [comment]
No it's not solved.

**Comment by TallTed** [comment]
@jaxoncreed - Flagging [the above](https://github.com/solid/node-solid-server/issues/1351#issuecomment-557918024), as comments on closed issues are easily overlooked.

**Comment by pheyvaer** [comment]
@RubenVerborgh

**Comment by RubenVerborgh** [comment]
@pheyvaer After the config was set to non-localhost, have the templates been regenerated as well?

**Comment by pheyvaer** [comment]
@RubenVerborgh What do you mean with "templates"?

**Comment by RubenVerborgh** [comment]
@pheyvaer The `config` folder contains `templates` and `views` subfolders; they might get outdated.

That said, I've just checked, and the URLs in question are in the template in their entirety, so it is the server that populates them with the wrong value. Can you `grep` the `config` and `data` folders for `localhost`?

**Comment by bourgeoa** [comment]
> Ok it was the end of my comments, then you shall proxy :
> from https://ash.runi.ilabt.imec.be:443/
> to https://ash.runi.ilabt.imec.be:8443/

I went to your pod and I can access [https://ash.runi.ilabt.imec.be](url) but not [https://ash.runi.ilabt.imec.be:8443](url) , I think either you do not proxy from 443 to 8443 or port 8443 is not open : could you check ? and see if you can access.

**Comment by pheyvaer** [comment]
@RubenVerborgh grep on `config` gives
```
config/templates/new-account/.meta
config/templates/new-account/.acl
config/templates/new-account/inbox/.acl
config/templates/new-account/private/.acl
config/templates/new-account/profile/.acl
config/templates/new-account/profile/card$.ttl
config/templates/new-account/robots.txt.acl
config/templates/new-account/settings/serverSide.ttl.acl
config/templates/new-account/settings/.acl
config/templates/new-account/settings/prefs.ttl
config/templates/new-account/settings/publicTypeIndex.ttl.acl
config/templates/new-account/.well-known/.acl
config/templates/new-account/public/.acl
config/templates/new-account/favicon.ico.acl
config/templates/new-account/.meta.acl
config/views/auth/no-permission.hbs
```
Grep on `data` gives
```
data/.meta
data/.acl
data/inbox/.acl
data/private/.acl
data/profile/.acl
data/robots.txt.acl
data/settings/serverSide.ttl.acl
data/settings/.acl
data/settings/publicTypeIndex.ttl.acl
data/.well-known/.acl
data/public/.acl
data/favicon.ico.acl
data/.meta.acl
```

@bourgeoa `https://ash.runi.ilabt.imec.be:8443` is not publicly available, because everything on port 443 (`https://ash.runi.ilabt.imec.be`) is proxied to `http://localhost:8443`

**Comment by RubenVerborgh** [comment]
So localhost occurs in all those places? We’d probably want to fix those
then.

-- 
This e-mail, and any attachments thereto, is intended only for use by the 
addressee(s) named herein and may contain legally privileged, confidential 
and/or proprietary information. If you are not the intended recipient of 
this e-mail (or the person responsible for delivering this document to the 
intended recipient), please do not disseminate, distribute, print or copy 
this e-mail, or any attachment thereto. If you have received this e-mail in 
error, please respond to the individual sending the message, and 
permanently delete the email.

**Comment by pheyvaer** [comment]
As in the code or on my local set up or both?

**Comment by RubenVerborgh** [comment]
Your local setup.

**Comment by pheyvaer** [comment]
I got it working. I removed the folders `config` and `data`.  Restarted NSS with the same config and this time the profile card contains the correct URL. I have done this before, so I don't know why it works this time. I checked with `grep` again and `localhost` is not longer found in files in `config` and `data`.
