### ISSUE TITLE
NSS doesn't respond for a while during test suite run

### ISSUE THREAD

**Issue by kjetilk** [solid/node-solid-server#1358]
NSS 5.2.2. seems to be unresponsive at random times for me while I'm running the test suite against it. I've seen this for a while, but it hasn't been much of a problem before now, where it stops with every run. It sits there for a while, times out with no data sent to the client, and then continues as if nothing happened. :-) 

The client says 
```
        # 500 Server closed connection without sending any data back
```

I test several HTTP methods, but I can't say I've seen anything that indicates it happens with any particular method, though perhaps more often with `PUT`.

I'm attaching [debug output](https://github.com/solid/node-solid-server/files/3851177/nss_log.txt), but it doesn't seem terribly useful, so ping me about reproducing.

**Comment by kjetilk** [comment]
I'm trying to figure out if there could be something wrong on the client end here, I can't be sure it isn't, and the funny thing is the server responds to other requests while it hangs on the request from the test suite. 

I ended up falling down to `tcpdump`, but I'm a bit out of my depth here:

```
01:31:08.464717 IP (tos 0x0, ttl 64, id 52272, offset 0, flags [DF], proto TCP (6), length 52)
    robin.kjernsmo.net.52338 > robin.kjernsmo.net.8446: Flags [.], cksum 0x6857 (incorrect -> 0x6d74), seq 598, ack 1891, win 1386, options [nop,nop,TS val 1970648433 ecr 1970648391], length 0
01:33:08.435061 IP (tos 0x0, ttl 64, id 5540, offset 0, flags [DF], proto TCP (6), length 52)
    robin.kjernsmo.net.8446 > robin.kjernsmo.net.52338: Flags [F.], cksum 0x6857 (incorrect -> 0x9cb0), seq 1891, ack 598, win 3
```

It seems the last traffic comes from the client, and then there is no response for two minutes, and then it responds with something. I'm guessing the very low `win` may be just a hangup, but not sure what it means, and what `incorrect` implies...

**Comment by mikeadams1** [comment]
I am also getting some strange responses via the data browser, look like this:

![image](https://user-images.githubusercontent.com/44804421/68991752-085d3500-0830-11ea-9b8a-9af5531b9da9.png)

**Comment by kjetilk** [comment]
That looks unrelated though, it seems that error comes from the JS running in the browser, not in the interaction between server and client.

**Comment by jaxoncreed** [comment]
@kjetilk Where do you have NSS deployed? Is this a remote deployment or one done locally in docker?

**Comment by kjetilk** [comment]
It is a local deployment, just right on the iron, no docker :-)

**Comment by kjetilk** [comment]
I have analyzed the situation with wireshark. It seems something is going wrong in the dialog, but I'm not so sure it is the server anymore. Unfortunately, I couldn't find a decent way to export a decent text file from wireshark, so here comes a screenshot.

In this, 178.22.8.4 is the client, 178.22.8.2 is the server. 

It begins with a normal request, the usual TCP traffic, then it adds TLS, then the client sends application data with a length of 991 bytes. I'm guessing that's the actual HTTP request with headers and stuff. The server goes `ACK` and then sends the 1250 bytes, which is probably the HTTP response, then another small response, lenth 90, and then the client goes `RST, ACK` in the red line. Looks good.

In the faulty request, what seems to differ is that the client goes `ACK` instead of sending what I interpreted as the HTTP request. Then, the server waits 2 minutes, before it goes `FIN, ACK`.

So, what could possibly make the client go `ACK`?

![Screenshot_20191119_160328](https://user-images.githubusercontent.com/154068/69158124-38356280-0ae6-11ea-990a-a21f9fadfa91.png)

**Comment by kjetilk** [comment]
I think I have found it: The problem occurs mainly with the Net::SSL perl module, which I used because it was easier to configure to ignore hostname verification, self-signed certs. The alternative, IO::Socket::SSL, requires more rigour from its users, but also does not exhibit this problem. 

So, I guess I just have to be more rigorous, then. :-)
