### ISSUE TITLE
creation of file without extension (foo/file) returns foo/file should be foo/file$.bin

### ISSUE THREAD

**Issue by bourgeoa** [solid/node-solid-server#1364]
The creation of file without extension and no contentType (`foo/bar`) returns `foo/bar` should be `foo/bar$.bin`.
This as been introduced since PR #1336 (mp3$.mp3)
A PR is on-the-go for the `foo/bar$bin solution`
@jaxoncreed @RubenVerborgh 
what is the good response  ?
- `foo/bar$.bin`
-  refuse to create
- create but with an other name : `foo/bar.bin`

Actually you can delete existing foo/bar (tested) even if they coexist with foo/bar$.ttl or foo/bar$.bin

In general foo/bar with contentType is created as `foo/bar$.ext` (ext from contentType) is that correct ? It as some importance because `foo/bar` can be the name of a folder `foo/bar/` 
(databrowser display both `bar` as folder with folder contents if `foo/bar/ has contents`, it is a bug)
`

**Comment by RubenVerborgh** [comment]
> The creation of file without extension and no contentType (`foo/bar`) returns `foo/bar` should be `foo/bar$.bin`.

Why?

**Comment by bourgeoa** [comment]
May be because no extension "" !== 'bin' 

But having some doubts I wondered about other solution but forgot that it might be correct.
If you confirm, then only the consequences need to be resolved. (Display on dataBrowser)

**Comment by RubenVerborgh** [comment]
I think the correct behavior here is to have no extension on disk. Should hopefully be independent of Databrowser.

**Comment by kjetilk** [comment]
We have resolved to require a content-type (https://github.com/solid/specification/issues/70), so this is a situation that should not occur, right?

I suppose NSS should already change its behaviour if this situation can occur.

**Comment by bourgeoa** [comment]
> We have resolved to require a content-type

I suppose it does not change anything for application/octet-stream which is the default for no extension and so will have no extension on disk

> Should hopefully be independent of Databrowser.

Yes just need to make an issue
