### ISSUE TITLE
Locking files when writing to avoid concurrency issues

### ISSUE THREAD

**Issue by nicola** [solid/node-solid-server#137]
The idea is to avoid two people writing at the same time

**Comment by nicola** [comment]
I have done some thinking and I think there is only a way to achieve this __and__ still being working async. In other words, reads are fine to be async as they are, but for writes, the server has to have a global state of what file is being written at the moment which has some sort of queuing (or even simpler nextTick) until the resource is free.

By bringing back sync, a possible attack could be loading a 10 GB file while two people are chatting (hence breaking their conversation)

**Comment by RubenVerborgh** [comment]
Not a problem right now, can reconsider in the future.

**Comment by RubenVerborgh** [comment]
Reopening, as the future is now.

**Comment by RubenVerborgh** [comment]
Fixed in https://github.com/solid/node-solid-server/pull/1116
