### ISSUE TITLE
public/.acl>; as application/octet-stream

### ISSUE THREAD

**Issue by scenaristeur** [solid/node-solid-server#1376]
Trying Pixolid, i’ve crashed my POD.
when accessing to
https://smag0.solid.community/public/ 3

now I’ve got
```
Error: Don't know how to parse application/octet-stream yet while trying to parse <https://smag0.solid.community/public/.acl>; as application/octet-stream
```
can’t access it my public folder anymore, even via the browser, solid-file-manager, or Pod-explorer.
Any idea ??

more here : 

https://forum.solidproject.org/t/is-my-pod-dead/2513/18

Related to that one https://forum.solidproject.org/t/cannot-create-acl-file-because-of-content-type/1955 ?
thxs

**Comment by scenaristeur** [comment]
Is this related to https://github.com/solid/node-solid-server/pull/1258 ?

**Comment by jaxoncreed** [comment]
It might be related to that but I am not sure. If you'd like to experiment around with another pod, feel free to create a new one. In the mean time, I'll see if I can get that PR merged and we'll see if that fixes it.

**Comment by scenaristeur** [comment]
I've created another one, but I've got some data on this one that I need to get back, so I need to restore my root .acl & my /public .acl

**Comment by bourgeoa** [comment]
@jaxoncreed can you do that as an exception or make a zip of @scenaristeur data/smag0.solid.community/ folder (may be more error prone).
If allowed by @scenaristeur I am ready to help restore the zip on my server (bourgeoa.ga) and copy the data to @scenaristeur pod using solid-file-client which can recursive copy including acl and meta

**Comment by scenaristeur** [comment]
I think the owner of a pod could have the possibility to restore it's default acl. Don't you?

**Comment by bourgeoa** [comment]
There has been discussion about this : 
- there is no pod owner concept, if there would be one
- some data may be protected from pod owner write/control

At the moment the only solution can be through the pod provider.
May be we could ask to know who has control and if none to default to Pod's webId.

**Comment by jaxoncreed** [comment]
Right there have been discussions about "restore my pod." But it would be on an implementation level, not a spec level. At the moment node-solid-server does not have a feature to help users restore their pod after corruption.

**Comment by scenaristeur** [comment]
I think there must be a way to restore, because when the user try an app, he doesn't know what the app can do, and the app can corrupt the pod & all data, & block access to the 'owner' as I think there is a owner ( the one that create, that is owner in the share tool).
That owner must be able to restore the state of his Pod. 
for the moment, can an admin restore my root & my public .acl. ?

**Comment by scenaristeur** [comment]
please unblock my POD !

**Comment by akuckartz** [comment]
https://solid.community states:
> there are no security or stability guarantees

**Comment by scenaristeur** [comment]
> https://solid.community states:
> 
> > there are no security or stability guarantees

I know but do you think it is normal that an app can take contral or break your POD, and you can't restore it ? 
This way I don't want to use any Solid App, and nobody will use mine...

**Comment by alexcorvis84** [comment]
> > https://solid.community states:
> > > there are no security or stability guarantees
> 
> I know but do you think it is normal that an app can take contral or break your POD, and you can't restore it ?
> This way I don't want to use any Solid App, and nobody will use mine...
> 
> **Is there an solid.community server admin that could restore my root .acl & /public .acl ? PLEASE !!!**

I've just opened an Issue into the support solid.community GitLab repo. As you can checked, I've referenced this post as issue is quite similar to yours (mine at least just affected to some containers and not my root).

Hope it will serve to get some help and could find a fix ;)

**Comment by scenaristeur** [comment]
@alexcorvis84 thxs, I didn't know the existence of the gitlab. And I'm waiting since December for an admin answer

**Comment by melvincarvalho** [comment]
@alexcorvis84 hi!

@jaxoncreed is one of our admins right now, but it looks like he's been unable to resolve your issue, so far

I started solid.community and this issue was brought to my attention that people were having issues with .acls and they were not being resolved, leading to some frustration.  For that reason I started a place where solid.community specific issues, a couple of days ago

https://gitlab.com/solid.community/support/

We seem to have a related issue here:

https://gitlab.com/solid.community/support/issues/2

So if you tag on a request there, we can try and work out what's going on.

Disclaimer:  I'd like to manage some expectations here.  I've not and have never been paid to work on solid, all our work comes on a volunteer basis.  We are looking for more contributors, and that will enable us to help out more people

**Comment by melvincarvalho** [comment]
@scenaristeur so I am applying some guesswork here but I have restored your /public/ `.acl` file to the default.  Could you let me know if that has had the desired effect?

**Comment by scenaristeur** [comment]
yes I can get now my /public. there was other problems with my /root, but it's quite finished https://gitlab.com/solid.community/support/issues/2#note_292679518
for me we can close the issue, but we must maintain a list of working/corrupting apps to disallow this kind of matter
