### ISSUE TITLE
ENOENT: no such file or directory, stat 'xxx/node_modules/solid-server/node_modules/mashlib/dist/index.html'

### ISSUE THREAD

**Issue by linonetwo** [solid/node-solid-server#1382]
I'm trying to start a local test server. After login, and goto https://localhost:8443/profile/card#me , it shows `ENOENT: no such file or directory, stat 'xxx/node_modules/solid-server/node_modules/mashlib/dist/index.html'`.

And there is no `xxx/node_modules/solid-server/node_modules` in `xxx/node_modules/solid-server`

I'm using NSS 5.2.2

Maybe this line should use `require` instead of a hardcoded path?

https://github.com/solid/node-solid-server/blob/6432c4ed9c41a930c6f0b8b550034b96beb6fd32/lib/handlers/get.js#L92

**Comment by linonetwo** [comment]
This can be easily solved by adding `--data-browser-path $(pwd)/../node_modules/mashlib/dist/databrowser.html`

**Comment by jaxoncreed** [comment]
Good temporary fix. The hard-coded value for the default data browser seems to be wrong.
