### ISSUE TITLE
" You are currently logged in as" while not login, in localhost

### ISSUE THREAD

**Issue by linonetwo** [solid/node-solid-server#1383]
NSS 5.2.2

> You are currently logged in as , but do not have permission to access https://zhihucrawler.localhost:8443/. 

<img width="969" alt="截屏2020-01-02下午12 32 38" src="https://user-images.githubusercontent.com/3746270/71651895-158c9f80-2d5c-11ea-9638-7d54557c4a51.png">

Local CA is added using `mkcert localhost`

Local server is started using `solid start --port 8443 --ssl-key ../keys/localhost-key.pem --ssl-cert ../keys/localhost.pem --webid --multiuser --data-browser-path $(pwd)/../node_modules/mashlib/dist/databrowser.html`

And `127.0.0.1    zhihucrawler.localhost` is added to hosts.

Reproduce: https://github.com/linonetwo/zhihu-nlp-playground/tree/config-solid

**Comment by linonetwo** [comment]
And If I start server using 

`--force-user https://zhihucrawler.localhost:8443` or `--force-user https://zhihucrawler.localhost`

It will be:

<img width="1194" alt="截屏2020-01-02下午1 52 33" src="https://user-images.githubusercontent.com/3746270/71653408-2262c080-2d67-11ea-957c-c3bea0bcb63e.png">

**Comment by linonetwo** [comment]
After enable debug logging using `DEBUG=solid:* solid start`

I found:

```shell
dataBrowserPath "/Users/linonetwo/Desktop/repo/zhihu-nlp-playground/solid/../node_modules/mashlib/dist/databrowser.html"
  solid:server Error page because of: ForbiddenError: Forbidden
    at SendStream.error (/Users/linonetwo/repo/zhihu-nlp-playground/node_modules/send/index.js:270:31)
    at SendStream.pipe (/Users/linonetwo/repo/zhihu-nlp-playground/node_modules/send/index.js:553:12)
    at sendfile (/Users/linonetwo/repo/zhihu-nlp-playground/node_modules/express/lib/response.js:1103:8)
    at ServerResponse.sendFile (/Users/linonetwo/repo/zhihu-nlp-playground/node_modules/express/lib/response.js:433:3)
    at handler (/Users/linonetwo/repo/zhihu-nlp-playground/node_modules/solid-server/lib/handlers/get.js:96:11) {
  message: 'Forbidden',
  expose: false
}
```

in

https://github.com/solid/node-solid-server/blob/dcc5f9074669bb5c0a936ac3450aba18b16fd13a/lib/handlers/get.js#L96

where `dataBrowserPath === "/xxxrepopath/solid/../node_modules/mashlib/dist/databrowser.html"`

**Comment by linonetwo** [comment]
But problem is still there, there is :

```shell
[HTTPError: Resource not found: /mash.css] {
  name: 'HTTPError',
  message: 'Resource not found: /mash.css',
  status: 404
}
```

because `/node_modules/mashlib/dist/index.html` is requesting `/mash.css`, and there is no such file served by nss.

**Comment by jaxoncreed** [comment]
So does this look more like a data browser issue to you at this point?
