### ISSUE TITLE
req.session.userId is undefined in allow.js

### ISSUE THREAD

**Issue by linonetwo** [solid/node-solid-server#1386]
As https://github.com/jeff-zucker/solid-auth-cli/issues/6

https://github.com/solid/node-solid-server/blob/dcc5f9074669bb5c0a936ac3450aba18b16fd13a/lib/handlers/allow.js#L51-L52

`req.session.userId` is `undefined` in this line.

And the debug log is as follow, notice in first line show that NSS get the correct webID of current fetch, but in the last line, it gets `undefined` in `req.session.userId`:

```shell
solid:authentication User is already authenticated as https://zhihucrawler.localhost:8443/profile/card#me +41ms
  solid:ACL Using ACL https://zhihucrawler.localhost:8443/public/.acl for ./zhihu/aa.txt +46ms
  solid:ACL    2  default authentications about <https://zhihucrawler.localhost:8443/public/> in <https://zhihucrawler.localhost:8443/public/.acl> +1ms
  solid:ACL accessDenied: checking access to <https://zhihucrawler.localhost:8443/public/zhihu/aa.txt> by null and origin null +9ms
  solid:ACL    2  default authentications about <https://zhihucrawler.localhost:8443/public/> in <https://zhihucrawler.localhost:8443/public/.acl> +0ms
  solid:ACL    Checking auth <https://zhihucrawler.localhost:8443/public/.acl#owner> with agent null +0ms
  solid:ACL     Agent or group: Fail: not public and not logged on. +0ms
  solid:ACL      The agent/group check fails +0ms
  solid:ACL       Check failed: User Unauthorized +0ms
  solid:ACL     Agent or group: Ok, its public. +1ms
  solid:ACL       Mode allowed: <http://www.w3.org/ns/auth/acl#Read> +0ms
  solid:ACL accessDenied: modeURIorReasons: ["User Unauthorized","http://www.w3.org/ns/auth/acl#Read"] +0ms
  solid:ACL  checking <http://www.w3.org/ns/auth/acl#Write> +0ms
  solid:ACL   MODE REQUIRED NOT ALLOWED: <http://www.w3.org/ns/auth/acl#Write> Denying with User Unauthorized +0ms
  solid:ACL Write access denied to (none): undefined - Forbidden +0ms
```

I can try to debug this, but I need help

1. to figure out where `solid:authentication` logger is located in, since I can't search out any log text with `'User is already authenticated as` in `solid-server` package.
2. where is this `req` passed from?

**Comment by linonetwo** [comment]
`allow.js` is used in 

https://github.com/solid/node-solid-server/blob/dcc5f9074669bb5c0a936ac3450aba18b16fd13a/lib/ldp-middleware.js#L28

and `ldp-middleware.js` is used in 

https://github.com/solid/node-solid-server/blob/dcc5f9074669bb5c0a936ac3450aba18b16fd13a/lib/create-app.js#L117


But I still don't know why `req` have `req.session.userId === undefined`

**Comment by jaxoncreed** [comment]
The debug statement you're looking for is in another library: https://github.com/solid/oidc-auth-manager/blob/a8f8945e826a04ed8b16c8458667f60dea0723fd/src/host-api.js#L32

Similarly the `session.userId` is set in the same package here: https://github.com/solid/oidc-auth-manager/blob/80860f88c5b160e9b9290455b066063ba40acd9e/src/handlers/auth-callback-request.js#L121

**Comment by linonetwo** [comment]
`@solid/oidc-auth-manager` is not longer a dependency of latest `solid-server`, the only similar dep is `oidc-op-express`.

**Comment by linonetwo** [comment]
I can't console.log in that package in node_modules, don't know why...

And I get `Token does not pass the audience allow filter` right after above errors.

```
solid:ACL Write access denied to (none): undefined - Forbidden +0ms
solid:server Error page because of: ForbiddenError: Forbidden
    at AuthenticatedRequest.forbidden (/Users/linonetwo/repo/zhihu-nlp-playground/node_modules/@solid/oidc-rs/src/AuthenticatedRequest.js:781:17)
    at AuthenticatedRequest.allowAudience (/Users/linonetwo/repo/zhihu-nlp-playground/node_modules/@solid/oidc-rs/src/AuthenticatedRequest.js:367:24)
    at allow (/Users/linonetwo/repo/zhihu-nlp-playground/node_modules/@solid/oidc-rs/src/AuthenticatedRequest.js:335:13) {
  handled: true,
  statusCode: 403,
  realm: 'https://localhost:8443',
  error: 'access_denied',
  error_description: 'Token does not pass the audience allow filter',
  error_uri: undefined
}
```

I tried `console.log(aud)` in

**Comment by linonetwo** [comment]
> solid:ACL accessDenied: checking access to <https://zhihucrawler.localhost:8443/public/zhihu/aa.txt> by null and origin null +8ms

@jaxoncreed do you know where does this happen? The place of `solid:ACL` logger.

**Comment by linonetwo** [comment]
https://github.com/solid/node-solid-server/blob/dcc5f9074669bb5c0a936ac3450aba18b16fd13a/lib/acl-checker.js#L21

`options.agentOrigin` is null here, make `agentOrigin` passing to `aclCheck.getTrustedModesForOrigin` also null.

https://github.com/solid/node-solid-server/blob/dcc5f9074669bb5c0a936ac3450aba18b16fd13a/lib/acl-checker.js#L72


Resulted in `solid:ACL accessDenied: checking access to <https://zhihucrawler.localhost:8443/public/zhihu/aa.txt> by null and origin null +9ms`

**Comment by linonetwo** [comment]
@jaxoncreed Seems solid/oidc-auth-manager:src/handlers/auth-callback-request.js@80860f8#L121
is not executed, I tried log and throw error from here and there is no echo.

Do you know any other place where `req.session.userId` is setted?

**Comment by linonetwo** [comment]
https://github.com/solid/node-solid-server/blob/dcc5f9074669bb5c0a936ac3450aba18b16fd13a/lib/create-app.js#L202-L211

Seems it is actually getting `userId` from here. And if I access resource form the browser, I can log correct `req.session.userId` here.

But if using `solid-cli`, `req.session.userId` will be null.

Is `req.session.userId` comes from the cookie sending from the client, and parsed by `express-session`?

**Comment by linonetwo** [comment]
Where does this cookie comes from? How to get a cookie with `solid-cli` and `solid-auth-cli`?

https://github.com/jeff-zucker/solid-auth-cli/issues/7

**Comment by linonetwo** [comment]
Close because using https://github.com/jeff-zucker/solid-auth-cli/issues/7#issuecomment-573027685 fixes it, it is my fault, fetch in the wrong way.
