### ISSUE TITLE
The Depency Contextify does not work well with Node 5 / Ubuntu 14.04

### ISSUE THREAD

**Issue by bshambaugh** [solid/node-solid-server#139]
I have been trying to install ldnode on Ubuntu 14.04. Unfortunately, I ended up deleting GNU core-utils, so my plan is to start over with Ubuntu 15.04 and compile npm and node from source. The trouble seems to stem from the modules contextify and node-gyp. I e-mailed the some output that I encountered to deiu since I was unable to attach it here.

Some links I found useful:

https://github.com/brianmcd/contextify/issues/171

https://github.com/atom/atom/issues/1981#issuecomment-42395882

https://github.com/nodejs/node-gyp/issues/426

**Comment by nicola** [comment]
Hi, thanks for this, I will have a look this week.
Github has introduced attachments here, feel free to update us

**Comment by bshambaugh** [comment]
I started over with Ubuntu 15.04 and installed node from http://github.com/nodejs/node to get v5.0.0-pre. I got a warning wanting a pre version and  some error messages. I tried 'sudo n stable' at the bash prompt to get v4.0.0 . I then tried npm install -g contextify to get:

 $ sudo npm install -g contextify
/
> contextify@0.1.14 install /usr/local/lib/node_modules/contextify
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/home/brent/.node-gyp/4.0.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/contextify/.node-gyp"
make: Entering directory '/usr/local/lib/node_modules/contextify/build'
  CXX(target) Release/obj.target/contextify/src/contextify.o
In file included from ../src/contextify.cc:3:0:
../node_modules/nan/nan.h:261:25: error: redefinition of ‘template<class T> v8::Local<T> _NanEnsureLocal(v8::Local<T>)’
 NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                         ^
../node_modules/nan/nan.h:256:25: note: ‘template<class T> v8::Local<T> _NanEnsureLocal(v8::Handle<T>)’ previously declared here
 NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Handle<T> val) {
                         ^
../node_modules/nan/nan.h:661:13: error: ‘node::smalloc’ has not been declared
     , node::smalloc::FreeCallback callback
             ^
../node_modules/nan/nan.h:661:35: error: expected ‘,’ or ‘...’ before ‘callback’
     , node::smalloc::FreeCallback callback
                                   ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(char*, size_t, int)’:
../node_modules/nan/nan.h:665:50: error: ‘callback’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                  ^
../node_modules/nan/nan.h:665:60: error: ‘hint’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                            ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(const char*, uint32_t)’:
../node_modules/nan/nan.h:672:67: error: call of overloaded ‘New(v8::Isolate*, const char*&, uint32_t&)’ is ambiguous
     return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
                                                                   ^
../node_modules/nan/nan.h:672:67: note: candidates are:
In file included from ../node_modules/nan/nan.h:25:0,
                 from ../src/contextify.cc:3:
/usr/local/lib/node_modules/contextify/.node-gyp/4.0.0/include/node/node_buffer.h:31:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/usr/local/lib/node_modules/contextify/.node-gyp/4.0.0/include/node/node_buffer.h:31:40: note:   no known conversion for argument 3 from ‘uint32_t {aka unsigned int}’ to ‘node::encoding’
/usr/local/lib/node_modules/contextify/.node-gyp/4.0.0/include/node/node_buffer.h:43:40: note: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/usr/local/lib/node_modules/contextify/.node-gyp/4.0.0/include/node/node_buffer.h:43:40: note:   no known conversion for argument 2 from ‘const char*’ to ‘char*’
In file included from ../src/contextify.cc:3:0:
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(uint32_t)’:
../node_modules/nan/nan.h:676:61: error: could not convert ‘node::Buffer::New(v8::Isolate::GetCurrent(), ((size_t)size))’ from ‘v8::MaybeLocal<v8::Object>’ to ‘v8::Local<v8::Object>’
     return node::Buffer::New(v8::Isolate::GetCurrent(), size);
                                                             ^
../node_modules/nan/nan.h: In function ‘v8::Local<v8::Object> NanBufferUse(char*, uint32_t)’:
../node_modules/nan/nan.h:683:12: error: ‘Use’ is not a member of ‘node::Buffer’
     return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
            ^
contextify.target.mk:90: recipe for target 'Release/obj.target/contextify/src/contextify.o' failed
make: *** [Release/obj.target/contextify/src/contextify.o] Error 1
make: Leaving directory '/usr/local/lib/node_modules/contextify/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.19.0-15-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/contextify
gyp ERR! node -v v4.0.0
gyp ERR! node-gyp -v v3.0.1
gyp ERR! not ok 
npm ERR! Linux 3.19.0-15-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "contextify"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! code ELIFECYCLE

npm ERR! contextify@0.1.14 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the contextify@0.1.14 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the contextify package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls contextify
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/brent/npm-debug.log

**Comment by bshambaugh** [comment]
There were no warnings or errors with Ubuntu 12.04.4 LTS:

$ sudo npm install -g contextify
npm http GET https://registry.npmjs.org/contextify
npm http 304 https://registry.npmjs.org/contextify
npm http GET https://registry.npmjs.org/bindings
npm http GET https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/bindings
npm http 304 https://registry.npmjs.org/nan

> contextify@0.1.14 install /usr/local/lib/node_modules/contextify
> node-gyp rebuild

make: Entering directory `/usr/local/lib/node_modules/contextify/build'
  CXX(target) Release/obj.target/contextify/src/contextify.o
  SOLINK_MODULE(target) Release/obj.target/contextify.node
  SOLINK_MODULE(target) Release/obj.target/contextify.node: Finished
  COPY Release/contextify.node
make: Leaving directory `/usr/local/lib/node_modules/contextify/build'
contextify@0.1.14 /usr/local/lib/node_modules/contextify
├── bindings@1.2.1
└── nan@1.8.4

**Comment by bshambaugh** [comment]
But it fails at cors:
$ sudo npm install -g ldnode

npm http 304 https://registry.npmjs.org/cors
npm ERR! Error: No compatible version found: cors@'^2.7.1'
npm ERR! Valid install targets:
npm ERR! ["0.0.1","0.0.2","0.0.3","0.0.4","0.0.5","0.1.0","0.1.1","1.0.0","1.0.1","2.0.0","2.1.0","2.1.1","2.2.0","2.3.0","2.3.1","2.3.2","2.4.0","2.4.1","2.4.2","2.5.0","2.5.1","2.5.2","2.5.3","2.6.0","2.6.1","2.7.0","2.7.1"]
npm ERR!     at installTargetsError (/usr/local/lib/node_modules/npm/lib/cache.js:685:10)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache.js:607:10
npm ERR!     at saved (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:138:7)
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 2.6.32-43-generic
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "ldnode"
npm ERR! cwd /home/brent
npm ERR! node -v v0.10.4
npm ERR! npm -v 1.2.18

**Comment by bshambaugh** [comment]
Yet cors installation succeeds on Ubuntu 15.04

$ npm install cors
cors@2.7.1 node_modules/cors
└── vary@1.1.0

**Comment by bshambaugh** [comment]
The closest thus far on Ubuntu 15.04
$ git clone https://github.com/nodejs/node
(do the setting up .... then move to another version using the lines below)
$ sudo npm install -g n
$ n ls
$ sudo n 0.12.7
$ sudo npm install -g ldnode
 
> ws@0.4.32 install /usr/local/lib/node_modules/ldnode/node_modules/express-ws/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory '/usr/local/lib/node_modules/ldnode/node_modules/express-ws/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  COPY Release/bufferutil.node
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  COPY Release/validation.node
make: Leaving directory '/usr/local/lib/node_modules/ldnode/node_modules/express-ws/node_modules/ws/build'

> contextify@0.1.14 install /usr/local/lib/node_modules/ldnode/node_modules/jsonld/node_modules/jsdom/node_modules/contextify
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/home/brent/.node-gyp/0.12.7"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/ldnode/node_modules/jsonld/node_modules/jsdom/node_modules/contextify/.node-gyp"
make: Entering directory '/usr/local/lib/node_modules/ldnode/node_modules/jsonld/node_modules/jsdom/node_modules/contextify/build'
  CXX(target) Release/obj.target/contextify/src/contextify.o
  SOLINK_MODULE(target) Release/obj.target/contextify.node
  COPY Release/contextify.node
make: Leaving directory '/usr/local/lib/node_modules/ldnode/node_modules/jsonld/node_modules/jsdom/node_modules/contextify/build'

> kerberos@0.0.14 install /usr/local/lib/node_modules/ldnode/node_modules/acl/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos
> (node-gyp rebuild) || (exit 0)

gyp WARN EACCES user "root" does not have permission to access the dev dir "/home/brent/.node-gyp/0.12.7"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/ldnode/node_modules/acl/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos/.node-gyp"
make: Entering directory '/usr/local/lib/node_modules/ldnode/node_modules/acl/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos/build'
  CXX(target) Release/obj.target/kerberos/lib/kerberos.o
In file included from ../lib/kerberos.cc:1:0:
../lib/kerberos.h:5:27: fatal error: gssapi/gssapi.h: No such file or directory
 #include <gssapi/gssapi.h>
                           ^
compilation terminated.
kerberos.target.mk:92: recipe for target 'Release/obj.target/kerberos/lib/kerberos.o' failed
make: *** [Release/obj.target/kerberos/lib/kerberos.o] Error 1
make: Leaving directory '/usr/local/lib/node_modules/ldnode/node_modules/acl/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 3.19.0-30-generic
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/ldnode/node_modules/acl/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 
/usr/local/bin/ldnode -> /usr/local/lib/node_modules/ldnode/bin/ldnode.js
ldnode@0.2.11 /usr/local/lib/node_modules/ldnode
├── node-regexp@0.1.1
├── li@1.0.1
├── webid@0.2.4
├── async@1.4.2
├── negotiator@0.5.3
├── http-delayed-response@0.0.4
├── mime@1.3.4
├── node-uuid@1.4.3
├── redis@0.12.1
├── string@3.3.1
├── cors@2.7.1 (vary@1.1.0)
├── debug@2.2.0 (ms@0.7.1)
├── response-time@2.3.1 (on-headers@1.0.1, depd@1.0.1)
├── n3@0.4.5
├── express-session@1.11.3 (utils-merge@1.0.0, cookie-signature@1.0.6, cookie@0.1.3, on-headers@1.0.1, parseurl@1.3.0, depd@1.0.1, crc@3.3.0, uid-safe@2.0.0)
├── fs-extra@0.21.0 (jsonfile@2.2.2, rimraf@2.4.3, graceful-fs@4.1.2)
├── nomnom@1.8.1 (underscore@1.6.0, chalk@0.4.0)
├── raw-body@2.1.4 (bytes@2.1.0, unpipe@1.0.0, iconv-lite@0.4.12)
├── express@4.13.3 (escape-html@1.0.2, merge-descriptors@1.0.0, array-flatten@1.1.1, cookie@0.1.3, utils-merge@1.0.0, cookie-signature@1.0.6, methods@1.1.1, fresh@0.3.0, range-parser@1.0.2, vary@1.0.1, path-to-regexp@0.1.7, content-type@1.0.1, etag@1.7.0, parseurl@1.3.0, content-disposition@0.5.0, serve-static@1.10.0, depd@1.0.1, qs@4.0.0, finalhandler@0.4.0, on-finished@2.3.0, proxy-addr@1.0.8, accepts@1.2.13, type-is@1.6.9, send@0.13.0)
├── glob@5.0.15 (path-is-absolute@1.0.0, inherits@2.0.1, inflight@1.0.4, once@1.3.2, minimatch@3.0.0)
├── request@2.64.0 (aws-sign2@0.5.0, stringstream@0.0.4, forever-agent@0.6.1, caseless@0.11.0, oauth-sign@0.8.0, tunnel-agent@0.4.1, form-data@1.0.0-rc3, isstream@0.1.2, json-stringify-safe@5.0.1, extend@3.0.0, qs@5.1.0, tough-cookie@2.1.0, combined-stream@1.0.5, mime-types@2.1.7, http-signature@0.11.0, bl@1.0.0, hawk@3.1.0, har-validator@1.8.0)
├── rdflib@0.2.8 (xmlhttprequest@1.7.0, async@0.9.2, coffee-script@1.10.0, jsdom@6.5.1, browserify@11.2.0)
├── express-ws@0.2.6 (url-join@0.0.1, ws@0.4.32)
├── jsonld@0.3.26 (xmldom@0.1.19, pkginfo@0.3.0, es6-promise@2.0.1, commander@2.8.1, jsdom@3.1.2)
└── acl@0.4.9 (bluebird@2.10.2, lodash@3.10.1, mongodb@2.0.45)

**Comment by sebilasse** [comment]
@bshambaugh Could you please review if it is the same issue as with?
If so: contextify 171 and 188 is a dup ...

**Comment by bshambaugh** [comment]
@sebilasse I did reference brianmcd/contextify#171 at the beginning of this issue

**Comment by bshambaugh** [comment]
for reference, I believe the n --help command explains things:
$ n --help

  Usage: n [options/env] [COMMAND] [args]

  Environments:
    n [COMMAND] [args]            Uses default env (node)
    n io [COMMAND]                Sets env as io

  Commands:

    n                              Output versions installed
    n latest                       Install or activate the latest node release
    n -a x86 latest                As above but force 32 bit architecture
    n stable                       Install or activate the latest stable node release
    n <version>                    Install node <version>
    n use <version> [args ...]     Execute node <version> with [args ...]
    n bin <version>                Output bin path for <version>
    n rm <version ...>             Remove the given version(s)
    n --latest                     Output the latest node version available
    n --stable                     Output the latest stable node version available
    n ls                           Output the versions of node available

  (iojs):
    n io latest                    Install or activate the latest iojs release
    n io -a x86 latest             As above but force 32 bit architecture
    n io <version>                 Install iojs <version>
    n io use <version> [args ...]  Execute iojs <version> with [args ...]
    n io bin <version>             Output bin path for <version>
    n io rm <version ...>          Remove the given version(s)
    n io --latest                  Output the latest iojs version available
    n io ls                        Output the versions of iojs available

  Options:

    -V, --version   Output current version of n
    -h, --help      Display help information
    -q, --quiet     Disable curl output (if available)
    -d, --download  Download only
    -a, --arch      Override system architecture

  Aliases:

    which   bin
    use     as
    list    ls
    -       rm

**Comment by sebilasse** [comment]
@bshambaugh I see. Got it working by setting up a complete different development environment (another hardware ;) with node 0.12.7. Thankyou.
Unfortunately downgrading is not an option for where I currently develop my decentralized cms, so let's hope that the author of contextify will get it to work with current node versions ...

**Comment by deiu** [comment]
Closing this issue, following an upstream fix for contextify https://github.com/brianmcd/contextify/issues/188

**Comment by dmitrizagidulin** [comment]
Reopening. This is still an issue -- can't install `ldnode` on Ubuntu on Node 5. 
Need to:

1. Remove or fix `jsonld` dependency (since `contextify` is a dep of that). (Remove because its usage is commented out in `lib/parse.js`.)
2. Fix `rdflib.js` upstream to use a later version of `jsonld`.

**Comment by nicola** [comment]
this is fixed in latest
