### ISSUE TITLE
Cannot read property 'updateTimeout' of undefined

### ISSUE THREAD

**Issue by linonetwo** [solid/node-solid-server#1394]
https://github.com/solid/node-solid-server/blob/4cac16857aef2565dab8a85c36b2aadf5293d0c2/package.json#L95

I got following error, when I close an electron app window, and click the tray icon to restart that app.

```
Uncaught Exception:
TypeError: Cannot read property 'updateTimeout' of undefined
    at updateLock (/xxx/SoLiDBox.app/Contents/Resources/app.asar/node_modules/proper-lockfile/lib/lockfile.js:90:14)
    at /xxx/SoLiDBox.app/Contents/Resources/app.asar/node_modules/proper-lockfile/lib/lockfile.js:136:13
    at FSReqCallback.oncomplete (fs.js:153:23)
```

Have `proper-lockfile` upgrade to 4.1.1 , which is the latest version, will fixes this bug.

**Comment by jaxoncreed** [comment]
Merged into version 5.2.3
