### ISSUE TITLE
Cannot build NSS from master

### ISSUE THREAD

**Issue by bourgeoa** [solid/node-solid-server#1406]
I'm building from a master fork, a docker NSS using Dockerfile.

```
> solid-server@5.2.3 solid /usr/src/app
> node ./bin/solid "start"

/usr/src/app/node_modules/@solid/cli/node_modules/@solid/oidc-rp/lib/IDTokenSchema.js:14
var IDTokenSchema = JWTSchema.extend({
                              ^

TypeError: Cannot read property 'extend' of undefined
    at Object.<anonymous> (/usr/src/app/node_modules/@solid/cli/node_modules/@solid/oidc-rp/lib/IDTokenSchema.js:14:31)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/src/app/node_modules/@solid/cli/node_modules/@solid/oidc-rp/lib/IDToken.js:17:21)
    at Module._compile (module.js:652:30)

```
The error goes back along NSS 5.2.3 => solid-auth-client 2.4.1 => @solid/oidc-rp 0.10 => @solid/jose 0.5

see issue https://github.com/solid/jose/issues/8

It has been tagged as a `regression`. Good.

I tried to downgrade the `solid-auth-client` version from `^2.3.1 ` to `2.3.1` It had no impact.

It seems that the npm chain always go to the latest version.
Is it by purpose to have latest npm app versions in the chain, is there no way to keep a buildable NSS version ?
I'm in the feeling that with the actual way of using the `^` character it is not possible to rebuild old NSS versions.

**Comment by dmitrizagidulin** [comment]
The issue is in the https://github.com/solid/solid-cli/ repo. It needs to publish a new npm version that includes Ruben's fix, https://github.com/solid/solid-cli/commit/8aaf55e76c2ee4712c47230726f66577fc4b0535.

Then you need to update `solid-auth-cli`, then update `rdflib`, and finally update NSS to use that rdflib.

**Comment by RubenVerborgh** [comment]
`@solid/cli` v.0.1.3 with the fix was released on 2020/2/26. We just need a package-lock update.

**Comment by bourgeoa** [comment]
Thanks. It works : 
I do not understand why.
When I build from a master fork a dockerNSS. I run npm install. Should I delete package-lock before ?

**Comment by RubenVerborgh** [comment]
> When I build from a master fork a dockerNSS. I run npm install. Should I delete package-lock before ?

package-lock.json was asking for a broken version of `@solid/cli`, not anymore now. Deleting is not necessary.
