### ISSUE TITLE
Link "rel=acl" HTTP header points to non existing ACL resource location

### ISSUE THREAD

**Issue by fourcube** [solid/node-solid-server#1429]
When performing a GET or HEAD request on an existing resource (`path/resource`), NSS always returns (`path/resource.acl`) in the Link header ([src](https://github.com/solid/node-solid-server/blob/master/lib/header.js#L77)).

## Example

```
GET 
https://foo.solid.community/public/example.html
...

Link: <example.html.acl>; rel="acl", <example.html.meta>; rel="describedBy", <http://www.w3.org/ns/ldp#Resource>; rel="type"
```

## Expected behavior

From the [spec](https://github.com/solid/web-access-control-spec#acl-resource-location-discovery) I assumed that the returned `acl` relation would allow a client to discover the corresponding ACL resource of the requested resource (which is located under `../.acl` in this example).

### Edit:

From looking through some other issues, it looks like this relation does not imply that the ACL file actually exists. If this is a correct assumption, please feel free to close this issue.

**Comment by csarven** [comment]
Thanks for raising this. Your Edit is correct.

The ACL resource is named (and linked to) but it may not necessarily have a representation ie. server may return a 404. Note step 1 of the ACL inheritance algorithm: https://github.com/solid/web-access-control-spec#acl-inheritance-algorithm . The same algorithm is also defined for clients: https://github.com/solid/specification/issues/106
