### ISSUE TITLE
Auxillary resources should only be created with PUT

### ISSUE THREAD

**Issue by bourgeoa** [solid/node-solid-server#1442]
@michielbdejong @RubenVerborgh @csarven.

This is a follow up of PR #1422 where the consensus seemed to agree that acl resources should not be created with POST+slug.
**You MUST know for sure the resource name that is created.**

So you must either : 
1. forbid POST+slug and only allow PUT with an error (error code ?)
2. force POST+slug to PUT equivalent at the filesystem level and no error 

Both can be done with NSS and I don'know what is the prefered specification way.
I was with the general idea that .meta and .acl where resources and as such could be created with POST+slug.

This should be the case for all auxilliary resources (actually acl and meta).

**Comment by michielbdejong** [comment]
Hi Alain!
You say
> the consensus seemed to agree that acl resources should not be created with POST+slug.

but
> I was with the general idea that .meta and .acl where resources and as such could be created with POST+slug.

so you mean that you don't agree with the consensus?

**Comment by bourgeoa** [comment]
I am not saying that, I think that the consensus is on the result (the URL must be guaranteed). The way to achieve it may/may not depend on other considerations/principles.

I am not an expert and am asking experts for guidance.
