### ISSUE TITLE
Percent-encoded characters causes issues with access control

### ISSUE THREAD

**Issue by FlorSanders** [solid/node-solid-server#1474]
Creating an ACL file for a resource which name contains percent-encoded characters seems to cause issues with access control.

More specifically, I have a file with name `urn:dev:mac:807d3afffe367a58_humidity.ttl` saved on the Pod using rdflib.
The `:` get percent-encoded upon saving to get the following result `urn%3Adev%3Amac%3A807d3afffe367a58_humidity.ttl`.
As long as the file doesn't have its own ACL file (relying on the ACL of its folder), all access control seems to be working fine.
Though at the moment one creates an ACL file for this resource (e.g. by adding read access for another webId), permission is lost to send patch requests for the file in question.

This issue was discussed on the [Solid forum](https://forum.solidproject.org/t/error-403-for-patch-after-creating-document-acl/3426/4), where more details as well as the actual ACL files for the resources can be found.

**Comment by Vinnl** [comment]
Possibly related: https://github.com/solid/node-solid-server/issues/1324

**Comment by bourgeoa** [comment]
Your problem is that the url `must be` %-encoded and yours are not.
- pathname.split(’/’).map((component) => encodeURIComponent(component)).join(’/’)
- decodeURIComponent(pathname)

see https://tools.ietf.org/html/rfc3986

NSS 
- resources are URI (so they are %-encoded)
- mashlib displays the resource name as a decoded string
- stores the files in the filesystem as decoded strings

**Comment by FlorSanders** [comment]
I see, have you confirmed this is the problem? Otherwise I don't mind inspecting some of the HTML-packets using wireshark to make sure.
Also, if this is the case, wouldn't it be an idea to add a check on the input in rdflib.js, or even make sure the arguments passed are %-encoded before making the requests.

What still confuses me about all of this is that everything works fine before adding an ACL.

**Comment by bourgeoa** [comment]
@FlorSanders I shall try to give you the workflow in NSS, so you can understand why your app does not work with an ACL.
1. create resources (`test:test.ttl` or `test3Atest.ttl` give the same result on the file system)
- resource test:test.ttl is created => resource test:test.ttl is %-decoded => file test:test.ttl is created
- to create ACL : read the resource test:test.ttl => search %-decoded of test:test.tll => find file test:test.ttl => is %-encoded to resource test%3Atest.ttl => acl resource is created as test%3Atest.ttl.acl => %-decoded to file test:test.ttl.acl (acl content contains `<acl:accessTo <test%3Atest.ttl>`)
2. read resources do not give the same result on access rights
- to read resource `test:test.ttl` => you ask for acl content of resource test:test.ttl.acl => file is test:test.ttl.acl => that is %-encoded to resource test%3Atest.ttl.acl (acl:accessTo `do not match test:test.ttl`, `no access to resource test:test.ttl`)
- to read resource `test%3Atest.ttl` => you ask for acl content resource test%3Atest.ttl.acl => file is test:test.ttl.acl => that is %-encoded to resource test%3Atest.ttl.acl (acl:accessTo `do match test%3Atest.ttl` and you have `access to resource test%3Atest.ttl`)

A resource is an URL in NSS by nature.

> Also, if this is the case, wouldn't it be an idea to add a check on the input in rdflib.js, or even make sure the arguments passed are %-encoded before making the requests.

I supppose `rdflib` is not only meant to work with URI. So you have to take care of having avalid url (%-encoded)

ps: I posted in private to forum.solidproject.org for you solid.community pod

**Comment by FlorSanders** [comment]
Thanks for taking the time, this makes is way clearer!

> I supppose rdflib is not only meant to work with URI. So you have to take care of having avalid url (%-encoded)

Makes sense, thanks again.
Since this has nothing to do with NSS misbehaving, I'll close this issue then.
