### ISSUE TITLE
IDP list still links to solid.community which has migrated to solidcommunity.net

### ISSUE THREAD

**Issue by AJRepo** [solid/node-solid-server#1486]
Apologies if this is the wrong place for this issue: 

Using npm install solid-server one gets a button that says "Sign up for Solid" . That links to https://solid.github.io/solid-idps/?origin=....

One of the listings at https://solid.github.io/solid-idps/ is to solid.community, which is defunct. There is a redirect to solidcommunity.net, however, the SSL certificate your browser is looking for on the link is for the solid.community URL so you get security errors. 

It looked like the place to open that issue was https://github.com/solid/solid-idp-list/issues but that repository is now read-only. 

The link to solid.community should be replaced with one to solidcommunity.net. If there's a better place to open this ticket I'd be glad to close this one and open it there instead.

**Comment by michielbdejong** [comment]
Thanks for reporting! I'll change that URL to https://solidproject.org/use-solid/ in https://github.com/solid/solid-ui/blob/master/src/authn/config-default.js#L21
