### ISSUE TITLE
Header location with POST return path and not url

### ISSUE THREAD

**Issue by bourgeoa** [solid/node-solid-server#1507]
@csarven @michielbdejong @jeff-zucker  
Doing tests with solid-rest we found that header location return path and I was expecting url.
What is the good content from spec viewpoint.

in https://github.com/solid/node-solid-server/blob/master/lib/handlers/post.js
```
  function one () {
    debug('Receving one file')
    const { slug, link, 'content-type': contentType } = req.headers
    const links = header.parseMetadataFromHeader(link)
    const mimeType = contentType ? contentType.replace(/\s*;.*/, '') : ''
    const extension = mimeType in extensions ? `.${extensions[mimeType][0]}` : ''

    ldp.post(req.hostname, containerPath, req,
      { slug, extension, container: links.isBasicContainer, contentType }).then(
      resourcePath => {
        debug('File stored in ' + resourcePath)
        header.addLinks(res, links)
        res.set('Location', resourcePath)
        res.sendStatus(201)
        next()
      },
      err => next(err))
  }
```

**Comment by bourgeoa** [comment]
@csarven What is the proper spec viewpoint ?
@jeff-zucker
I reopen this issue due to differences between NSS and CSS, see discussion in issue https://github.com/0dataapp/hello-world-solid/issues/2 
- CSS header location return absolute URL in conformance with [rfc2616-sec14.30](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.30), 
- but NSS header location return the relative url like in MDN fetch.

**Comment by bourgeoa** [comment]
@michielbdejong What do you think ? Does this imply a test-suite change ?

**Comment by csarven** [comment]
Absolute reference is valid.

**Comment by bourgeoa** [comment]
@csarven thanks for the response. 
 https://datatracker.ietf.org/doc/html/rfc7231#section-7.1.2

It is not so easy for app developer to imagine that location depends on server implementation.

We will have to update our solid-file-client library.

Anyway this closes the issue.
