### ISSUE TITLE
Tagged Docker Hub builds out of date 

### ISSUE THREAD

**Issue by MikiDi** [solid/node-solid-server#1509]
Hi,

When comparing [tagged versions on Github](https://github.com/solid/node-solid-server/tags) with the [tagged builds on Docker hub](https://hub.docker.com/r/nodesolidserver/node-solid-server/tags), it looks like Docker hub stopped building tagged versions a couple of months ago. Although I'd perfectly be able to build an image myself, having the tagged builds available on Docker hub makes life easier.

While typing this up, I realized that the only two tagged builds available on Docker Hub are those that aren't tagged with a `v` as a prefix ... It might be no more than adding the `v` to the Docker Hub build regex.

From #1167 , I understand @angelo-v might be the right person to ask? If I can help in some way, I'd be glad to!

Michaël

**Comment by angelo-v** [comment]
Good catch, I will take a look at it

**Comment by angelo-v** [comment]
I added a build trigger vor versions starting with "v" as well. Cannnot trigger it manually for existing tags, but next time it should work again.
