### ISSUE TITLE
NSS should not allow deletion of the content of the root

### ISSUE THREAD

**Issue by scenaristeur** [solid/node-solid-server#1524]
_should not allow deletion of the root folder and some other that I call system folders like (profile, inbox, settings, .well-known)_
https://github.com/solid/solidcommunity.net/issues/27

**Comment by bourgeoa** [comment]
>When a DELETE request targets storage’s root container or its associated ACL resource, the server MUST respond with the 405 status code. Server MUST exclude the DELETE method in the HTTP response header Allow in response to safe method requests [RFC7231]. [Source]
https://solid.github.io/specification/#deleting-resources

**Comment by bourgeoa** [comment]
soved with PR #1554
