### ISSUE TITLE
Server emails include tracking pixels

### ISSUE THREAD

**Issue by jeff-zucker** [solid/node-solid-server#1532]
I just got a reset-password email from inrupt.net running 5.5.3 and this is in the body of the email:
```
<img src=3D"https://u7773952.ct.sendgrid.net/wf/open?upn=3DD7-2B4oi-2FnXzz2=
Un0791ni-2BqwjIABIvuzFIrH-2B1oiJ7StABQsIpH-2BxBvDtMR45DYqkbJxtUUAFGwUrMNbdb=
BbI7rqN1Q-2B7MlMVX2sh0rbxYgpzLPbS1zspw81FoduwnBzrvW-2FkPsMOGg3h6sg1pyhKZpGC=
tz85VCQ6XwSYvVkhLJS1zta1RhLd-2FVzqC3UnKDA4t0jdiAYLtpk9iSGivb-2F31sYkKcOfr6v=
L4-2FmPXnNd6gY-3D" alt=3D"" width=3D"1" height=3D"1" border=3D"0" style=3D"=
height:1px !important;width:1px !important;border-width:0 !important;margin=
-top:0 !important;margin-bottom:0 !important;margin-right:0 !important;marg=
in-left:0 !important;padding-top:0 !important;padding-bottom:0 !important;p=
adding-right:0 !important;padding-left:0 !important;"/>
```

**Comment by akuckartz** [comment]
I did not find information regarding this behavior on that page: https://inrupt.com/privacy-policy/

**Comment by angelo-v** [comment]
Perhaps you should file an issue at inrupt? I do not think this is part of NSS soure code, or is it?

**Comment by jeff-zucker** [comment]
@angelo-v Correct that it is not an NSS bug, however I just tested and the same thing happens on solidcommunity.net, so it isn't specific to Inrupt, so not sure where the issue should go.

**Comment by angelo-v** [comment]
Inrupt has a customer portal and for solid community there is a dedicated repo https://github.com/solid/solidcommunity.net

**Comment by jeff-zucker** [comment]
Thanks, will file in those places.

**Comment by kevin-inrupt** [comment]
The tracking pixel was not used by Inrupt for any purpose, and so has been removed from the password reset email. 

Thanks for bringing this to our attention.
