### ISSUE TITLE
non-turtle .meta files corrupt a folder

### ISSUE THREAD

**Issue by angelo-v** [solid/node-solid-server#1548]
*Actual behaviour*:

Given a folder contains a `.meta` file with invalid turtle
When the folder is requested
Then the server fails with status 500
And the browser shows `Can't parse container`

*Expected behaviour:*

NSS should reject to create `.meta` files that contain invalid turtle.

Further it should ignore existing `.meta` files or at least not try to parse them and fail.

It is essential that a folder containing such a `.meta` file for any reason can still be used and the `.meta` file can be fixed or deleted manually.

See also: https://github.com/solid/solidcommunity.net/issues/33

**Comment by bourgeoa** [comment]
> NSS should reject to create `.meta` files that contain invalid turtle.

done 
> Further it should ignore existing `.meta` files or at least not try to parse them and fail.

Still to be discussed 
> It is essential that a folder containing such a `.meta` file for any reason can still be used and the `.meta` file can be fixed or deleted manually

Can be done using a direct link to .meta

**Comment by bourgeoa** [comment]
https://github.com/solid/solidos/issues/129

**Comment by bourgeoa** [comment]
#1677
