### ISSUE TITLE
Invalid contact email address in README

### ISSUE THREAD

**Issue by brownhoward** [solid/node-solid-server#1560]
The README.MD still includes the following bullet point at the bottom:

- Reach out to Jackson at jacksonm@inrupt.com to become more involved in maintaining Node Solid Server

As this email address is not longer valid, recommend updating to an appropriate solidproject.org email or URL.

cc @jaxoncreed

**Comment by alceil** [comment]
I would like to take up this issue. And whats the email id I need to update? @brownhoward

**Comment by bourgeoa** [comment]
Thanks for participating. Every help is welcomed for resolving issues.
We actually have a common issue dashboard with SolidOS 
Being the main maintainer for about 2 years you can add my email alain.bourgeois10@gmail.com

**Comment by alceil** [comment]
I have raised a pr please have a look @bourgeoa

**Comment by bourgeoa** [comment]
Done with https://github.com/solid/node-solid-server/commit/1ac66461dbe4dba88a00ddec2fdb4552eb9c0076
