### ISSUE TITLE
POSTing ActivityPub message to Solid inbox produces wrong content-type

### ISSUE THREAD

**Issue by WhyINeedToFillUsername** [solid/node-solid-server#1574]
POSTing message to solid inbox (inrupt.net, Solid 5.6.4) with content type `application/ld+json; profile="https://www.w3.org/ns/activitystreams"` (official ActivityPub content-type from spec https://www.w3.org/TR/activitypub/#client-to-server-interactions) produces application/octet-stream content-type.

To be more specific:

- POST to /inbox/ with Content-Type `application/ld+json` -> created -> GET this message, you'll get `application/ld+json` Content-Type
- POST to /inbox/ with Content-Type `application/ld+json; profile="https://www.w3.org/ns/activitystreams"` -> created -> GET this message, you'll get **`application/octet-stream`** Content-Type, which is... bad :D

Might be related to other content-type issues (https://github.com/solid/node-solid-server/issues?q=is%3Aissue+is%3Aopen+application%2Foctet-stream), but I didn't find any quite this specific.

(originally reported at https://github.com/solid/community-server/issues/458#issuecomment-786203561)

**Comment by csarven** [comment]
IIRC, it has to do with the profile parameter. There is more to it:

* https://github.com/solid/node-solid-server/issues/621
* https://www.w3.org/TR/social-web-protocols/#inbox-interop , https://www.w3.org/TR/social-web-protocols/#profiles ..

**Comment by WhyINeedToFillUsername** [comment]
How do I find out if the fix has been released, please? :)
