### ISSUE TITLE
Missing server root registration button

### ISSUE THREAD

**Issue by jeff-zucker** [solid/node-solid-server#1625]
The sign-up button on the server-root index.html goes to solidproject.org list of pod-providers rather than to the /register endpoint as it used to.  I have fixed that and would appreciate that the two of you test the whole process at  https://jeff-zucker.solidcommunity.net:8443/test/server-root.html.  I put the register button in a-text link  rather than a button . That page should be good to go if the in-text link is okay.  The page on the registration endpoint should, AFAIK be good to go as-is with one exception : it has "already have an account?" and an old login button.  I recommend we just remove it.  If that's not ok, I can point it back to the server-root page.  To make an actual login button here, I'd need to recreate the entire script from the index.html here.  Although I could do that, it seems like  a lot of work for a very edge case of someone clicking "create an account" and then remembering "oh I already have an account" while also forgetting there's a back button on the browser. :-)  So let me know about the login button on the registration page, and whether the whole registration flow works the way you want it to.

**Comment by bourgeoa** [comment]
Sorry I missed all this before.
Work flow is correct now
> I put the register button in a-text link rather than a button

The page intention being **mostly** `register` and `login` if you are here by mistake or not remembering your webId I would prefer a button as it used to be

> with one exception : it has "already have an account?" and an old login button. I recommend we just remove it.

agreed. It can always be done latter.
