### ISSUE TITLE
Cannot switch WebIDs keeping same provider

### ISSUE THREAD

**Issue by jeff-zucker** [solid/node-solid-server#1630]
The problem : You are owner of webidA and webidB on given instance of NSS.  You login as webidA, then logout and attempt to login as webidB.  NSS logs you in as webidA.  

The problem is NOT the local cookie, it is the session stored on the server.

**Comment by bourgeoa** [comment]
If you have :
- only one browser tag open for the pod, then you can change pod with same provider
- if you have more than one pod, even if you logout, then you cannot change pod
- closing a tag do not log you out

**Comment by theRealImy** [comment]
I checked again, with one tab and with 2 tabs and with the same IDP and different IDPs. It actually seems to work fine, not sure what I tested last time. 
@jeff-zucker when you say "NSS logs you in as webidA." where do you see this? How did you test it explicitly?
I looked at the localStorage and the session and also tried to access private files for webIdA and webIdB. It behaved correctly from my point of view.

**Comment by bourgeoa** [comment]
@theRealImy try to open also a serverRoot URL then I think a serverRoot cookie is retained and you cannot change WebID.

**Comment by jeff-zucker** [comment]
Hmm, I can not reproduce the problem.  Yay!  Must have been something to do with the test server or maybe using the main server before it was patched.
