### ISSUE TITLE
Using NSS webId's to log in CSS fails with missing solid:oidcIssuer

### ISSUE THREAD

**Issue by bourgeoa** [solid/node-solid-server#1631]
https://github.com/solid/solid-oidc/issues/51

adding solid:oidcIssuer triple in profile/card#me allow log in.
like `:me solid:oidcIssuer <https://inrupt.net>`

**Comment by bourgeoa** [comment]
There seem that the discussion says same origin should allow implicit verification approval.

**Comment by bourgeoa** [comment]
see also https://gitter.im/solid/profile-spec?at=61ec42cf7842bd3ca95c3ca4 that tend to support some security control on writing to webId profile part of profile/card, namely solid:oidcIssuer.

**Comment by TallTed** [comment]
I *think* this is what was meant by the title for this issue:
```
Using NSS WebIDs to log in to CSS fails with missing `solid:oidcIssuer`
```

**Comment by bourgeoa** [comment]
closed with https://github.com/solid/node-solid-server/pull/1673
