### ISSUE TITLE
Account recovery via email

### ISSUE THREAD

**Issue by nicola** [solid/node-solid-server#175]
Match Gold implementation for account recovery

**Comment by nicola** [comment]
done in https://github.com/solid/node-solid-server/commit/0fab26fd7d9d23bc74df9407bceab82738a01f6b

**Comment by mediaprophet** [comment]
<img width="501" alt="screen shot 2016-06-16 at 3 00 26 am" src="https://cloud.githubusercontent.com/assets/5718022/16089531/dfe03544-336e-11e6-8670-50f579a7470e.png">
<img width="509" alt="screen shot 2016-06-16 at 3 00 45 am" src="https://cloud.githubusercontent.com/assets/5718022/16089535/e1bd860a-336e-11e6-9488-77f4b4beb0b9.png">

I've tried to recover my account via Chrome and Safari.  

Chrome I received the email, then typed in my details being my name and my WebID URI and it failed to issue me a cert. but gave me access to my account via warp.  (no cert)

Wasn't sure if it was adblocker or something; so tried with safari, and it issued a cert; but it seems the URI is incorrect. (images attached)
