### ISSUE TITLE
Implement API for deleting accounts

### ISSUE THREAD

**Issue by dmitrizagidulin** [solid/node-solid-server#177]
See https://github.com/solid/solid/issues/14 for discussion / specs.

**Comment by dmitrizagidulin** [comment]
See also https://github.com/linkeddata/gold/issues/28

**Comment by RubenVerborgh** [comment]
We need account management in general.

**Comment by kjetilk** [comment]
This is a big issue now, post-announce.

**Comment by justinwb** [comment]
Note that this should also have a corresponding action in the current UI for a logged-in user that allows them to do this (with confirmation).

**Comment by dmitrizagidulin** [comment]
So here's one way you could implement the Delete Account feature.

#### The 'Delete Account' button

[ ] Find a place to actually put the 'Delete Account' button. The first place that comes to mind, though may not be optimal, is somewhere on the [user account homepage / index.html](https://github.com/solid/node-solid-server/blob/develop/default-templates/new-account/index.html) app. Alternatively, you can put it in whatever profile editor app we're currently using.

The button/link should point people to the "Delete Account Confirmation" url, for example `/account/delete/send` (the existing reset password url is currently `/account/password/reset`, fwiw). This will be a GET request, but it'll be just to a confirmation page, so it's safe.

#### `DeleteAccountRequest` class

[ ] Create the `DeleteAccountRequest` class

This is a request that will display the Delete Account Confirmation page, and send the email with the delete link.

It'll go into `/lib/requests/`, feel free to model it on https://github.com/solid/node-solid-server/blob/develop/lib/requests/password-reset-email-request.js (it'll have essentially the same instance methods, since the steps are so similar).

It will become clearer what should actually go into this class soon; we'll come back to this.

#### Delete Account Confirmation routes

[ ] Add a GET route for `/account/delete/send` to the user accounts `middleware()` at https://github.com/solid/node-solid-server/blob/develop/lib/api/accounts/user-accounts.js#L61 - this will display the confirmation page
[ ] Add a POST route for `/account/delete/send` in the same place - this will actually handle the user input, and send the email.

This will look like:

```js
router.get('/account/delete/send', DeleteAccountRequest.get)
router.post('/account/delete/send', DeleteAccountRequest.post)
```

#### Delete Account Confirmation page

[ ] Create a page (Handlebars template) for Delete Account Confirmation

For an idea of what this is going to look like, go to `https://solid.community/login`, then hit `[Reset Password]` button, on the bottom right. So this is what you're aiming for, except the page will be asking the user "Please enter your account name. A link to delete the account will be emailed to the address you provided during account registration."

Model it on the [`reset-password.hbs`](https://github.com/solid/node-solid-server/blob/develop/default-views/auth/reset-password.hbs) Handlebars view.

This page requires the user to input their account name (so that we can [look up their email](https://github.com/solid/node-solid-server/blob/master/lib/models/account-manager.js#L471), which gets stored in the user's Root ACL file). _Side note: I think storing the recovery email in the root ACL instead of the user profile is going to be confusing to people. Especially since our profile editors aren't editing that file currently. I'm not sure how this convention came to be._

#### Delete Account Email template

[ ] Create a template for the email that gets sent (with the delete account link)

Model it on the 'reset password' email: https://github.com/solid/node-solid-server/blob/master/default-templates/emails/reset-password.js

#### Delete Account Email Sent page

[ ] Create a "Your delete link has been sent" page

Model it on https://github.com/solid/node-solid-server/blob/master/default-views/auth/reset-link-sent.hbs

(TO BE CONTINUED...)

**Comment by kjetilk** [comment]
@megoth and I decided that delete is the most important functionality right now, so we put the other stuff we did on hold to address this together.
