### ISSUE TITLE
Invert --webid default value, streamline flags towards default Solid behavior

### ISSUE THREAD

**Issue by dmitrizagidulin** [solid/node-solid-server#197]
From yesterday's discussion with @deiu and @nicola:

Desired default behavior (when launching `ldnode` with key and certificate parameter):

- WebID is enabled by default (no flag needed)
- Identity provider enabled by default (no flag needed)
- key and cert are required (to enable webid and identity provider functionality)
- Add an `--ldp-mode` flag (which turns of `webid` and `idp` flags, makes key and cert params not required).

**Comment by nicola** [comment]
This is in current, apart from --ldp-mode is --no-webid
