### ISSUE TITLE
Clean up unused (withering) branches.

### ISSUE THREAD

**Issue by deiu** [solid/node-solid-server#221]
We have a bunch of branches for ldnode that we're not using anymore. We need to check if it still makes sense to let them exist.

`fix-index` and `workspaces` are the only ones with pending PRs.

**Comment by dmitrizagidulin** [comment]
I think it's fairly safe to toss ones that aren't on active PRs. (Since, presumably, their original authors have copies of those branches locally).

**Comment by nicola** [comment]
let's delete them
