### ISSUE TITLE
Fix serialization to jsonld

### ISSUE THREAD

**Issue by deiu** [solid/node-solid-server#226]
Currently, during content negotiation for `application/ld+json`, ldnode serializes to turtle before translating to jsonld. We need this hack because the jsonld library does not support relative URIs. We should look into ways of avoiding double serialization by supporting relative URIs when serializing to jsonld.

**Comment by rhiaro** [comment]
+1 please fix relative URLs for JSON-LD. Currently I get domain.tld/slug, missing out any container hierarchy in the middle.

**Comment by dmitrizagidulin** [comment]
@rhiaro - can you provide some reproduce steps?
