### ISSUE TITLE
Add ability for Proxy to follow redirects

### ISSUE THREAD

**Issue by dmitrizagidulin** [solid/node-solid-server#258]
The main reason we have a proxy in LDNode is so we can fetch insecure (`http`) resources from scripts running on secure (`https`) pages.
However, as soon as an `http` resource returns a Redirect (say, `301` status), we run into a problem.

The XMLHttpRequest spec says that the browser must _transparently_ follow a 301 redirect. And there's [no way to disable that behavior](http://stackoverflow.com/questions/228225/prevent-redirection-of-xmlhttprequest). What ends up happening, however, is the following set of steps:
1. Solid client sees that it's trying to fetch an `http` resource from an `https` page, and switches to using a proxy url (say, LDNode's).
2. LDNode proxy fetches that `http` resource correctly, and returns a 301 redirect with a location.
3. The XHR response (without alerting the Solid client code) goes to transparently follow that 301 redirect, which can be to another insecure/`http` resource
4. The browser then shuts down the request with a `Mixed content` error, `This request has been blocked; the content must be served over HTTPS.` Unfortunately, this doesn't throw a catch-able Javascript error that the client can recover from. It just gets silently squashed.

To fix this situation, we need to extend LDNode's proxy to do the redirect-following on the server side, and only return the final results (making sure not to get stuck in an infinite loop) to the client.

**Comment by csarven** [comment]
Would https://www.npmjs.com/package/follow-redirects here?

**Comment by RubenVerborgh** [comment]
Not a priority right now.

**Comment by csarven** [comment]
Hello ldnode, we meet again. I've overlooked this issue. Created #1070 with the same expected result. PR in release/v5.0.0 : https://github.com/solid/node-solid-server/pull/1070
