### ISSUE TITLE
Add `typeIndex` registry links when creating new profile

### ISSUE THREAD

**Issue by dmitrizagidulin** [solid/node-solid-server#260]
Add support for the new `typeIndex` registry mechanism.
(Do a global search on `inbox` for the various places to add `typeIndex` support).
1. Create the public typeIndex resource in `/settings/`, add a corresponding link to user profile
2. Create the private typeIndex resource (same place), add a corresponding link to user preferences file.

**Comment by nicola** [comment]
Have we finalized on the typeRegistry (public and not?)

**Comment by dmitrizagidulin** [comment]
Still waiting on @timbl to review the typeIndex PR to solid/solid

**Comment by RubenVerborgh** [comment]
I'd say this is a client concern.
