### ISSUE TITLE
Implement If-Match and If-None-Match

### ISSUE THREAD

**Issue by deiu** [solid/node-solid-server#268]
The server should support conditional requests that contain an ETag in the `If-Match` or `If-None-Match` header.

**Comment by dmitrizagidulin** [comment]
+1 to this. (How do we currently generate our ETags, btw? Hopefully based on a hash of the resource?)

**Comment by deiu** [comment]
I think Express handles ETags.

**Comment by elf-pavlik** [comment]
I'd like also to have option in server config to require `If-Match` header for PUT requests when resource already exist. Similar to https://wiki.apache.org/couchdb/HTTP_Document_API#PUT
> To update an existing document, you also issue a PUT request. In this case, the JSON body must contain a _rev property, which lets CouchDB know which revision the edits are based on. If the revision of the document currently stored in the database doesn't match, then a 409 conflict error is returned.

Only requests which create new resource with PUT wouldn't need to include `If-Match`

**Comment by RubenVerborgh** [comment]
Not a priority right now.
