### ISSUE TITLE
500 "error translating JPEG to RDF+XML"

### ISSUE THREAD

**Issue by timbl** [solid/node-solid-server#270]
timbl 10:52

Using the firefox Tabulator extension with the very latest rdflib.js in it, I find that when opening it within the tabulator view I get for tehis image  a 500 "Internal Server Error". in the client log.

From ldnde server log:
```
Fri, 04 Mar 2016 10:22:00 GMT ldnode:get error translating: /timbl/2016/02/Medical/thumb_IMG_3781_1024.jpg image/jpeg -> application/rdf+xml -- 500 undefined
```

But how could that error occur anyway? Why ever should it be trying to convert an image to RDF anyway? (apart from extracting the JFIF out of it but igniore that)....

**Comment by timbl** [comment]
Sounds as though the conneg logic is not as logical as it should be!

**Comment by deiu** [comment]
It turns out the `Accept` header did not include a mime type for `image/*`, meaning that ldnode was not able to do conneg from an image to an rdf document. I suggest that we return `406 Not Acceptable` instead of `500`.

**Comment by nicola** [comment]
Will changing 500 to 406 work for you @timbl ?

**Comment by nicola** [comment]
I think we have addressed this a few commits ago, if this is not the case, please re-open this issue!
