### ISSUE TITLE
[Proxy] do not proxy secure networks (LAN)

### ISSUE THREAD

**Issue by deiu** [solid/node-solid-server#309]
The proxy system should not allow requests to LAN servers (IP ranges).

10.0.0.0/8 IP addresses: 10.0.0.0 -- 10.255.255.255
172.16.0.0/12 IP addresses: 172.16.0.0 -- 172.31.255.255
192.168.0.0/16 IP addresses: 192.168.0.0 – 192.168.255.255

**Comment by nicola** [comment]
Fixed in github.com/solid/node-solid-server/pull/342
