### ISSUE TITLE
Clarity about .key, .cert and .pem in README.md

### ISSUE THREAD

**Issue by bshambaugh** [solid/node-solid-server#323]
Perhaps more clarity about the key generation process is needed? 

An admin a key and certificate was first created:

openssl req -new -x509 -nodes -sha256 -days 3650 -key ../localhost.key -subj '/CN=*.localhost' > ../localhost.cert

This was then fed with the create admin option below giving:

ldnode --port 8443 --ssl-key localhost.key  --ssl-cert localhost.cert --create-admin
Can't find SSL key in ..../localhost.key
Error: Can't find SSL key in ..../localhost.key
    at Function.createServer (/usr/local/lib/node_modules/ldnode/lib/create-server.js:46:13)
    at bin (/usr/local/lib/node_modules/ldnode/bin/ldnode.js:141:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/ldnode/bin/ldnode.js:168:1)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

Per  http://stackoverflow.com/questions/991758/how-to-get-an-openssl-pem-file-from-key-and-crt-files I concluded I should choose to rename localhost.key to ssl-key.pem and localhost.cert to ssl-cert.pem  since the link suggested they were already in .pem format (as they both started with --BEGIN).

Once the renaming is done I ran:

ldnode --port 8443 --ssl-key ../ssl-key.pem --ssl-cert ../ssl-cert.pem --create-admin
Action required: Create your admin account on https://localhost:8443/
When done, stop your server (<ctrl>+c) and restart without "--create-admin"

See the conversation at gitter.im as I am still getting "Access to https://localhost:8443/ requires authorization" even though my certs appear in the browser.

**Comment by bshambaugh** [comment]
Renaming localhost.cert to ssl-cert.pem (or some other .cert to .pem) seems to be a valid practice per the howtossl documentation. http://how2ssl.com/articles/working_with_pem_files/

**Comment by dmitrizagidulin** [comment]
Hi Brent! Thanks for the suggestions. (Yeah, we can probably rename the files in the docs).

I noticed that in your first example that failed, you didn't have the `../` part, and were trying to access the key & cert in the same directory as ldnode (`--ssl-key localhost.key --ssl-cert localhost.cert `).

**Comment by rhiaro** [comment]
Just +1ing clarifying the docs on this as I just had to ask @dmitrizagidulin about the filenames IRL.

(For the record, advice was to generate .pem files for both with openssl in the first place).

**Comment by nicola** [comment]
Does the example in the README not work?

**Comment by bshambaugh** [comment]
Not really. I had more luck with cloning the repo and using the procedure
I've described before than

npm install -g solid-server , solid init , and solid start . As it is
I am not seeing

the certificate saved in the browser or things like .ttl files appear
in the browser


-Brent Shambaugh

Website: bshambaugh.org

**Comment by nicola** [comment]
Can I close this issue? 
This is related to the SSL keys

**Comment by bshambaugh** [comment]
Sure, go for it.

-Brent Shambaugh

Website: bshambaugh.org
