### ISSUE TITLE
After npm list -g from home/user/ directory node mailer stuff is missing ..

### ISSUE THREAD

**Issue by bshambaugh** [solid/node-solid-server#344]
Here is a selection from the npm list -g results:

npm ERR! invalid: mailcomposer@3.7.0 /usr/local/lib/node_modules/solid-server/node_modules/nodemailer/node_modules/mailcomposer
npm ERR! invalid: nodemailer-direct-transport@3.0.7 /usr/local/lib/node_modules/solid-server/node_modules/nodemailer/node_modules/nodemailer-direct-transport
npm ERR! invalid: nodemailer-smtp-pool@2.5.2 /usr/local/lib/node_modules/solid-server/node_modules/nodemailer/node_modules/nodemailer-smtp-pool
npm ERR! invalid: nodemailer-smtp-transport@2.4.2 /usr/local/lib/node_modules/solid-server/node_modules/nodemailer/node_modules/nodemailer-smtp-transport

**Comment by nicola** [comment]
why `-g` ?
does your solid-server install or not?

**Comment by bshambaugh** [comment]
npm list > ../npm_list
npm ERR! missing: nodemailer-shared@1.0.5, required by nodemailer@2.4.0
npm ERR! invalid: mailcomposer@3.7.0 /usr/local/bin/node-solid-server/node-solid-server/node_modules/nodemailer/node_modules/mailcomposer
npm ERR! invalid: nodemailer-direct-transport@3.0.7 /usr/local/bin/node-solid-server/node-solid-server/node_modules/nodemailer/node_modules/nodemailer-direct-transport
npm ERR! invalid: nodemailer-smtp-pool@2.5.2 /usr/local/bin/node-solid-server/node-solid-server/node_modules/nodemailer/node_modules/nodemailer-smtp-pool
npm ERR! invalid: nodemailer-smtp-transport@2.4.2 /usr/local/bin/node-solid-server/node-solid-server/node_modules/nodemailer/node_modules/nodemailer-smtp-transport

**Comment by bshambaugh** [comment]
I'm getting closer I think. To be verbose. here is the full output after an npm update.

npm list
solid-server@2.1.5 /usr/local/bin/node-solid-server/node-solid-server
├── async@1.5.2
├─┬ body-parser@1.15.1
│ ├── bytes@2.3.0
│ ├── content-type@1.0.2
│ ├── depd@1.1.0
│ ├─┬ http-errors@1.4.0
│ │ └── statuses@1.2.1
│ ├── iconv-lite@0.4.13
│ ├─┬ on-finished@2.3.0
│ │ └── ee-first@1.1.1
│ ├── qs@6.1.0
│ ├─┬ raw-body@2.1.6
│ │ └── unpipe@1.0.0
│ └─┬ type-is@1.6.12
│   └── media-typer@0.3.0
├─┬ busboy@0.2.13
│ ├─┬ dicer@0.2.5
│ │ └── streamsearch@0.1.2
│ └─┬ readable-stream@1.1.14
│   ├── core-util-is@1.0.2
│   ├── isarray@0.0.1
│   └── string_decoder@0.10.31
├── camelize@1.0.0
├─┬ chai@3.5.0
│ ├── assertion-error@1.0.1
│ ├─┬ deep-eql@0.1.3
│ │ └── type-detect@0.1.1
│ └── type-detect@1.0.0
├── colors@1.1.2
├─┬ cors@2.7.1
│ └── vary@1.1.0
├─┬ debug@2.2.0
│ └── ms@0.7.1
├─┬ express@4.13.4
│ ├─┬ accepts@1.2.13
│ │ └── negotiator@0.5.3
│ ├── array-flatten@1.1.1
│ ├── content-disposition@0.5.1
│ ├── cookie@0.1.5
│ ├── cookie-signature@1.0.6
│ ├── escape-html@1.0.3
│ ├── etag@1.7.0
│ ├── finalhandler@0.4.1
│ ├── fresh@0.3.0
│ ├── merge-descriptors@1.0.1
│ ├── methods@1.1.2
│ ├── parseurl@1.3.1
│ ├── path-to-regexp@0.1.7
│ ├─┬ proxy-addr@1.0.10
│ │ └── forwarded@0.1.0
│ ├── qs@4.0.0
│ ├── range-parser@1.0.3
│ ├─┬ send@0.13.1
│ │ ├── destroy@1.0.4
│ │ └── http-errors@1.3.1
│ ├── serve-static@1.10.2
│ ├── utils-merge@1.0.0
│ └── vary@1.0.1
├─┬ express-session@1.13.0
│ ├── cookie@0.2.3
│ ├── crc@3.4.0
│ ├── on-headers@1.0.1
│ └─┬ uid-safe@2.0.0
│   └── base64-url@1.2.1
├── extend@3.0.0
├─┬ from2@2.1.1
│ ├── inherits@2.0.1
│ └─┬ readable-stream@2.1.2
│   ├── isarray@1.0.0
│   ├── process-nextick-args@1.0.7
│   └── util-deprecate@1.0.2
├─┬ fs-extra@0.30.0
│ ├── graceful-fs@4.1.4
│ ├── jsonfile@2.3.0
│ ├── klaw@1.2.0
│ └── path-is-absolute@1.0.0
├─┬ glob@7.0.3
│ ├─┬ inflight@1.0.4
│ │ └── wrappy@1.0.1
│ ├─┬ minimatch@3.0.0
│ │ └─┬ brace-expansion@1.1.4
│ │   ├── balanced-match@0.4.1
│ │   └── concat-map@0.0.1
│ └── once@1.3.3
├─┬ inquirer@1.0.2
│ ├── ansi-escapes@1.4.0
│ ├─┬ chalk@1.1.3
│ │ ├── ansi-styles@2.2.1
│ │ ├── escape-string-regexp@1.0.5
│ │ ├── has-ansi@2.0.0
│ │ └── supports-color@2.0.0
│ ├─┬ cli-cursor@1.0.2
│ │ └─┬ restore-cursor@1.0.1
│ │   ├── exit-hook@1.1.1
│ │   └── onetime@1.1.0
│ ├── cli-width@2.1.0
│ ├── figures@1.6.0
│ ├── lodash@4.12.0
│ ├── mute-stream@0.0.6
│ ├─┬ pinkie-promise@2.0.1
│ │ └── pinkie@2.0.4
│ ├─┬ run-async@2.2.0
│ │ └── is-promise@2.1.0
│ ├── rx@4.1.0
│ ├─┬ string-width@1.0.1
│ │ ├─┬ code-point-at@1.0.0
│ │ │ └── number-is-nan@1.0.0
│ │ └── is-fullwidth-code-point@1.0.0
│ ├─┬ strip-ansi@3.0.1
│ │ └── ansi-regex@2.0.0
│ └── through@2.3.8
├─┬ ip-range-check@0.0.1
│ └── ipaddr.js@1.0.5
├─┬ is-ip@1.0.0
│ └── ip-regex@1.0.3
├─┬ jsonld@0.4.11
│ ├── es6-promise@2.3.0
│ ├── pkginfo@0.4.0
│ └── xmldom@0.1.19
├── li@1.0.1
├── mime@1.3.4
├─┬ mocha@2.4.5
│ ├── commander@2.3.0
│ ├── diff@1.4.0
│ ├── escape-string-regexp@1.0.2
│ ├─┬ glob@3.2.3
│ │ ├── graceful-fs@2.0.3
│ │ └─┬ minimatch@0.2.14
│ │   ├── lru-cache@2.7.3
│ │   └── sigmund@1.0.1
│ ├── growl@1.8.1
│ ├─┬ jade@0.26.3
│ │ ├── commander@0.6.1
│ │ └── mkdirp@0.3.0
│ ├─┬ mkdirp@0.5.1
│ │ └── minimist@0.0.8
│ └── supports-color@1.2.0
├── moment@2.13.0
├── n3@0.4.5
├── negotiator@0.6.1
├─┬ nock@7.7.3
│ ├── deep-equal@1.0.1
│ ├── json-stringify-safe@5.0.1
│ ├── lodash@3.10.1
│ └── propagate@0.3.1
├── node-forge@0.6.39
├── node-uuid@1.4.7
├─┬ nodemailer@2.4.0
│ ├─┬ libmime@2.0.3
│ │ ├── iconv-lite@0.4.13
│ │ ├── libbase64@0.1.0
│ │ └── libqp@1.1.0
│ ├─┬ mailcomposer@3.7.0 invalid
│ │ └─┬ buildmail@3.6.0
│ │   ├── addressparser@1.0.1
│ │   └── nodemailer-fetch@1.3.0
│ ├─┬ nodemailer-direct-transport@3.0.7 invalid
│ │ ├── nodemailer-shared@1.0.4
│ │ └── smtp-connection@2.3.2
│ ├── UNMET DEPENDENCY nodemailer-shared@1.0.5
│ ├─┬ nodemailer-smtp-pool@2.5.2 invalid
│ │ └── nodemailer-wellknown@0.1.8
│ ├── nodemailer-smtp-transport@2.4.2 invalid
│ └─┬ socks@1.1.9
│   ├── ip@1.1.2
│   └── smart-buffer@1.0.4
├─┬ nomnom@1.8.1
│ ├─┬ chalk@0.4.0
│ │ ├── ansi-styles@1.0.0
│ │ ├── has-color@0.1.7
│ │ └── strip-ansi@0.1.1
│ └── underscore@1.6.0
├─┬ rdflib@0.6.1
│ ├── async@0.9.2
│ ├── xmldom@0.1.22
│ └── xmlhttprequest@1.8.0
├─┬ request@2.72.0
│ ├── aws-sign2@0.6.0
│ ├── aws4@1.4.1
│ ├─┬ bl@1.1.2
│ │ └─┬ readable-stream@2.0.6
│ │   └── isarray@1.0.0
│ ├── caseless@0.11.0
│ ├─┬ combined-stream@1.0.5
│ │ └── delayed-stream@1.0.0
│ ├── forever-agent@0.6.1
│ ├── form-data@1.0.0-rc4
│ ├─┬ har-validator@2.0.6
│ │ ├─┬ commander@2.9.0
│ │ │ └── graceful-readlink@1.0.1
│ │ └─┬ is-my-json-valid@2.13.1
│ │   ├── generate-function@2.0.0
│ │   ├─┬ generate-object-property@1.2.0
│ │   │ └── is-property@1.0.2
│ │   └── jsonpointer@2.0.0
│ ├─┬ hawk@3.1.3
│ │ ├── boom@2.10.1
│ │ ├── cryptiles@2.0.5
│ │ ├── hoek@2.16.3
│ │ └── sntp@1.0.9
│ ├─┬ http-signature@1.1.1
│ │ ├── assert-plus@0.2.0
│ │ ├─┬ jsprim@1.2.2
│ │ │ ├── extsprintf@1.0.2
│ │ │ ├── json-schema@0.2.2
│ │ │ └── verror@1.3.6
│ │ └─┬ sshpk@1.8.3
│ │   ├── asn1@0.2.3
│ │   ├── assert-plus@1.0.0
│ │   ├─┬ dashdash@1.13.1
│ │   │ └── assert-plus@1.0.0
│ │   ├── ecc-jsbn@0.1.1
│ │   ├─┬ getpass@0.1.6
│ │   │ └── assert-plus@1.0.0
│ │   ├── jodid25519@1.0.2
│ │   ├── jsbn@0.1.0
│ │   └── tweetnacl@0.13.3
│ ├── is-typedarray@1.0.0
│ ├── isstream@0.1.2
│ ├─┬ mime-types@2.1.11
│ │ └── mime-db@1.23.0
│ ├── oauth-sign@0.8.2
│ ├── stringstream@0.0.5
│ ├── tough-cookie@2.2.2
│ └── tunnel-agent@0.4.3
├── rimraf@2.5.2
├── rsvp@3.2.1
├─┬ sinon@1.17.4
│ ├── formatio@1.1.1
│ ├── lolex@1.3.2
│ ├── samsam@1.1.2
│ └── util@0.10.3
├─┬ solid-ws@0.2.2
│ ├── run-parallel@1.1.6
│ └─┬ ws@0.8.1
│   ├── UNMET OPTIONAL DEPENDENCY bufferutil@1.2.x
│   ├── options@0.0.6
│   ├── ultron@1.0.2
│   └── UNMET OPTIONAL DEPENDENCY utf-8-validate@1.2.x
├─┬ standard@7.0.1
│ ├─┬ eslint@2.9.0
│ │ ├─┬ concat-stream@1.5.1
│ │ │ ├─┬ readable-stream@2.0.6
│ │ │ │ └── isarray@1.0.0
│ │ │ └── typedarray@0.0.6
│ │ ├─┬ doctrine@1.2.1
│ │ │ ├── esutils@1.1.6
│ │ │ └── isarray@1.0.0
│ │ ├─┬ es6-map@0.1.3
│ │ │ ├── d@0.1.1
│ │ │ ├── es5-ext@0.10.11
│ │ │ ├── es6-iterator@2.0.0
│ │ │ ├── es6-set@0.1.4
│ │ │ ├── es6-symbol@3.0.2
│ │ │ └── event-emitter@0.3.4
│ │ ├─┬ escope@3.6.0
│ │ │ ├── es6-weak-map@2.0.1
│ │ │ └─┬ esrecurse@4.1.0
│ │ │   └── estraverse@4.1.1
│ │ ├─┬ espree@3.1.4
│ │ │ ├── acorn@3.1.0
│ │ │ └── acorn-jsx@3.0.1
│ │ ├── estraverse@4.2.0
│ │ ├── esutils@2.0.2
│ │ ├─┬ file-entry-cache@1.2.4
│ │ │ ├─┬ flat-cache@1.0.10
│ │ │ │ ├─┬ del@2.2.0
│ │ │ │ │ ├─┬ globby@4.0.0
│ │ │ │ │ │ ├─┬ array-union@1.0.1
│ │ │ │ │ │ │ └── array-uniq@1.0.2
│ │ │ │ │ │ ├── arrify@1.0.1
│ │ │ │ │ │ └── glob@6.0.4
│ │ │ │ │ ├── is-path-cwd@1.0.0
│ │ │ │ │ ├─┬ is-path-in-cwd@1.0.0
│ │ │ │ │ │ └── is-path-inside@1.0.0
│ │ │ │ │ └── pify@2.3.0
│ │ │ │ ├── read-json-sync@1.1.1
│ │ │ │ └── write@0.2.1
│ │ │ └── object-assign@4.1.0
│ │ ├── globals@9.6.0
│ │ ├── ignore@3.1.2
│ │ ├── imurmurhash@0.1.4
│ │ ├─┬ inquirer@0.12.0
│ │ │ ├─┬ readline2@1.0.1
│ │ │ │ └── mute-stream@0.0.5
│ │ │ ├── run-async@0.1.0
│ │ │ └── rx-lite@3.1.2
│ │ ├─┬ is-resolvable@1.0.0
│ │ │ └── tryit@1.0.2
│ │ ├─┬ js-yaml@3.6.0
│ │ │ ├─┬ argparse@1.0.7
│ │ │ │ └── sprintf-js@1.0.3
│ │ │ └── esprima@2.7.2
│ │ ├─┬ json-stable-stringify@1.0.1
│ │ │ └── jsonify@0.0.0
│ │ ├─┬ optionator@0.8.1
│ │ │ ├── deep-is@0.1.3
│ │ │ ├── fast-levenshtein@1.1.3
│ │ │ ├── levn@0.3.0
│ │ │ ├── prelude-ls@1.1.2
│ │ │ ├── type-check@0.3.2
│ │ │ └── wordwrap@1.0.0
│ │ ├── path-is-inside@1.0.1
│ │ ├── pluralize@1.2.1
│ │ ├── progress@1.1.8
│ │ ├─┬ require-uncached@1.0.2
│ │ │ ├─┬ caller-path@0.1.0
│ │ │ │ └── callsites@0.2.0
│ │ │ └── resolve-from@1.0.1
│ │ ├── shelljs@0.6.0
│ │ ├── strip-json-comments@1.0.4
│ │ ├─┬ table@3.7.8
│ │ │ ├── bluebird@3.3.5
│ │ │ ├── slice-ansi@0.0.4
│ │ │ ├── tv4@1.2.7
│ │ │ └── xregexp@3.1.0
│ │ ├── text-table@0.2.0
│ │ └─┬ user-home@2.0.0
│ │   └── os-homedir@1.0.1
│ ├── eslint-config-standard@5.3.1
│ ├── eslint-config-standard-jsx@1.2.0
│ ├── eslint-plugin-promise@1.1.0
│ ├── eslint-plugin-react@5.1.1
│ ├── eslint-plugin-standard@1.3.2
│ └─┬ standard-engine@4.0.1
│   ├─┬ defaults@1.0.3
│   │ └── clone@1.0.2
│   ├─┬ deglob@1.1.1
│   │ ├── find-root@0.1.2
│   │ ├── glob@6.0.4
│   │ └── uniq@1.0.1
│   ├── find-root@1.0.0
│   ├── get-stdin@5.0.1
│   ├── minimist@1.2.0
│   ├─┬ multiline@1.0.2
│   │ └─┬ strip-indent@1.0.1
│   │   └── get-stdin@4.0.1
│   ├─┬ pkg-config@1.1.1
│   │ └── debug-log@1.0.0
│   └── xtend@4.0.1
├── string@3.3.1
├─┬ supertest@1.2.0
│ └─┬ superagent@1.8.3
│   ├── component-emitter@1.2.1
│   ├── cookiejar@2.0.6
│   ├── form-data@1.0.0-rc3
│   ├── formidable@1.0.17
│   ├── qs@2.3.3
│   ├── readable-stream@1.0.27-1
│   └── reduce-component@1.0.1
├── uuid@2.0.2
├── valid-url@1.0.9
├── vhost@3.0.2
└─┬ webid@0.3.7
  └─┬ rdflib@0.2.11
    ├── async@0.9.2
    ├─┬ browserify@13.0.1
    │ ├── assert@1.3.0
    │ ├─┬ browser-pack@6.0.1
    │ │ ├─┬ combine-source-map@0.7.2
    │ │ │ ├── convert-source-map@1.1.3
    │ │ │ ├── inline-source-map@0.6.2
    │ │ │ ├── lodash.memoize@3.0.4
    │ │ │ └── source-map@0.5.6
    │ │ └── umd@3.0.1
    │ ├── browser-resolve@1.11.1
    │ ├─┬ browserify-zlib@0.1.4
    │ │ └── pako@0.2.8
    │ ├─┬ buffer@4.6.0
    │ │ ├── base64-js@1.1.2
    │ │ ├── ieee754@1.1.6
    │ │ └── isarray@1.0.0
    │ ├─┬ console-browserify@1.1.0
    │ │ └── date-now@0.1.4
    │ ├── constants-browserify@1.0.0
    │ ├─┬ crypto-browserify@3.11.0
    │ │ ├─┬ browserify-cipher@1.0.0
    │ │ │ ├─┬ browserify-aes@1.0.6
    │ │ │ │ └── buffer-xor@1.0.3
    │ │ │ ├─┬ browserify-des@1.0.0
    │ │ │ │ └─┬ des.js@1.0.0
    │ │ │ │   └── minimalistic-assert@1.0.0
    │ │ │ └── evp_bytestokey@1.0.0
    │ │ ├─┬ browserify-sign@4.0.0
    │ │ │ ├── bn.js@4.11.3
    │ │ │ ├── browserify-rsa@4.0.1
    │ │ │ ├─┬ elliptic@6.2.3
    │ │ │ │ ├── brorand@1.0.5
    │ │ │ │ └── hash.js@1.0.3
    │ │ │ └─┬ parse-asn1@5.0.0
    │ │ │   └── asn1.js@4.6.0
    │ │ ├── create-ecdh@4.0.0
    │ │ ├─┬ create-hash@1.1.2
    │ │ │ ├── cipher-base@1.0.2
    │ │ │ └── ripemd160@1.0.1
    │ │ ├── create-hmac@1.1.4
    │ │ ├─┬ diffie-hellman@5.0.2
    │ │ │ └── miller-rabin@4.0.0
    │ │ ├── pbkdf2@3.0.4
    │ │ ├── public-encrypt@4.0.0
    │ │ └── randombytes@2.0.3
    │ ├── defined@1.0.0
    │ ├── deps-sort@2.0.0
    │ ├── domain-browser@1.1.7
    │ ├─┬ duplexer2@0.1.4
    │ │ └─┬ readable-stream@2.1.2
    │ │   └── isarray@1.0.0
    │ ├── events@1.1.0
    │ ├── glob@5.0.15
    │ ├─┬ has@1.0.1
    │ │ └── function-bind@1.1.0
    │ ├── htmlescape@1.1.1
    │ ├── https-browserify@0.0.1
    │ ├─┬ insert-module-globals@7.0.1
    │ │ ├── is-buffer@1.1.3
    │ │ └─┬ lexical-scope@1.2.0
    │ │   └─┬ astw@2.0.0
    │ │     └── acorn@1.2.2
    │ ├─┬ JSONStream@1.1.1
    │ │ └── jsonparse@1.2.0
    │ ├─┬ labeled-stream-splicer@2.0.0
    │ │ └─┬ stream-splicer@2.0.0
    │ │   └─┬ readable-stream@2.1.2
    │ │     └── isarray@1.0.0
    │ ├─┬ module-deps@4.0.5
    │ │ ├─┬ detective@4.3.1
    │ │ │ └── acorn@1.2.2
    │ │ ├─┬ readable-stream@2.1.2
    │ │ │ └── isarray@1.0.0
    │ │ └─┬ stream-combiner2@1.1.1
    │ │   └─┬ readable-stream@2.1.2
    │ │     └── isarray@1.0.0
    │ ├── os-browserify@0.1.2
    │ ├─┬ parents@1.0.1
    │ │ └── path-platform@0.11.15
    │ ├── path-browserify@0.0.0
    │ ├── process@0.11.3
    │ ├── punycode@1.4.1
    │ ├── querystring-es3@0.2.1
    │ ├─┬ read-only-stream@2.0.0
    │ │ └─┬ readable-stream@2.1.2
    │ │   └── isarray@1.0.0
    │ ├─┬ readable-stream@2.1.2
    │ │ └── isarray@1.0.0
    │ ├── resolve@1.1.7
    │ ├─┬ shasum@1.0.2
    │ │ ├── json-stable-stringify@0.0.1
    │ │ └── sha.js@2.4.5
    │ ├─┬ shell-quote@1.6.0
    │ │ ├── array-filter@0.0.1
    │ │ ├── array-map@0.0.0
    │ │ └── array-reduce@0.0.0
    │ ├─┬ stream-browserify@2.0.1
    │ │ └─┬ readable-stream@2.1.2
    │ │   └── isarray@1.0.0
    │ ├─┬ stream-http@2.3.0
    │ │ ├── builtin-status-codes@2.0.0
    │ │ ├─┬ readable-stream@2.1.2
    │ │ │ └── isarray@1.0.0
    │ │ └── to-arraybuffer@1.0.1
    │ ├─┬ subarg@1.0.0
    │ │ └── minimist@1.2.0
    │ ├─┬ syntax-error@1.1.6
    │ │ └── acorn@2.7.0
    │ ├─┬ through2@2.0.1
    │ │ └─┬ readable-stream@2.0.6
    │ │   └── isarray@1.0.0
    │ ├── timers-browserify@1.4.2
    │ ├── tty-browserify@0.0.0
    │ ├─┬ url@0.11.0
    │ │ ├── punycode@1.3.2
    │ │ └── querystring@0.2.0
    │ └─┬ vm-browserify@0.0.4
    │   └── indexof@0.0.1
    └── coffee-script@1.10.0

**Comment by bshambaugh** [comment]
Using the -g option was a force of habit. I removed it. It works to the extent that I reported. I may need to look at things like bufferutil. This may be related. I am not sure what I am doing...

**Comment by bshambaugh** [comment]
This is basically where I am at. Hopefully I will get back to this soon. https://github.com/bshambaugh/ldnode-experiments/blob/master/wed_may_11_1208_npm_update_log.txt

**Comment by nicola** [comment]
Looks like you are having some issues here:

```
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/6.0.0"
```

are you sure you are running node 6 and the latest npm?

**Comment by bshambaugh** [comment]
Trying "npm install -g npm " from outside the directory and  "npm update" from in the directory (the cloned node-solid-server directory) echoed nothing to the screen. I think I was root the whole time. This is promising.

**Comment by bshambaugh** [comment]
/node-solid-server# node -v
v6.0.0

**Comment by melvincarvalho** [comment]
@bshambaugh can I close this old issue?  Perhaps try with node 8?
