### ISSUE TITLE
OIDC integration v1

### ISSUE THREAD

**Issue by nicola** [solid/node-solid-server#348]
## v1

Ldnode side
- [x] Server capabilities discovery: https://github.com/solid/node-solid-server/pull/347
- [x] Switch between WebID-TLS and OIDC https://github.com/solid/node-solid-server/pull/346
- [x] Accounts APIs `/api/accounts` https://github.com/solid/node-solid-server/pull/339 @nicola
- [x] OIDC APIs `/api/oidc` https://github.com/solid/node-solid-server/pull/330 @dmitrizagidulin 
- [x] Sync Accounts APIs and OIDC APIs @dmitrizagidulin @nicola
- [x] Test workflow https://github.com/solid/node-solid-server/pull/345 @deiu @nicola
- [x] Email support for account creation and account recovery https://github.com/solid/node-solid-server/pull/335

Application side
- [x] Signin app (to discover the webid) @deiu
- [x] Signup app (to create the webid) @deiu 

OIDC side
- [x] Fix temporary signin.html page, test webid -> oidc provider discovery
- [x] Test user creation api endpoint (integration w oidc)
- [x] Test login workflow with two OIDC providers (like localhost & freecandy.space)
- [x] Implement the 'verify the webid' step during login process

`/api/oidc/` endpoints:
- `/api/oidc/rp` - relying party callback

Have a look at the [scenario](https://github.com/solid/node-solid-server/blob/25921b8a282b29fd18d175a23cd5a2e9d016e22c/test/scenarios.md) to understand the steps

**Comment by dmitrizagidulin** [comment]
Moving 'fix async / race condition problem' / 'implement persistent client store' item to the [next version](https://github.com/solid/node-solid-server/issues/353)

**Comment by nicola** [comment]
Didn't I implement this already?



On Thu, Jun 2, 2016 at 11:08 AM -0700, "Dmitri Zagidulin" <notifications@github.com> wrote:












Moving 'fix async / race condition problem' / 'implement persistent client store' item to the next version

**Comment by dmitrizagidulin** [comment]
Partly. The PR isn't working, which is fine, the functionality from it is being merged into upstream libraries.

**Comment by nicola** [comment]
hey @dmitrizagidulin what is the state of this?

**Comment by dmitrizagidulin** [comment]
The individual items are implemented, the issue can be closed.

**Comment by nicola** [comment]
Perfect!
Let's leave till they are not in master, no?Do we have any time line to bring oidc in?

**Comment by dmitrizagidulin** [comment]
Sure thing.

Not sure if we have a timeline specifically, but I'm tracking the remaining items at this epic here: https://github.com/solid/node-solid-server/issues/353

**Comment by melvincarvalho** [comment]
@dmitrizagidulin ok to close this now?

**Comment by melvincarvalho** [comment]
@dmitrizagidulin gentle bump on this.  Will close this issue soon if there's not an objection.

**Comment by dmitrizagidulin** [comment]
@melvincarvalho - ah, thanks! Missed the previous query somehow. 

Yes, this should be ok to close (closing it, in fact).
