### ISSUE TITLE
Account APIs v2

### ISSUE THREAD

**Issue by nicola** [solid/node-solid-server#350]
#### LDNODE
- [ ] `/api/accounts/delete`: account is deleted from LDP and (?)
#### OIDC
- [ ] `/api/accounts/signout`: removes standing tokens (?)
- [ ] `/api/accounts/validateToken`: redirect to create a new password?
- [ ] `/api/accounts/delete`: deleting on OIDC (?)
  I ticked the ones I have implemented.

**Comment by RubenVerborgh** [comment]
We indeed need an account manager at some point.
