### ISSUE TITLE
SOLID Init Script does not lead to a resolvable page

### ISSUE THREAD

**Issue by bshambaugh** [solid/node-solid-server#354]
Installation Method: sudo npm install solid-server

Environment: node 6.10, npm 3.90, Firefox 46.0, Machine: Inspiron 1525, uname -a == Linux brent-Inspiron-1525 3.2.0-97-generic #137-Ubuntu SMP Thu Dec 17 18:11:47 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux, lsb_release -a == No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 12.04.5 LTS
Release:    12.04
Codename:   precise

In the Browser
view-source:https://localhost:8443/  
Not Found 

In the Terminal Emulator:
root@brent-Inspiron-1525:/usr/local/bin/node-solid-server# solid init
? Path to the folder you want to serve. Default is /
? SSL port to run on. Default is 8443
? Enable WebID authentication Yes
? Select authentication strategy WebID-TLS
? Path to the SSL private key in PEM format /usr/local/bin/node-solid-server/localhost.key
? Path to the SSL certificate key in PEM format /usr/local/bin/node-solid-server/localhost.crt
? Allow users to sign up for an account Yes
? Type the URL of default app to use for browsing files (or use default) https://linkeddata.github.io/warp/#/list/
? Enable data viewer (defaults to using Tabulator) Yes
? Enforce same origin policy in the ACL Yes
? Do you want to set up an email service? No
config created on /usr/local/bin/node-solid-server/config.json
root@brent-Inspiron-1525:/usr/local/bin/node-solid-server# solid start
Solid server (solid v2.3.0) running on https://localhost:8443/
Press <ctrl>+c to stop

**Comment by nicola** [comment]
uhm, interesting.

- Do you mind removing the .acl if you have any in that folder?
- Do you mind re-running the setting saying `No` to _Enforce same origin policy in the ACL_

**Comment by bshambaugh** [comment]
At present, the only .acl type files are in test. Running with "No" did not change the result. The good news is I learned something unrelated to this issue but necessary. That is, treat ubuntu 12.04 differently when running with node and npm. https://github.com/nodesource/distributions/blob/master/OLDER_DISTROS.md . I think your suggestion of meeting to chat will be a good one. Fortunately I will be distracted for the next couple days, giving us both time. Hopefully things will be in more order by then. Thanks Nicola.
