### ISSUE TITLE
Authorization Fails with Admin Signup

### ISSUE THREAD

**Issue by bshambaugh** [solid/node-solid-server#355]
Installation Method: git clone https://github.com/solid/node-solid-server.git
                                   npm install -g
                                   npm install pug -g (for a warning when trying npm install without -g)  -
see https://github.com/bshambaugh/ldnode-experiments/blob/master/wed_may_11_1208_npm_update_log.txt (for similar output)
                                   npm ls graceful-fs (for a warning when trying npm install without -g)
see https://github.com/bshambaugh/ldnode-experiments/blob/master/wed_may_11_1208_npm_update_log.txt (for similar output)

Environment: node 6.10, npm 3.90, Firefox 46.0, Machine: Inspiron 1525, uname -a == Linux brent-Inspiron-1525 3.2.0-97-generic #137-Ubuntu SMP Thu Dec 17 18:11:47 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux, lsb_release -a == No LSB modules are available.
Distributor ID: Ubuntu
Description: Ubuntu 12.04.5 LTS
Release: 12.04
Codename: precise

First start:
                          solid start --port 8443 --ssl-key ../localhost.key --ssl-cert ../localhost.crt -v --webid

In the Browser:
Admin Signup: Create Your Account Screen appears, blue button fails
Error: Request failed
Stack trace:
createAccount/http.onreadystatechange@https://localhost:8443/:73:20

In the Terminal:

solid start --port 8443 --ssl-key ../localhost.key --ssl-cert ../localhost.crt -v --webid
TIP create a config.json: `$ solid init`
  solid:settings Suffix Acl: .acl +0ms
  solid:settings Suffix Meta: .meta +3ms
  solid:settings Filesystem Root: /usr/local/bin/node-solid-server/node-solid-server/ +1ms
  solid:settings Allow WebID registration (multi-user): true +2ms
  solid:settings Live-updates: true +0ms
  solid:settings Identity Provider: false +0ms
  solid:settings Default file browser app: https://linkeddata.github.io/warp/#/list/ +0ms
  solid:settings Default data browser app: true +0ms
  solid:settings Base URL (--mount): / +45ms
  solid:settings SSL Private Key path: ../localhost.key +1ms
  solid:settings SSL Certificate path: ../localhost.crt +0ms
Solid server (solid v2.3.0) running on https://localhost:8443/
Press <ctrl>+c to stop
  solid:idp Account on localhost is not available / +6s
  solid:authentication No client certificate found in the request. Did the user click on a cert? +53s
  solid:ACL Can an agent Append https://localhost:8443/accounts/new? +3ms
  solid:ACL Check if acl exist: https://localhost:8443/accounts/new.acl +5ms
  solid:ACL Error: HTTPError: Can't read file +4ms
  solid:ACL Check if acl exist: https://localhost:8443/accounts/.acl +0ms
  solid:ACL Error: HTTPError: Can't read file +1ms
  solid:ACL Check if acl exist: https://localhost:8443/.acl +0ms
  solid:ACL Error: HTTPError: Can't read file +1ms
  solid:ACL No ACL resource found - access not allowed +0ms
  solid:ACL Error: No Access Control Policy found +0ms
  solid:ACL Authentication required +0ms
  solid:server Error page because of Access to https://localhost:8443/accounts/new requires authorization +1ms
  solid:authentication No client certificate found in the request. Did the user click on a cert? +1s

In the FireFox Certificate Manager:
The Servers has a certificate name *.localhost:8443  for localhost:8443 and a lifetime of Temporary

Comments: Occasionally this Issue is solved when everything from the Certificate Manager is removed relating to localhost and the repository is deleted than cloned again from github. This (s the admin signup) has not worked recently. If it does, the certificate is not saved in the browser, which encourages creating and uploading a .p12 file in the certificate manager. See issue 356 when it exists.

**Comment by nicola** [comment]
This issue is pretty related to the same problem of #354, will leave open for investigation
