### ISSUE TITLE
Document discovering WebID from domain name

### ISSUE THREAD

**Issue by nicola** [solid/node-solid-server#359]
The webid is in the `.meta` and discovered via OPTIONS

**Comment by dmitrizagidulin** [comment]
From what I understand, this is implemented. Leaving this open as a reminder to document it.

**Comment by dmitrizagidulin** [comment]
Specifically, when an account is created, a triple gets added to the account's *root .meta* resource (e.g. `https://alice.databox2.com/.meta`) with the predicate `solid:account` and their WebID as the object (e.g. `https://alice.databox2.com/profile/card#me`).

`solid-client` has a helper method `discoverWebID(accountUrl)` that loads and parses the root `.meta` resource, and returns that account's WebID URI.
