### ISSUE TITLE
How should we handle ACLs for the meta document?

### ISSUE THREAD

**Issue by deiu** [solid/node-solid-server#368]
`/foo/bar.png` may have an ACL at `/foo/bar.png.acl`, but where should the ACLs for its corresponding meta live? Is it in `/foo/bar.png.meta.acl` or is it the same as `/foo/bar.png.acl`?

**Comment by dmitrizagidulin** [comment]
Did we resolve this question, or is it still under discussion?

**Comment by deiu** [comment]
We have currently resolved it by just adding the `.acl` suffix to the meta file -- i.e. `/foo/bar.png.meta.acl`.

**Comment by dmitrizagidulin** [comment]
Thanks!

**Comment by dmitrizagidulin** [comment]
@deiu if a `.meta` for `resource1.tts` *doesn't* have its own `.acl`, does it then default to `resource1.ttl.acl`? Or to the parent/inherited acl?

**Comment by deiu** [comment]
It currently defaults to the inherited acl, like any other resource.
