### ISSUE TITLE
Move default webid from /profile/card to /.meta

### ISSUE THREAD

**Issue by nicola** [solid/node-solid-server#370]
So that the WebID is served on root

**Comment by dmitrizagidulin** [comment]
What does the WebID URL look like, then? `https://nicola.databox.me/.meta#me`?

**Comment by nicola** [comment]
https://nicola.databox.me/#me

**Comment by dmitrizagidulin** [comment]
Ohh I see.

**Comment by dmitrizagidulin** [comment]
+1 to this, I think this is a great idea.

**Comment by RubenVerborgh** [comment]
This is not necessarily a good idea; needs more discussion.
