### ISSUE TITLE
Empty POST to /api/accounts/new should fail in Multi User/--idp mode

### ISSUE THREAD

**Issue by dmitrizagidulin** [solid/node-solid-server#375]
If you launch solid-server in `--idp` mode, an empty post (with no username) to `/api/accounts/new` should fail with a 400 (with the error message `Username required`)
Currently fails with `Account already exists`

**Comment by nicola** [comment]
I rephrase the question in this way:

Should the user create a new account by doing a POST on:

- POST https://databox.com/api/accounts/new {username: 'nicola'}
- https://nicola.databox.com/api/accounts/new (no username needed to be passed)

?

The second is a sort of a claim of a url (also this is what we have done so far)

**Comment by dmitrizagidulin** [comment]
I'm not sure I'm understanding that second option. What http verb is that, still a post?

**Comment by nicola** [comment]
yes!

**Comment by dmitrizagidulin** [comment]
Ohhhh I see!

**Comment by dmitrizagidulin** [comment]
Yeah, that seems reasonable. We should differentiate between those two use cases (and not require usernames in the second case)

**Comment by dmitrizagidulin** [comment]
After further discussion with @nicola, we agree that we currently don't need the concept of usernames. Closing this issue.
