### ISSUE TITLE
GET on an inherited .acl resource should return the "parent" authorization rules

### ISSUE THREAD

**Issue by dmitrizagidulin** [solid/node-solid-server#379]
Per our conversation with @deiu and @ghanemabdo at the WWW Conference.

Context:
There's a container, say `/posts/` that has an `.acl` resource, `/posts/.acl` with a `defaultForNew` statement in it. (Sidenote - we're still planning to rename that predicate to just `default`.) 
Inside the container, the individual resources do not have their own ACLs, they just inherit the container's.

Current behavior:
A GET on an individual post's ACL resource (GET `/posts/post1.ttl.acl`) yields a 404.

Needed behavior:
A GET on an individual post's ACL needs to return the authorization statements (minus the `defaultForNew`) of whatever parent `.acl` it's inheriting from (so, in this case, return the contents of `/posts/.acl`).

**Comment by dmitrizagidulin** [comment]
Semi-blocker for the solid.js Permissions functionality.

**Comment by ghanemabdo** [comment]
What we do need is a way to let Solid servers return the url of the actual acl resource (maybe of one of resource's parents) which contains the acls for the requested resource.

So, the server's behavoir with `HEAD` requests on `/posts/post1.ttl` with acl header should be:
1- if `/posts/post1.ttl.acl` exists => return its content
2- if not, return the `url` of the nearest parent having acl authorizations that contains `default` predicate. In this case it's `/posts/.acl`

Because otherwise, to retrieve the acl authorization for a resource, the client should make a series of `HEAD` requests on the resource and up its parents till it hits an existing individual `.acl` resource which is totally inefficient.

**Comment by nicola** [comment]
Agreed, we need dynamic ACL on GET and futher patches/put should create the file based on this dynamically generated ACL

**Comment by dmitrizagidulin** [comment]
No, we've agreed that the best way to proceed was for the server to return the /contents/ of the parent acl, not the url for it, remember. (@deiu can back me up on this)
The client /should not/ perform the multiple hops. (would even say must not)

**Comment by deiu** [comment]
Yes, it's pretty much the same workflow we have now for checking parent ACLs.

**Comment by ghanemabdo** [comment]
Why do we need to retrieve the content of the parent acl not the acl url and the client do GET on this url? is there any security issues with the url?

**Comment by mediaprophet** [comment]
What about search indexing?

**Comment by dmitrizagidulin** [comment]
@ghanemabdo - there are a couple of reasons for it. 
The main one is - there are a bunch of statements in a container's acl file that do not apply to an inherited resource. The inherited acl only cares about statements that contain 'defaultForNew'. The client should not be filtering those out, browser side.

@mediaprophet - what do you mean, re search indexing?

**Comment by ghanemabdo** [comment]
@dmitrizagidulin understood. This means Doing `GET` on any individual resource will never trigger 404 not found and the server will return either the content of the individual acl resource or the authorizations having `default` from one of the parents. This means `HEAD` requests on a resource always returns the url of the individual acl resource. 
The question ... Does this mean there is no way to know whether a resource has an individual acl resource or its permissions are inherited?

**Comment by dmitrizagidulin** [comment]
@ghanemabdo ah, that's an interesting question. 
In what sort of usecases would it be useful to distinguish between individual .acl or inherited?
