### ISSUE TITLE
Implement ldp:DirectContainer

### ISSUE THREAD

**Issue by csarven** [solid/node-solid-server#399]
Handle `ldp:DirectContainer` resources and its members.

**Comment by elf-pavlik** [comment]
looks like this line assumes `ldp:BasicContainer` https://github.com/solid/node-solid-server/blob/f2a420217b6114b0bf48803975cf29800d3ea8d8/lib/handlers/post.js#L89

does anyone object to modifing it in a way that besides `ldp:DirectContainer` it would later also work with `ldp:IndirectContainer` ?
