### ISSUE TITLE
Accept-Patch HTTP header

### ISSUE THREAD

**Issue by csarven** [solid/node-solid-server#410]
`Accept-Patch` is *missing in action* for HTTP OPTIONS

**Comment by dmitrizagidulin** [comment]
(see PR https://github.com/solid/node-solid-server/pull/411 for reference)

**Comment by dmitrizagidulin** [comment]
Per @csarven, the value of the header, the content type should be `application/sparql*`

**Comment by dmitrizagidulin** [comment]
Let's go with returning the value `application/sparql-update` initially.

**Comment by deiu** [comment]
It should be `application/sparql-update` since it's the only one we officially support.

**Comment by dan-f** [comment]
sounds good. still diving through the code, but I'll ping you guys when I have a PR

**Comment by dan-f** [comment]
PR is up - #418

**Comment by dmitrizagidulin** [comment]
PR is merged, closing this issue.
