### ISSUE TITLE
Support XML Patch

### ISSUE THREAD

**Issue by csarven** [solid/node-solid-server#414]
Using an implementation of http://tools.ietf.org/html/rfc7351 and https://tools.ietf.org/html/rfc5261 is one way to get HTTP PATCH working for text/html and application/xhtml+xml (essentially for HTML+RDFa). When this is implemented, `application/xml-patch+xml` should appear in Accept-Patch. See also: https://github.com/solid/node-solid-server/issues/410

**Comment by csarven** [comment]
@RubenVerborgh Would you mind reopening this?

Some documentation on why it is deemed to be a feature would be useful. application/sparql-update wasn't a feature as I recall it - in fact, it was literally made-up for something to work for PATCH. It'd be great to make PATCH work for any RDF syntax.

What's the ETA on "revisit"?

**Comment by RubenVerborgh** [comment]
> What's the ETA on "revisit"?

That's up to the community. If someone wants to invest resources in this, let's reopen to indicate this issue is active.

For now, it is on "revisit" (= "paused") state because we have no one working on this.

**Comment by RubenVerborgh** [comment]
We're using it differently indeed, hence the "revisit" label.

We (= maintainers of his repo) didn't think it was meaningful to leave issues open that we cannot realistically get to within 6 months. That way, all the "open" issues reflect current problems and current work.

If anyone wants to get to those issues sooner, please do, that would be awesome.
