### ISSUE TITLE
Remove extra 'BasicContainer' link header

### ISSUE THREAD

**Issue by dmitrizagidulin** [solid/node-solid-server#426]
When creating a container via POST, the 201 Created response header contains an extra `BasicContainer` type link header. Specifically:

`Link: <.acl>; rel="acl", <.meta>; rel="describedBy", <http://www.w3.org/ns/ldp#Container>; rel="type", <http://www.w3.org/ns/ldp#BasicContainer>; rel="type", <http://www.w3.org/ns/ldp#BasicContainer>; rel="type"`

Remove the second one.

**Comment by csarven** [comment]
I'd suspect that this is a relatively minor or non-issue for a client. Any particular reason why this issue doesn't have "good first issue" label?
