### ISSUE TITLE
Web-DHT Support

### ISSUE THREAD

**Issue by ghost** [solid/node-solid-server#429]
support for WebDHT [1] might solve alot of problems..

[1] https://www.npmjs.com/package/did-io

**Comment by mediaprophet** [comment]
IMHO; an implementation method might be that core identifiers can be distributed within a social-group, which may transit multiple Node.solid.servers...  

therein, the attack-vectors become far more complex if seeking to eradicate an identity.

This needs to be further considered; however the principle is that WebDHT doesn't need a large file that's akin to DNS - but rather, one that incorporates other principles [2]
[2] https://www.w3.org/DesignIssues/CloudStorage.html

**Comment by dmitrizagidulin** [comment]
Very possible. We do have fans of WebDHT-like technologies (including IPFS) on the dev team.

What sort of problems do you see it solving, though?

**Comment by mediaprophet** [comment]
a number of issues... 

The key considerations are around what i consider a 'human centric web' as a quality of these sorts of works, or an alternative and perhaps optional deployment of them. 

it is very easy to demonstrate other 'credentials' related technologies / methodologies, that are moreover federated.  It is far more difficult to demonstrate an alternative that is 'human centric' or decentralised in nature. 

I also do not like the computational payload/respondence/reliance of Blockchain based tech.  I appreciate, with great esteem the work of @melvincarvalho however also believe it may be adapted to other alternatives that are more 'human centric'.

computers are tools.  Timbl mentioned at least once, that 'bots' started with companies.

the world is 'human centric'. 

 i think we should provide that possible alternative, and i think the data-storage requirements of it, shouldn't be overly burdensome.

**Comment by mediaprophet** [comment]
I think the root identifiers for the author strategy could be decentralised
across the social-group of friends using either ipfs or web-dht.

May also support decentralised backup for other objects, and, perhaps
support some form of CDN logic with a little more thought.

Web-DHT seems like an easier way to assert distribution rules / semantics.

Haven't looked into IPFS enough yet...  I hear it's celebrated in a manner
Web-DHT is not; yet more over, time to market seems most important.

Principle consideration is an alternative to blockchain that help ensure
humans cannot be deleted or fenced into a non-functional state, as the
basic / lower levels.

**Comment by mediaprophet** [comment]
I've done some more investigation.  Conversation in Creds: https://lists.w3.org/Archives/Public/public-credentials/2016Sep/0003.html noted Web-DHT being Dropped; which left the consideration to IPFS. 

independently; the comment from a well-known guru was "I am in contact with the IPFS folks with regard to digital archiving and preservation"
