### ISSUE TITLE
--no-webid doesn't work?

### ISSUE THREAD

**Issue by SvenDowideit** [solid/node-solid-server#433]
```
root@7a97f621b985:/solid# 
root@7a97f621b985:/solid# 
root@7a97f621b985:/solid# /usr/local/bin/solid start --no-webid

  error: unknown option `--no-webid'

root@7a97f621b985:/solid# /usr/local/bin/solid start --help

  Usage: start [options]

  run the Solid server

  Options:

    -h, --help                 output usage information
    --root [value]             Root folder to serve (defaut: './')
    --port [value]             SSL port to use
    --webid                    Enable WebID+TLS authentication (use `--no-webid` for HTTP instead of HTTPS)
    --auth [value]             Pick an authentication strategy for WebID: `tls` or `oidc`
```

**Comment by timbl** [comment]
I found this problem too.    The command line parsing seems to have rotted a bit.  You can put   "webid": false,  in the config.json file.

**Comment by melvincarvalho** [comment]
I think the line is here:

https://github.com/solid/node-solid-server/blob/master/bin/lib/options.js#L26

Resolution is to remove the text `(use `--no-webid` for HTTP instead of HTTPS)` and write something more helpful

```JavaScript
  {
    name: 'webid',
    help: 'Enable WebID+TLS authentication (use `--no-webid` for HTTP instead of HTTPS)',
    flag: true,
    question: 'Enable WebID authentication',
    prompt: true
  }
```

**Comment by dmitrizagidulin** [comment]
This should be fixed in the latest commit. Closing.

**Comment by kjetilk** [comment]
Hmmm, indeed.

AFAICS, there hasn't been any changes in that since the dawn of ages:
https://github.com/solid/node-solid-server/blame/master/bin/lib/start.js#L71
But I don't know the entire history here, so I'll reopen in case someone who does can comment.

**Comment by michielbdejong** [comment]
Looks like this was never implemented, even if the readme does mention it. There is a `webid: false` config option, so we should check if that one works correctly.
