### ISSUE TITLE
ProxyPath is not defined

### ISSUE THREAD

**Issue by melvincarvalho** [solid/node-solid-server#437]
Noticed by @timbl in https://gitter.im/solid/node-solid-server?at=57c48c74ca24c06c63849a8a

I also experienced this issue.

It appears to be from the static/databrowser.html file.

https://github.com/solid/node-solid-server/blob/master/static/databrowser.html#L8

**Comment by timbl** [comment]
The databrowser could do with a update to use the newer mashlib and host scripts and CSS from github.io instead of scripts.mit.edu I think

**Comment by melvincarvalho** [comment]
I think this is now fixed, closing.
