### ISSUE TITLE
suggestion: default ACL origin for fileBrowser

### ISSUE THREAD

**Issue by chrysn** [solid/node-solid-server#439]
in first tests with node-solid-server, i had to disable strictOrigin until i manually inserted an `<#owner> acl:origin <https://linkeddata.github.io>` statement into the default acl.

as the acl file appears to be generated by the server, would it be reasonable to put the (path stripped) fileBrowser in the accepted origins list by default? otherwise, the combination of strictOrigin and fileBrowser seems rather pointless.

**Comment by dmitrizagidulin** [comment]
@chrysn ahh, good point! Thank for the catch.
