### ISSUE TITLE
Range header not yet supported in ldp GET

### ISSUE THREAD

**Issue by melvincarvalho** [solid/node-solid-server#442]
The default html5 video player allows skipping back and forth through a video file.  The method for doing this is to send a "range" header.  

This is yet not supported in node solid server and would allow a better experience for those that choose to store video on the cloud.

One possible solution is to use the following javascript or something similar

``` JavaScript
  if (req.headers['range']) {
    var range = req.headers.range;
    var parts = range.replace(/bytes=/, "").split("-");
    var partialstart = parts[0];
    var partialend = parts[1];

    var start = parseInt(partialstart, 10);
    var end = partialend ? parseInt(partialend, 10) : total-1;
    var chunksize = (end-start)+1;
    console.log('RANGE: ' + start + ' - ' + end + ' = ' + chunksize);

    var file = fs.createReadStream(path, {start: start, end: end});
    res.writeHead(206, { 'Content-Range': 'bytes ' + start + '-' + end + '/' + total, 'Accept-Ranges': 'bytes', 'Content-Length': chunksize, 'Content-Type': 'video/mp4' });
    file.pipe(res);
  } 
```

Taken from:

https://gist.github.com/paolorossi/1993068

**Comment by timbl** [comment]
Closed by https://github.com/solid/node-solid-server/pull/466
