### ISSUE TITLE
Implement ldp:constrainedBy

### ISSUE THREAD

**Issue by csarven** [solid/node-solid-server#444]
https://www.w3.org/TR/ldp/#ldpr-gen-pubclireqs

**Comment by dmitrizagidulin** [comment]
Can you be more specific here? The paragraph that you link to doesn't actually explain what constraints are.

**Comment by csarven** [comment]
Here is another take: https://linkedresearch.org/ldn/#constraints

**Comment by dmitrizagidulin** [comment]
Thanks. That one is slightly more descriptive. Which constraints would you like to be implemented, though? SHACL based ones, or Web Annotation ones?

**Comment by csarven** [comment]
I was essentially referring to a validator that the server can run the payload through before having it reaching the disk. If a resource advertises a constraint, it should be able to verify. With SHACL, arbitrary data can be checked to see if it matches some constraints. Web Annotation happens to be just one which is left to each implementation. I'd like suggest to go for SHACL since solid-server is relatively agnostic about how resources are modelled and described.

**Comment by dmitrizagidulin** [comment]
@csarven The main difficulty with implementing this feature is that there doesn't seem to be a usable SHACL library for javascript. (At least, I couldn't find one - if you can link me to one, that'd be great). 
I'll leave the issue open, until somebody implements one of those.

**Comment by csarven** [comment]
Just a note for anyone looking into this or considering in the future: the entity at the end of `ldp:constrainedBy` doesn't have to conform to a particular specification (at this point in time). It can be application specific, or it can be in a general form like SHACL or ShEx.

Perhaps what's really required by the system is a way to advertise that a constrained exists, i.e., via a resource having a `Link` header with `ldp:constrainedBy` or in the RDF body.

**Comment by dduran1967** [comment]
@csarven - agreed and fyi - we're planning to do this with json-schema resources shortly...

**Comment by simonstey** [comment]
> The main difficulty with implementing this feature is that there doesn't seem to be a usable SHACL library for javascript. (At least, I couldn't find one - if you can link me to one, that'd be great).
I'll leave the issue open, until somebody implements one of those.

@dmitrizagidulin fwiw, [SHACL Playground - A constraint validator for SHACL written in JavaScript.](http://shacl.org/playground/) based on [SHACL JavaScript Extensions](http://w3c.github.io/data-shapes/shacl-js/)

**Comment by elf-pavlik** [comment]
ShEx has list of open source implementations on https://www.w3.org/2001/sw/wiki/ShEx#Implementations shex.js has MIT license

I'd really like to see SHACL & ShEx comparisons published by both groups developing them.
