### ISSUE TITLE
Return the Content-Type of resources in container list data

### ISSUE THREAD

**Issue by timbl** [solid/node-solid-server#446]
It would be great if, along with the normal LDP container listing data, a solid server returned for each file (or directory) in the container, its MIME type as an RDF type.  
- It allows me to spot which folders should be thought of as slide shows without cheating and looking at the file extensions on the URIs
- It allows a file listing to use appropriate icons, colors, etc
- It allows code which runs recursively over a directory tree can be much faster without having to do a HEAD on each thing

(I suggest that Internet Content Types be mapped onto https: space, possibly https://www.w3.org/ns/mime/image/png and some support for it be made by adding data about the mime types derived from the MIME type XML file at IANA.  An alternative is to use a base URI in iana space which will not be supported with RDF)

**Comment by dmitrizagidulin** [comment]
This is a great idea! Couple of questions:

1. What's the MIME type of a directory?
2. What's the predicate that should be used?
3. Is it important that the object be a URI? (What about returning MIME types as literals?)

**Comment by timbl** [comment]
1. Just return the RDF type of an LDP container
2. rdf:type
3. Yes  I think so ...

The reason that we use an actual RDF class is because we can then use the RDFs tools.   We can add for example the in the ontology that image/png is a rdfs:subClassOf dc:Image 
The type arc is how we say that something is in a category in RDF traditionally.
The UI stack and the solid core already have a type index, so once could immediately use that to put a particular type of file in, like a spreadsheet or a PDF file, and we can use the app/type registry for a user to select how she will deal with a given mime type.

**Comment by dmitrizagidulin** [comment]
Got it, makes sense.

**Comment by dmitrizagidulin** [comment]
Wait, re number 1, isn't that mixing RDF Types and MIME Types? To put it another way, 'LDPResource' isn't a mime type..

**Comment by timbl** [comment]
Because we use rdf:type, and mapping the mime types into RDF types, then one benefit we have is we mix them.

**Comment by dmitrizagidulin** [comment]
Ah, makes sense. :)

**Comment by timbl** [comment]
Ok, so went out on a limb in https://github.com/solid/node-solid-server/pull/456 and decided on an arbitrary mapping for that to map Media Type

image/jpeg

to the class

http://www.w3.org/ns/iana/media-types/image/jpeg#Resource

```
@prefix terms: <http://purl.org/dc/terms/>.
@prefix XML: <http://www.w3.org/2001/XMLSchema#>.
@prefix ldp: <http://www.w3.org/ns/ldp#>.
@prefix st: <http://www.w3.org/ns/posix/stat#>.
@prefix jpeg: <http://www.w3.org/ns/iana/media-types/image/jpeg#>.
...
<cam-012758.jpg>
    terms:modified
       "2016-11-06T20:40:53Z"^^XML:dateTime;
    a    jpeg:Resource, ldp:Resource;
    st:mtime
       1478464853;
    st:size
       35647.

```

**Comment by dmitrizagidulin** [comment]
Implemented & merged, closing.
