### ISSUE TITLE
Server crashes due to unhandled error during specific PATCH requests.

### ISSUE THREAD

**Issue by Exulansis** [solid/node-solid-server#448]
To reproduce: 

Have an instance of the Solid server running and create a file containing some test tripple, for instance:

```
<https://bob.de/profile/card#me> <http://xmlns.com/foaf/0.1/knows> <https://alice.de/profile/card#me>.
```

Now we can send a PATCH request with the SPARQL query: 

```
DELETE DATA { <https://bob.de/profile/card#me> <http://xmlns.com/foaf/0.1/knows> <https://alice.de/profile/card#me> .};
```

This works as expected.

The following request: 

```
DELETE DATA { <https://malice.de/profile/card#me> <http://xmlns.com/foaf/0.1/knows> <https://alice.de/profile/card#me> .};
```

Returns an error. This is expected behaviour, since the function `applyPatch`, defined in [RDFLIB,](https://github.com/linkeddata/rdflib.js/blob/master/src/indexed-formula.js#L94) does check first if the triple exists, before attempting to remove it. As a result of that, supplying a non existent tripple will be handled correctly.

The problem occures when we supply a query containing the same, valid triple, repeated twice:

```
DELETE DATA {
<https://bob.de/profile/card#me> <http://xmlns.com/foaf/0.1/knows> <https://alice.de/profile/card#me> .  
<https://bob.de/profile/card#me> <http://xmlns.com/foaf/0.1/knows> <https://alice.de/profile/card#me> . 
};
```

This crashes the server, producing the following stack trace: 

```
/node-solid-server/node_modules/rdflib/src/indexed-formula.js:511
      throw new Error('Statement to be removed is not on store: ' + st)
      ^

Error: Statement to be removed is not on store: <https://bob.de/profile/card#me> <http://xmlns.com/foaf/0.1/knows> <https://alice.de/profile/card#me> .
    at IndexedFormula.remove (/node-solid-server/node_modules/rdflib/src/indexed-formula.js:511:13)
    at /node-solid-server/node_modules/rdflib/src/indexed-formula.js:120:20
    at Array.map (native)
    at doPatch (/node-solid-server/node_modules/rdflib/src/indexed-formula.js:119:13)
    at IndexedFormula.applyPatch (/node-solid-server/node_modules/rdflib/src/indexed-formula.js:162:7)
    at /node-solid-server/lib/handlers/patch.js:177:18
    at tryToString (fs.js:449:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:436:12)
```

Just like in the previous example, the `applyPatch` function checks if the tripples exist before attempting to remove them. In this case, both triples exist, therefore the check is passed without any issues. But after the first triple is removed, the server attempts to remove the same tripple again, for the second time, causing a crash.

**Comment by dmitrizagidulin** [comment]
Great catch, thanks for reporting!

**Comment by dmitrizagidulin** [comment]
@timbl - Do you know if this issue is fixed by your latest fix to rdflib?
