### ISSUE TITLE
Making index.ttl#this a assumed subject of a folder as a server-side  convention

### ISSUE THREAD

**Issue by timbl** [solid/node-solid-server#452]
We use the server-side convention that, when a human browser asks for a directory, if there is an index.html file in the directory, then we send that file, as if you like a representation of the folder which the publisher wants to use.

I find a common form of index.html for me is one which loads index.ttl and  then runs the default data bowser for index.ttl#this 

Suppose we make index.ttl#this a thing, just like index.html.  That is, the server, if the client is looking for HTML, and there is not index.html but there is an index.ttl,  it fabricates the appropriate index.html on the fly. 

When a data-capable thing like a file browser pulls the same directory, and is getting turtle, and there is an index.ttl, then the server could add to the data a triple to indicate that the main subject of the folder is ./index.ttl#this, and maybe pass on the types of thing whichindex.ttl#this is given in that file -- producing a similar result.  In this case it would be up to the file bowser (etc) to decide how to display/interact with etc ./index.ttl#this

**Comment by mediaprophet** [comment]
https://lists.w3.org/Archives/Public/public-rww/2016Oct/0009.html 

.bot isn't the point; yet, is it important to pick ttl over other serialisation formats?

**Comment by timbl** [comment]
Actually the proposal was to make it a thing but NOT just like index.html.

Send all the notmal contents of the folder, plus just tye type arcs in index.html about <#this>.

`<index.ttl#this> a ?type`
