### ISSUE TITLE
Allow video skip with Accept-Ranges: bytes ?

### ISSUE THREAD

**Issue by timbl** [solid/node-solid-server#457]
I notice that an HTML5 video clip hosted from this server does not allow skipping forwards.    (Whereas Youtub.com for example does).   Is the problem just that the server does not do the
```
Accept-Ranges: bytes
```
protocol?  

Could that be added from an existing express module?

It could be done just for video, to avoid interaction with things happen with turtle, etc, where byte ranges are not needed.

Of course solid' main goal is serving data, but serving everything in a person's life too is important

**Comment by timbl** [comment]
See https://tools.ietf.org/html/rfc7233#section-2.3

**Comment by timbl** [comment]
Maybe see
https://www.npmjs.com/package/express-range
and maybe
https://delog.wordpress.com/2011/04/25/stream-webm-file-to-chrome-using-node-js/
https://github.com/meloncholy/vid-streamer
etc

**Comment by melvincarvalho** [comment]
Need to implement HTTP 206

I raised this in 

https://github.com/solid/node-solid-server/issues/442

Having experimented with the code snippet there, it does work with node solid server.  I host my videos on a custom version of node solid server and can watch them at home or remotely, from any device.

See: https://gist.github.com/paolorossi/1993068

**Comment by melvincarvalho** [comment]
```JavaScript
var http = require('http'),
    fs = require('fs'),
    util = require('util');

http.createServer(function (req, res) {
  var path = 'video.mp4';
  var stat = fs.statSync(path);
  var total = stat.size;
  if (req.headers['range']) {
    var range = req.headers.range;
    var parts = range.replace(/bytes=/, "").split("-");
    var partialstart = parts[0];
    var partialend = parts[1];

    var start = parseInt(partialstart, 10);
    var end = partialend ? parseInt(partialend, 10) : total-1;
    var chunksize = (end-start)+1;
    console.log('RANGE: ' + start + ' - ' + end + ' = ' + chunksize);

    var file = fs.createReadStream(path, {start: start, end: end});
    res.writeHead(206, { 'Content-Range': 'bytes ' + start + '-' + end + '/' + total, 'Accept-Ranges': 'bytes', 'Content-Length': chunksize, 'Content-Type': 'video/mp4' });
    file.pipe(res);
  } else {
    console.log('ALL: ' + total);
    res.writeHead(200, { 'Content-Length': total, 'Content-Type': 'video/mp4' });
    fs.createReadStream(path).pipe(res);
  }
}).listen(1337, '127.0.0.1');
console.log('Server running at http://127.0.0.1:1337/');
```

**Comment by melvincarvalho** [comment]
What is needed is to change the get handler to appreciate the range header

https://github.com/solid/node-solid-server/blob/master/lib/handlers/get.js#L50

```JavaScript
ldp.get(req.hostname, path, baseUri, includeBody, possibleRDFType, function (err, stream, contentType, container) {
```
Unfortunately the signature of ldp.get does not currently pass in the header, so either there needs to be a change in ldp.get (I dont know if this would break something) or a new function, say, getRange, which sends in either the range header, or all the headers.

Then the return value should contain the return code 206 in addition to the stream
```JavaScript
function (err, stream, contentType, container)
```
Although, I suppose the handler may be able to guess the HTTP code based on whether the range header is set

**Comment by melvincarvalho** [comment]
The following patch should fix this issue, and allow video to stream and skip

You can give it a try with 

    git apply <file>

[video-patch.txt](https://github.com/solid/node-solid-server/files/629665/video-patch.txt)
