### ISSUE TITLE
solid:get no translation text/turtle meaning

### ISSUE THREAD

**Issue by bshambaugh** [solid/node-solid-server#458]
When solid is enabled with the verbose option, I get the response "solid:get no translation text/turtle" .  I am not certain what this means.

**Comment by melvincarvalho** [comment]
This is just a debug line from : 

https://github.com/solid/node-solid-server/blob/3c8b7a6282dec418be40b2083d122a052af7c7c0/lib/handlers/get.js#L92

It is not an error.  I get this all the time.

**Comment by melvincarvalho** [comment]
> from @timbl 
solid:get no translation text/turtle means “Hey I’ll just send a response to this GET as text/turtle, I don’t need to translate anything betweeen languages"
Sorry it looks a bit like “Error: no translation found” but it isn’t it is “Info: no translation necessary"
Suggest change the log message to say “no translation necessary” in fact

https://gitter.im/solid/node-solid-server?at=5841ed270da034021b5ed899
