### ISSUE TITLE
MIT Hack Day

### ISSUE THREAD

**Issue by bshambaugh** [solid/node-solid-server#459]
Request to show up at the 5th floor office at the Stata Center and debug and install node-solid-server this week or next.

**Comment by dmitrizagidulin** [comment]
@bshambaugh Hi Brent. These past few weeks have been pretty hectic for us. Would a skype or screen hero call help?

**Comment by bshambaugh** [comment]
@dmitrizagidulin Skype could help, but it may not be until January. I'm working to get my ducks in a row applying for a grant of sorts. Unfortunately, I'm juggling both! Much thanks.

**Comment by dmitrizagidulin** [comment]
Closing this; feel free to contact us on Gitter.
