### ISSUE TITLE
on-behalf-of header crashes server

### ISSUE THREAD

**Issue by melvincarvalho** [solid/node-solid-server#473]
When using WebID delegation, the on-behalf-of header is sent by the user agent.  Currently this will crash node solid server.

It would be better to throw an error message, and keep the server running, or fix the delegation code in allow.js 

https://github.com/solid/node-solid-server/blob/master/lib/handlers/allow.js

The root problem lies in the function : 

    function verifyDelegator (host, ldp, baseUri, delegator, delegatee, callback) {

Which takes 6 parameters.  It is being called 

    verifyDelegator(req.hostname, delegator, req.session.userId, function

With only 4 parameters.  Meaning that the callback is sent instead of the delegate URI.  And the string function on the callback will throw an exception.

@dmitrizagidulin any ideas on what the logic *should* be here?

**Comment by dmitrizagidulin** [comment]
@melvincarvalho I'm not sure what the correct logic should be. Maybe @deiu can take a look?

**Comment by dmitrizagidulin** [comment]
Taking a look at this.

**Comment by dmitrizagidulin** [comment]
Fixed by PR #487. (WebID Delegation is currently not fully implemented in the server, but will be implemented by PR #475.) Closing.
