### ISSUE TITLE
Support the Memento protocol

### ISSUE THREAD

**Issue by csarven** [solid/node-solid-server#478]
http://mementoweb.org/guide/howto/

>The Memento protocol is closely aligned with a common resource versioning pattern that consists of:
>* Having a generic URI where at any moment in time the current version of the resource is accessible. The Memento protocol refers to the resource identified by the generic URI as the original resource.
>* Having a dedicated version URI for each resource version. The Memento protocol refers to a resource identified by a version URI as a Memento.

...

>This document describes, from simple to more complex, the ways in which a system that hosts resource versions can support the Memento framework by:
>* Providing HTTP response headers for resource versions to convey version date and links
>* Publishing a TimeMap, a list of versions of a resource
>* Exposing a TimeGate that supports datetime negotiation to access resource versions

**Comment by dmitrizagidulin** [comment]
👍 , good idea. The Memento protocol has been on our radar for a while. 

(I'm working on a refactoring of solid-server's LDP class, to have it work with arbitrary/pluggable backends (file system, quad store, etc). This is basically a pre-requisite for a lot of these advanced features - versioning/Memento, querying, and so on.)

**Comment by dmitrizagidulin** [comment]
Incidentally, supporting something like the Memento protocol (especially for binaries, where keeping efficient diffs is not always possible) would make being able to measure user bandwidth (and set quotas/limits) even more important for multi-user Solid installations.

**Comment by hvdsomp** [comment]
Great to see interest in Memento! I would like to mention that Fedora Commons is currently working on supporting LDP augmented with access to LDPR versions using the Memento protocol (TimeGates for datetime negotiation as well as TimeMaps for version lists). There is an API spec at http://fcrepo.github.io/fcrepo-specification/ and also some discussion at https://github.com/fcrepo/fcrepo-specification/issues/12 .

**Comment by dmitrizagidulin** [comment]
@hvdsomp Nice! Thanks for the heads up, and spec links. 
(Are you part of the LDP Next group, btw? If yes, we should bring it up on in the discussions there, if it hasn't been already.)

**Comment by elf-pavlik** [comment]
LDF server [has support for memento](https://github.com/LinkedDataFragments/Server.js/wiki/Configuring-Memento) but as I understand it only supports release based versioning of dataset and not datasets with 'rolling' updates https://ruben.verborgh.org/blog/2016/06/22/querying-history-with-linked-data/
@RubenVerborgh can correct me here...

**Comment by RubenVerborgh** [comment]
@elf-pavlik I'd say a “rolling” update is just a very small version, so it can surely work. It's just going to be more bookkeeping at the server side, but if the server knows when every update was made… sure.

**Comment by csarven** [comment]
Related to this issue is https://github.com/solid/node-solid-server/issues/611 and allowing the client to use `rel="timegate"` and `rel="original"` in the `Link` header.
