### ISSUE TITLE
Ship with default 401, 404 and 500 error pages

### ISSUE THREAD

**Issue by dmitrizagidulin** [solid/node-solid-server#480]
We do not provide any sort of error pages at the moment, and instead do just a bare 'Can't find file requested' text message, or a stack trace.

It would make for a better initial developer experience (not to mention users of databox2 etc) if we had simple error pages, with explanations, links to github issues, etc.

**Comment by dmitrizagidulin** [comment]
See also [issue #485-Install default apps in the 'solid init' step](https://github.com/solid/node-solid-server/issues/485)

**Comment by melvincarvalho** [comment]
see [chatlogs](https://gitter.im/solid/node-solid-server?at=5a7c4b4186ef1bb14183f04c)
