### ISSUE TITLE
Remove 'mount' config option

### ISSUE THREAD

**Issue by dmitrizagidulin** [solid/node-solid-server#493]
Currently, the `--mount` solid server config option allows for serving Solid from a "subpath" url. For example, if solid-server normally serves requests on `https://example.com/`, if you pass it `--mount solid`, then it would serve requests on `https://example.com/solid/`. 

This is separate from the `--root` config parameter: `root` has to do with a directory on the server, and `mount` has to do with a url subpath.

**Proposal:** remove the `--mount` option from solid-server.

Removing this option would significantly simplify internal URL-calculating code for various API mount points. In multi-user (idp) mode, the `mount` parameter's behavior is undefined/un-implemented anyway. And in single-user mode, which url path a server listens on is a concern for whatever web server (Nginx, Apache, etc) is serving as a front end to Solid.

**Comment by dr0i** [comment]
The `--mount` config option definetely confused me, see #635. So +1 for removing this option.

**Comment by kellyprankin** [comment]
Seems simple enough. I could take a crack at removing it. Not sure how things work around here yet as I am new.  Who needs to approve?

**Comment by dmitrizagidulin** [comment]
@kellyprankin sure, that seems like a decent task. Go ahead and submit a PR.
