### ISSUE TITLE
Redirect loop on initial account creation in single-user mode

### ISSUE THREAD

**Issue by dmitrizagidulin** [solid/node-solid-server#498]
Redirection to `/signup.html` is causing a redirect loop.

**Comment by Kedrigern** [comment]
Same problem.

**Comment by dmitrizagidulin** [comment]
@Kedrigern - thanks! Can you try applying the fix in PR #499? (let me know if you have any other questions).

**Comment by Kedrigern** [comment]
In ts PR #499 I get "Access to https://localhost:8443/signup.html requires authorization"

**Comment by dmitrizagidulin** [comment]
@Kedrigern and are you running the server from a global npm install, or from a cloned repo?
(I think this is the same global install issue somebody else was picking up on, that the tests aren't hitting)

**Comment by dmitrizagidulin** [comment]
@Kedrigern I just pushed a patch to the `fix-single-user-signup` branch - let me know if that doesn't address the signup page.

**Comment by dmitrizagidulin** [comment]
Fixed in PR #499, closing.
