### ISSUE TITLE
what base to use when serialising a glob?

### ISSUE THREAD

**Issue by webr3** [solid/node-solid-server#502]
Currently the `globHandler` at https://github.com/solid/node-solid-server/blob/master/lib/handlers/get.js#L179 sends no `target` and no `base` to the rdflib.js serialize function, which expects one of the two to be set.

Is the error:

1. rdflib expecting a base, or
2. globHandler should provide a base

perhaps that before the `*` in `path/file*.rdf`?

**Comment by dmitrizagidulin** [comment]
From what I understand, rdflib.serialize() expecting a base url is intentional. (There's been deprecation warnings for a few versions.) 

So, I suspect the fix should be to attempt and provide a base.
