### ISSUE TITLE
Incorporate TLS renegotiation

### ISSUE THREAD

**Issue by csarven** [solid/node-solid-server#522]
Currently TLS connection is forced for all requests, hence the client has to provide their certificate before anything else happens. For resources with a public read policy, this forces an undesirable UX through user's Web browser, i.e., the cert prompt [1]. An alternative behaviour would be to not bother the user if the resource is public read. For that to happen, TLS renegotiation [2] needs to be integrated (when used alongside WebID authentication).

Proposal: either set the default behaviour to not force upfront negotiation, or make it possible to configure. The out of the box configuration may want to force TLS connection, however, it should be possible to set TLS renegotiation for (at least) public read resources from config.

[1] https://github.com/linkeddata/dokieli/issues/122#issuecomment-316721891
[2] https://www.w3.org/2005/Incubator/webid/spec/tls/#h_note_2

**Comment by csarven** [comment]
See also https://github.com/solid/node-solid-server/wiki/Running-Solid-behind-a-reverse-proxy

**Comment by RubenVerborgh** [comment]
We need to enable configuration, as renegotiation will not work behind a proxy. (Or renegotiation should be disabled if `certificateHeader` is set).

**Comment by melvincarvalho** [comment]
> this forces an undesirable UX through user's Web browser

Any screen grabs here, would be helpful.

**Comment by RubenVerborgh** [comment]
![image](https://user-images.githubusercontent.com/675313/39871126-23c20388-5464-11e8-81b7-895e6a976024.png)

^ This times the number of origins on the page. (Modal popup, "Remember" doesn't work.)

**Comment by RubenVerborgh** [comment]
We have this now in OIDC mode.

**Comment by timbl** [comment]
This means that TLS renegotiation is now implemented — the oidc mode was a now defunct command line flag. You ran it oidc mode even if you were also using webid tls.

**Comment by RubenVerborgh** [comment]
@timbl We use renegotiation on one specific resource, namely '/login/tls', in order to wrap OIDC around WebID-TLS.

Renegotiation for private resources, as described in this PR, is not implemented.
