### ISSUE TITLE
Databrowser is mistakenly loaded for HTML files.

### ISSUE THREAD

**Issue by timbl** [solid/node-solid-server#538]
Example:

https://timbl.com/timbl/Public/Test/Content-Type/text/html/simple.html

Should be sent to the bowser by the server, rendered directly by the bowser.  Used to work. Not sure when broke. 

The databrowser should be used when the source data file is a data file like Turtle, etc, not  human-readable document like text, HTML, or PDF.

Similarly, https://timbl.com/timbl/Public/Test/2017/08/23/Saturday%20Article.html  should just be sent to the browser.

**Comment by timbl** [comment]
Interestingly, text/plain files like https://timbl.com/timbl/Public/Test/Content-Type/text/plain/simple.txt are served Ok

**Comment by timbl** [comment]
![image](https://user-images.githubusercontent.com/1254848/29253205-1ef7c1f6-8045-11e7-8358-b21839a8b0b6.png)

**Comment by dmitrizagidulin** [comment]
@timbl I suspect this issue was introduced when RDFa support was added, and `html` became a valid RDF type.
Fix is at PR https://github.com/solid/node-solid-server/pull/539, for your review.

**Comment by DiegoPino** [comment]
New to the project, but watching from afar for some time. Seems like the logic that forces that is here:
https://github.com/solid/node-solid-server/blob/cba687c455094adecc3d55b50ee6dd9a231d68c7/lib/handlers/get.js#L78-L96

Not sure if the first === 0 is intended there. (array) indexOf gives 0 (actual (int) number) back if needle is found in array at position 0, and -1 (where a !== would make sense) if not present at all.

**Comment by DiegoPino** [comment]
@dmitrizagidulin dismiss my last comment. Just saw yours and your fix 👍

**Comment by dmitrizagidulin** [comment]
Thanks, @DiegoPino

**Comment by dmitrizagidulin** [comment]
Fixed in PR #539, closing.
