### ISSUE TITLE
Resources should have working .acl links

### ISSUE THREAD

**Issue by RubenVerborgh** [solid/node-solid-server#542]
At the moment, a resource `https://solid.org/a/b/c/d` will have a link header to `https://solid.org/a/b/c/d.acl`, even if that .acl resource doesn't exist (for instance, the corresponding .acl might be `https://solid.org/a/b.acl`). As a result, .acl lookups sometimes/often result in a 404.

**Comment by RubenVerborgh** [comment]
The proposed resolution, as discussed with @dmitrizagidulin, is the following workflow:

a. If the .acl exists and the user can access it, return that .acl.
b. Otherwise, if the user can access the corresponding resource, generate a user-specific ACL for that specific resource.
c. Otherwise, return 401/403.

In the future, this workflow could be extended with options 2 or 3 above in case related .acls are accessible. However, in any case, step b will be needed to cover all remaining cases, so we opt to implement it first.

**Comment by timbl** [comment]
I have problems with these approaches... partly because I have ode which relies on the system as is, and partly because if you lie in http you can end up in trouble. In lots of ways later. 

The existence or not f a specific ACL file is an important thing 
Imagine making a copy of a repo preserving the acl files. You can do it now but you can't do tit if the server fakes acl files which are not there

**Comment by timbl** [comment]
Caches in bowsers would get confused of course too

**Comment by dmitrizagidulin** [comment]
@timbl A good point, re exporting the repo. (Although that's an excellent reason for why exporting accounts should be done server-side, and not client side).

So then how about we take the approach above, but instead of serving the generated acl directly, we 307 redirect to a generated acl?

**Comment by RubenVerborgh** [comment]
>partly because if you lie in http you can end up in trouble

What would the ”lie” be in this instance?

I figured that if "<x> :hasAcl <y>", then dereferencing <y> gets a representation of that ACL.
That representation might or might not be complete (and in fact, any representation of an ACL is incomplete).
We are not changing those semantics in anyway.

> Imagine making a copy of a repo preserving the acl files. You can do it now but you can't do tit if the server fakes acl files which are not there

Agree on that one.

> Caches in bowsers would get confused of course too

Vary by logged-in user fixes that.

**Comment by RubenVerborgh** [comment]
After discussion with @timbl and @dmitrizagidulin, we will implement this instead as #246.
