### ISSUE TITLE
Fragment identifier on main page URI is stripped in login process

### ISSUE THREAD

**Issue by timbl** [solid/node-solid-server#571]
e.g you open a new Chrome, go to incognito mode, and load:

https://timbl.com/timbl/2017/Solid/HighLevelIssues/index.ttl#this

You end up getting to

https://timbl.com/timbl/2017/Solid/HighLevelIssues/index.ttl

This is only a problem the first time, because of all the redirects, not later when the login state has been stored.
Seems to be a problem with eith TLS or OIDC forms of login.   I thought @RubenVerborgh fixed this, at least for OIDC.

**Comment by RubenVerborgh** [comment]
So the previous bug was #562 and involved a fix in the general 401 response. I'll check what's going on.

**Comment by dmitrizagidulin** [comment]
We fixed the server side redirect, but not for cases where the auth process is initiated from witnin a mashlib app. Will post details shortly.

**Comment by dmitrizagidulin** [comment]
The fix in https://github.com/solid/node-solid-server/pull/562 addressed a slightly different use case.

In this case, however, the hash fragment is being lost - first during the oidc identity provider's authentication response (the provider overwrites the hash fragment with auth response credentials), and second when the auth client parses the response and clears the credentials from the uri.

The upstream issues to fix are:

- [ ] [`oidc-op` #38-Preserve redirect_uri hash fragment during implicit flow AuthenticationResponse](https://github.com/anvilresearch/oidc-op/issues/38) and
- [ ] [`solid-auth-client` #28-Preserve original redirect_uri hash fragment when parsing authentication response](https://github.com/solid/solid-auth-client/issues/28)

**Comment by RubenVerborgh** [comment]
Given that https://github.com/solid/solid-auth-client/issues/28 is done, we should be able to close this.

I'm not sure that we need https://github.com/solid/solid-auth-client/issues/28, as the hash is added by solid-auth-client. @dmitrizagidulin, do you think this is still necessary?

We might need to be careful to avoid both components trying to add the same hash. It they do, we might want to lock oidc-op to 0.3.0 for now.

**Comment by dmitrizagidulin** [comment]
Yeah, i think this issue is now resolved and can be closed. And no, don't worry, the oidc-op component will not interfere w the auth client restoring the hash.

**Comment by RubenVerborgh** [comment]
Okay, let's wait for #590 to test.

**Comment by RubenVerborgh** [comment]
Can be tested after #593, and closed if succesful.

**Comment by dan-f** [comment]
Fixed in #593

**Comment by timbl** [comment]
This bug seems to have crept back in.
It certainly currently is a problem on timbl.com, using the current head of master 1a04fae750f5d8852c05790c2752d7a8836e95ca

**Comment by RubenVerborgh** [comment]
I suspect #640.

**Comment by RubenVerborgh** [comment]
So https://timbl.com/timbl/2017/Solid/HighLevelIssues/index.ttl#this currently redirects to https://timbl.com/api/auth/select-provider?returnToUrl=https://timbl.com/timbl/2017/Solid/HighLevelIssues/index.ttl#this.

Note how `returnToUrl` is not escaped, causing this problem (and several other potential ones, related to query string for instance).

**Comment by RubenVerborgh** [comment]
There was a bug on the node-solid-server side, which #648 fixes. The correct URL is now passed to oidc-auth-manager, which now needs to be fixed to handle that URL correctly.

**Comment by dmitrizagidulin** [comment]
@RubenVerborgh Great work on this!

**Comment by RubenVerborgh** [comment]
@dmitrizagidulin Thanks, now it's your turn in https://github.com/solid/oidc-auth-manager/issues/17 :wink:

**Comment by RubenVerborgh** [comment]
Should be fixed.
