### ISSUE TITLE
CLI - express injection

### ISSUE THREAD

**Issue by tomasklapka** [solid/node-solid-server#574]
I would like to run another express middleware with the solid server while not losing the CLI and its processing of args and config.json. It means I need to mount the middleware before solid mounts to it's mount path.

There is an optional argument to inject express in function `createServer (argv, app)` but it is not used in CLI.

I'm thinking about refactoring the CLI part to be a reusable module with possibility to inject both solid and express.

Do you have another suggestion?

**Comment by RubenVerborgh** [comment]
Actually, we have been discussing splitting the library into several parts, and all those parts could consist of Express-style handlers. For instance, the LDP handlers could live in a separate library, as could the permission handlers.

**Comment by tomasklapka** [comment]
resolved by #576
thanks for accepting 👍
