### ISSUE TITLE
Attempting to log in to https://timbl.com via WebId-TLS hangs

### ISSUE THREAD

**Issue by melvincarvalho** [solid/node-solid-server#575]
Attempting to log in to https://timbl.com hangs.  

**Setup**

OS : Ubuntu
Browser : Chromium
WebId : https://melvincarvalho.com/#me

**Steps**

- go to https://timbl.com
- click login
- click With Certificate (WebId-TLS)

Browser hanging too, nothing to report in console. 
Network Tab: POST to https://timbl.com/login/tls, status : pending

I believe also experienced by @csarven

**Comment by dmitrizagidulin** [comment]
This has likely been fixed in the latest `release/v4.0.0` branch; will check with @timbl regarding what version the site is running.
