### ISSUE TITLE
Dead-end UX upon landing "in" Solid

### ISSUE THREAD

**Issue by dan-f** [solid/node-solid-server#579]
![dead_end_ux](https://user-images.githubusercontent.com/2146312/30068167-eadbf908-922a-11e7-80b7-cf754fb678b1.png)

"Welcome to the account of `<url>`" doesn't help me discover what I can *do* with a solid account.

"Solid User Profile" would make sense if I were viewing a solid user profile.

I realize we don't yet have a dashboard, but I think there's a bare minimum experience we should offer on the home page:

- log out
- affordance to edit my profile
- file browser
- example apps

**Comment by RubenVerborgh** [comment]
I'll have a first pass on this.

**Comment by dan-f** [comment]
Great. Perhaps we can sync up when you get to the office.

**Comment by RubenVerborgh** [comment]
Following up on this in #594.
