### ISSUE TITLE
Filenames with spaces do not show up in folder listings

### ISSUE THREAD

**Issue by RubenVerborgh** [solid/node-solid-server#587]

**Comment by timbl** [comment]
E.g. https://timbl.com/timbl/Public/Test/Characters/ should in fact list two more .pdf files:

LeHégaret
before[between]after
coma,comma
movie@11
now two spaces.pdf
one space.pdf
per%cent

**Comment by timbl** [comment]
Log DOES include: solid:handlers Files in directory: LeHégaret,before[between]after,coma,comma,movie@11,now two spaces.pdf,one space.pdf,per%cent

**Comment by RubenVerborgh** [comment]
Fixed in #588.
