### ISSUE TITLE
/authorize endpoint throws 401

### ISSUE THREAD

**Issue by dan-f** [solid/node-solid-server#592]
@dmitrizagidulin any ideas?

**Comment by dmitrizagidulin** [comment]
Not sure, need to investigate. How do I replicate?

**Comment by dan-f** [comment]
create a new `node-solid-server`, check out the `release/v4.0.0` branch, initialize the server in single-user mode, and request the `/authorize` endpoint.

**Comment by RubenVerborgh** [comment]
Narrowed this down to `node_modules//@trust/oidc-op/src/handlers/AuthenticationRequest.js`:

```
provider.backend.get('clients', params.client_id)
      .then(client =>
```

For some reason, `client` is `null`.

**Comment by RubenVerborgh** [comment]
It's trying to read a non-existing file `node-solid-server/.db/oidc/op/clients/_key_eadf425188c51482d600a464a76266c8.json`

**Comment by RubenVerborgh** [comment]
The actual file seems to be called `_key_aadd1962ac2400a3812728805331acbb.json`.

**Comment by RubenVerborgh** [comment]
So when testing, remember to start with an empty `.db` folder; this seems to trigger it.

**Comment by dan-f** [comment]
Alright, I think we've tracked it down. The immediate issue was that the RP had a stale `client_id` (from previous testing).

The larger issue is that `401 Unauthorized` seems like the wrong status code for this case.
