### ISSUE TITLE
accounts/new: use given public FOAF profile to populate fields

### ISSUE THREAD

**Issue by jmvanel** [solid/node-solid-server#608]
On https://solidtest.space/api/accounts/new
When I put my public FOAF profile
http://jmvanel.free.fr/jmv.rdf#me
in field "(Optional) External WebID:"

The page says:
Username required

It could use the given public FOAF profile to populate fields:
- user name
- name
- email

**Comment by melvincarvalho** [comment]
Good idea!  Discussed here:

https://gitter.im/solid/node-solid-server?at=59cd4b020cef4fed2ebb3501
