### ISSUE TITLE
Support HTTP requests

### ISSUE THREAD

**Issue by retog** [solid/node-solid-server#609]
It should be possible, or if that's already the case documented, to have the server listen to HTTP. When using NSS behind a load balancer or behind a server serving multiple domains an encryption between the reverse proxy and NSS is often unnecessary.

**Comment by RubenVerborgh** [comment]
This is already possible; I'm running this setup myself. Just don't pass any certificate info and HTTP will be chosen.

**Comment by melvincarvalho** [comment]
@RubenVerborgh I assume this cant be done from the init.  

Do you mean you manually removed it from config.json?

I dont suppose you have a copy of your config.json?

**Comment by RubenVerborgh** [comment]
```
{
  "root": "/home/ruben/tmp/node-solid-server/data",
  "port": "5500",
  "serverUri": "https://drive.verborgh.org",
  "webid": true,
  "mount": "/",
  "configPath": "./config",
  "dbPath": "./.db",
  "idp": false,
  "corsProxy": "/proxy",
  "auth": "tls",
  "certificateHeader": "X-Client-Certificate"
}
```

**Comment by melvincarvalho** [comment]
However 

      "serverUri": "https://drive.verborgh.org"

Would indicate https and not http?

**Comment by RubenVerborgh** [comment]
That's the public URL. The server runs privately on HTTP over port 5500. Public HTTPS is NGINX.

**Comment by melvincarvalho** [comment]
@RubenVerborgh thanks!

I can confirm that this configuration works with http.

@retog ok to close this issue?
