### ISSUE TITLE
slug ignored when creating container

### ISSUE THREAD

**Issue by tag42git** [solid/node-solid-server#610]
seem to be running into:

ldp.js: 485: getAvailablePath (host, containerURI, { slug = uuid.v1(), extension }) {

**Comment by dmitrizagidulin** [comment]
Thanks @tag42git.

Can you provide a bit more info - what are the headers in the request and the response?

**Comment by tag42git** [comment]
input headers ...using auth.fetch(uri, options)

uri: https://localhost:8443/

Link:"<http://www.w3.org/ns/ldp#BasicContainer>; rel="type""
Slug:"newc"
body:undefined
content-type:"text/turtle"
location:"newc"
method:"POST"

---------------------------

output headers:

["vary", "Origin"]
["allow", "OPTIONS, HEAD, GET, PATCH, POST, PUT, DELETE"]
["content-type", "text/plain; charset=utf-8"]
["location", "/d302a610-a9f4-11e7-9814-252dab645994"]
["link", "<.acl>; rel="acl", <.meta>; rel="describedBy", <ht…p://www.w3.org/ns/ldp#BasicContainer>; rel="type""]
["content-length", "7"]
["etag", "W/"7-rM9AyJuqT6iOan/xHh+AW+7K/T8""]

**Comment by dmitrizagidulin** [comment]
Thanks. Hmm I wonder why it's ignoring the slug. Will investigate.

**Comment by tag42git** [comment]
Thanks for looking into this.  Here's an html file that reproduces it with my local solid-server@4.0.1

<html>
  <head>
    <script src="solid-auth-client.bundle.js"></script>
  </head>
  <header><title>name container test</title></header>
  <body>
    <title>name container test</title>
    <button onclick="login()">Login</button>
    <div>
      <textarea id="textarea1"></textarea>
      <button onclick="createContainer()">Create Container</button>
    </div>
    
    <script>
      var auth = SolidAuthClient;

      function login() {
        console.log("login");

        if (auth == null) {
          console.log("couldn't load SolidAuthClient");
          return;
        }

        //return auth.popupLogin({popupUri: process.env.POPUP_URI}).then(
        return auth.popupLogin({popupUri: "http://localhost:8080/popup.html"}).then(
          (session) => {
    			    if (session) {
                this.userNotification = 'logged in, webId= '+session.webId;
                this.usersWebid = session.webId;
              }
              else {
                this.userNotification = "couldn't get session";
              }
		        },
            (reason) => {
              this.userNotification = "couldn't authorize, reason= "+reason;
            }
          ).catch(err => {
              this.userNotification = "unable to authorize, error: "+err;
            }
          );
      } // login

      function createContainer() {
        var name = document.querySelector("#textarea1").value;

        const request = auth.fetch("https://localhost:8443/", 
                                    {
                                      method: "POST", 
                                      "Link": "http://www.w3.org/ns/ldp#BasicContainer; rel='type'", 
                                      "content-type": "text/turtle",
                                      "Slug": name, 
                                      "location": name
                                    });

        return request.then(
          (response)=>{
            if (response.ok === true) {
              console.log(response.text());
            }
            else {
              console.log("Couldn't create "+name);
            }
          },
          (err)=>{
             console.log("Couldn't create "+name+", because "+err);
          }
        );
      }
    </script>
  </body>
</html>

**Comment by tag42git** [comment]
Thanks for looking into this. Here's an html file that reproduces it with my local solid-server@4.0.1

[sluglet.html.gz](https://github.com/solid/node-solid-server/files/1363110/sluglet.html.gz)

**Comment by tag42git** [comment]
sorry closed by mistake...

**Comment by melvincarvalho** [comment]
@tag42git  Did you mean to close this again?

**Comment by tag42git** [comment]
@melvincarvalho Yes, sorry it was not a problem with nss but user error on my part.  I was using solid-auth-client without solid-client and I was putting the slug and some other options in the options object without making a headers object within the options object.  I got it working.  I'm making a rudimentary warp-like client in polymer 2 and hope to eventually build a quizlet-like gizmo with it.  Its an amateur effort.  I really like nss and Solid and hope to use it a lot.

**Comment by melvincarvalho** [comment]
@tag42git awesome, cant wait to see it.  If you add the solid-app tag to your repo, we can watch it evolve :)

**Comment by tag42git** [comment]
@melvincarvalho Added tag solid-app
