### ISSUE TITLE
Include RDFSource and NonRDFSource in response Link header

### ISSUE THREAD

**Issue by csarven** [solid/node-solid-server#611]
Making `POST`/`PUT` requests with:
`Link: <http://www.w3.org/ns/ldp#RDFSource>; rel="type"` and
`Link: <http://www.w3.org/ns/ldp#NonRDFSource>; rel="type"`
should be honoured. The server defaults it to its superclass `ldp:Resource` - this is fine if the type is not recognized, wanted, or simply having it there by default any way, as long as the other conditions are met. However, not applying the specific class makes it more difficult to distinguish between `ldp:RDFSource` and `ldp:NonRDFSource` resources - the client will have have to look at the `Content-Type` as a fallback. Perhaps most importantly, there is information loss due to the specialisation being ignored.

See `linksHandler` in https://github.com/solid/node-solid-server/blob/master/lib/header.js where it basically checks to see if it is a container or not.

If the incoming resource includes `Link: <http://www.w3.org/ns/ldp#RDFSource>; rel="type"` and the `Content-Type` is one of `'text/turtle', 'text/n3', 'application/n-triples', 'application/ld+json', 'application/rdf+xml', 'application/xhtml+xml', 'text/html'`, the response header for that resource should come back out the same way: `Link: <http://www.w3.org/ns/ldp#RDFSource>; rel="type"`.

**Comment by timbl** [comment]
1) What do you mean by "honoured"?   The link should be saved and regurgitated on HEAD and GET?  Or the server should change its behavior and eg not allow you to patch a non-RDF resource?  
2) What would you say an HTML document was - and RDF resource or not?

I think I am happy with the mime type, as stored in a file extension and transmitted in the Content-type header, being definitive about what the thing is and what it isn't.

**Comment by csarven** [comment]
1. Right, more or less "regurgitate". At the moment, if a POST/PUT request uses ldp (Non)RDFSource in Link header, the server allows it and saves it, but when that resource is served, it will only use ldp Resource. As far as the LDP spec goes, returning (Non)RDFSource is a MAY.
2. Yes, I think HTML documents are RDFSources.

Looking at:
- http://www.w3.org/TR/ldp/#dfn-linked-data-platform-rdf-source
- http://www.w3.org/TR/rdf11-concepts/#dfn-rdf-source

More specifically:

> "A snapshot of the state can be expressed as an RDF graph. For example, any web document that has an RDF-bearing representation may be considered an RDF source."

So, RDFa in HTML is definitely an RDFSource.


LDP's NonRDFSource: https://www.w3.org/TR/ldp/#dfn-linked-data-platform-non-rdf-source says "binary or text documents that do not have useful RDF representations." 

I suppose "plain" HTML may be in that grey zone. Having said that, RDFa parsers will grab any `rel` (and typical HTML documents do contain them), so I think it is sufficiently safe to treat HTML as RDFSource.

On a related note, SVG may also be an RDFSource because it contain contain RDFa or RDF/XML. RDFa in particular is not restricted to HTML, and can be embedded in (X)HT(ML) family.
