### ISSUE TITLE
Optional x509 module causing install error on Raspberry Pi

### ISSUE THREAD

**Issue by pmcb55** [solid/node-solid-server#616]
I'm seeing the following error when attempting a simple 'sudo npm install -g solid-server' on my Raspberry Pi with the latest Raspbian OS (v4.9.59-v7+, GNU/Linux 9 'stretch'). The failing module (x509) is marked as optional in the package.json, so the installation continues, but I assume this could cause problems later - i.e. what use-cases require the x509 module?

Doing a local install (npm install solid-server) seems to work fine.

```
pi@raspberrypi:~ $ sudo npm install -g solid-server
npm WARN deprecated nodemailer@3.1.8: All versions below 4.0.1 of Nodemailer are deprecated. See https://nodemailer.com/status/
/usr/bin/solid -> /usr/lib/node_modules/solid-server/bin/solid

> x509@0.3.2 install /usr/lib/node_modules/solid-server/node_modules/x509
> node-gyp rebuild

gyp ERR! clean error 
gyp ERR! stack Error: EACCES: permission denied, rmdir 'build'
gyp ERR! System Linux 4.9.59-v7+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/solid-server/node_modules/x509
gyp ERR! node -v v8.9.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: x509@0.3.2 (node_modules/solid-server/node_modules/x509):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: x509@0.3.2 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ solid-server@4.0.1
added 2 packages and updated 1 package in 36.074s
```

**Comment by melvincarvalho** [comment]
Thanks for the bug report.  Seems odd that you get permission denied when running as sudo.  Is it still an issue?

**Comment by pmcb55** [comment]
Hi Melvin - I gave up on using the Pi, due to this error. Dmitri mentioned that he thought Ruben introduced this dependency on x509 (and node_gyp) to resolve issues he was having in getting a proxy (Nginx I think) to forward auth headers to a SOLID server he was running behind that proxy. Or something like that...

**Comment by melvincarvalho** [comment]
OK thanks, well, we'll get it working!  Which type of pi do you have?  I'll order one ...

**Comment by pmcb55** [comment]
The latest one - Raspberry Pi 3. I used the standard, recommended OS distribution, running 'uname -a' gives me:
Linux raspberrypi 4.9.59-v7+ #1047 SMP Oct 29 12:19:23 GMT 2017 armv71 GNU/Linux

Running 'cat /etc/os-release' gives:
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"

**Comment by melvincarvalho** [comment]
did you [install](https://www.raspberrypi.org/downloads/) raspbian or noobs?

**Comment by melvincarvalho** [comment]
So I get the following : 

```
sudo npm install -g solid-server
npm WARN deprecated nodemailer@3.1.8: All versions below 4.0.1 of Nodemailer are deprecated. See https://nodemailer.com/status/
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
/usr/local/bin/solid -> /usr/local/lib/node_modules/solid-server/bin/solid

> x509@0.3.3 install /usr/local/lib/node_modules/solid-server/node_modules/x509
> node-gyp rebuild

gyp ERR! clean error 
gyp ERR! stack Error: EACCES: permission denied, rmdir 'build'
gyp ERR! System Linux 4.4.50-v7+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/solid-server/node_modules/x509
gyp ERR! node -v v9.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 

> spawn-sync@1.0.15 postinstall /usr/local/lib/node_modules/solid-server/node_modules/spawn-sync
> node postinstall

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: x509@0.3.3 (node_modules/solid-server/node_modules/x509):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: x509@0.3.3 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ solid-server@4.0.2
added 474 packages, updated 6 packages and moved 7 packages in 148.294s
```

But I think it may be installed

```
solid 

  Usage: solid [options] [command]


  Options:

    -V, --version  output the version number
    -h, --help     output usage information


  Commands:

    init [options]   create solid server configurations
    start [options]  run the Solid server
```

**Comment by melvincarvalho** [comment]
After this I was able to run solid with

    export NODE_TLS_REJECT_UNAUTHORIZED=0
    solid start -v

@pmcb55 Want to give it a try?

**Comment by pmcb55** [comment]
@melvincarvalho Ah Ok, so you are seeing the same error I was seeing, but you're just ignoring it :) ! See my original post though, where I did notice that the x509 module was marked as optional in the package.json - my question was about what could break when actually using SOLID? i.e. what are the optional features of SOLID that *need* the x509 module, and therefore need to be avoided when running on a Pi?

**Comment by melvincarvalho** [comment]
Ah, I suppose we could try running the tests?

**Comment by melvincarvalho** [comment]
@pmcb55 I get 3 failing tests on the pi

`$ npm run test`

----

```
  3 failing

  1) ACL with WebID through X-SSL-Cert with a valid certificate should return 200:
     AssertionError: expected { Object (_readableState, readable, ...) } to have a property 'statusCode' of 200, but got 500
      at Function.assert.propertyVal (node_modules/chai/lib/chai/interface/assert.js:1001:37)
      at Context.<anonymous> (test/integration/acl-tls-test.js:1125:14)

  2) ACL with WebID through X-SSL-Cert with a valid certificate should set the User header:
     AssertionError: expected { Object (x-powered-by, vary, ...) } to have a property 'user'
      at Function.assert.propertyVal (node_modules/chai/lib/chai/interface/assert.js:1001:37)
      at Context.<anonymous> (test/integration/acl-tls-test.js:1129:14)

  3) ACL with WebID through X-SSL-Cert with an invalid certificate should return 401:
     AssertionError: expected { Object (_readableState, readable, ...) } to have a property 'statusCode' of 401, but got 500
      at Function.assert.propertyVal (node_modules/chai/lib/chai/interface/assert.js:1001:37)
      at Context.<anonymous> (test/integration/acl-tls-test.js:1164:14)
```
----

Same for you?

**Comment by melvincarvalho** [comment]
Here's a strange thing.  Removing the node_modules directory, installing again and then running the tests, they all passed.

**Comment by melvincarvalho** [comment]
Ah, I know why.  So I followed the instructions here to fix the issue.

https://docs.npmjs.com/getting-started/fixing-npm-permissions

Still dont know the root cause tho.  Possibly in the way npm is installed.  Would like to understand better!

**Comment by RubenVerborgh** [comment]
It depends on the user which installed Node, and the user that is performing the local `npm install`. Given that there is a fix and this is not a Solid bug, there's nothing we need to do.

**Comment by RubenVerborgh** [comment]
For posterior reference:

>  i.e. what are the optional features of SOLID that need the x509 module, and therefore need to be avoided when running on a Pi?

This module is only needed when [running Solid behind a reverse proxy with certificate forwarding](https://github.com/solid/node-solid-server/wiki/Running-Solid-behind-a-reverse-proxy#solution-2-have-the-reverse-proxy-forward-the-client-certificate-through-an-http-header).
