### ISSUE TITLE
POSTs and PUTs to of resources with no extension and no content-type should be a 400 error

### ISSUE THREAD

**Issue by pmcb55** [solid/node-solid-server#624]
Clients should always either provide a resource extension (that maps to a valid content-type) or explicitly send a valid content-type with all POSTs and PUTs. To enforce this the server should reject as an explicit error any POST to /foo (i.e. without an extension) without a content-type header. Right now it accepts it - the server assumes the content-type to be Turtle and saves the file server-side as foo.ttl. Personally I'd rather see the server reject this request with a 400 and a clear explanation as text/plain such as 'POST requests must provide a valid HTTP content-type header'.

I assume file extensions will *safely* suffice if no content-type is provided, e.g. .ttl for 'text/turtle', .jsonld for 'application/ld+json', .nt for 'application/n-triples'. By 'safely' I mean no chance of accidental conflicts, where a user who has never heard of the RDF Trig serialization just happens to suffix their resources with '.trig'. The alternative is simply to always enforce the use of a content-type, and reject with a 400 any requests without one - but I guess that might make wget or curl a little more awkward to use for developers who know what they're doing!

**Comment by timbl** [comment]
In general web architecture has nothing to do with filename extensions.   Propose that a PUT or POST should be rejected if there is no Content-Type: header, whatever the path part of the URL.

**Comment by RubenVerborgh** [comment]
Should be implemented by #662.
