### ISSUE TITLE
Running in development environments

### ISSUE THREAD

**Issue by jdh0139** [solid/node-solid-server#626]
solid server version : 4.0.2
OS : Windows 10

I entered the following flags at the command prompt:

solid start --no-reject-unauthorized

Then, I checked with Select Provider.

request to https: // localhost: 8443 / .well-known / openid-configuration failed, reason: self signed certificate

If I set the 'Running in development environments' incorrectly, I would appreciate it if you let me know the right way.

**Comment by dmitrizagidulin** [comment]
Hi @jdh0139! Try `solid-test start -v` instead.  The `solid-test` script (instead of the `solid` script) sets the right flags etc.

**Comment by jdh0139** [comment]
Quick answer Thank you very much.

I entered the solid-test start -v at the command prompt.

The following warning has occurred:

'solid-test' is not an internal or external command, executable program, or batch file.

When you installed solid-server, you entered the following flags:

npm install -g solid-server

Should I install other programs?

If I installed it wrong, I would really appreciate it if you could tell me the right way.

**Comment by dmitrizagidulin** [comment]
Rrright, ok. So really, we should change the README / recommended install method to a local install from a git clone. Because this is the kind of stuff that global installs run into.

Soo, quick fix - install node-solid-server from a git repo, cd into it, and do `./bin/solid-test init` and `./bin/solid-test start -v`

**Comment by jdh0139** [comment]
Thank you very much.

I was able to run solid-server.

Thank you again and again.
