### ISSUE TITLE
I can not find the server IP address, DNS_PROBE_FINISHED_NXDOMAIN

### ISSUE THREAD

**Issue by jdh0139** [solid/node-solid-server#629]
1. os: Linux, Ubuntu 16.04.3 LTS
2. Domain : ccl.korea.ac.kr
3. solid server : https://ccl.korea.ac.kr:8443
4. WebID : https://jdh0139.ccl.korea.ac.kr:8443/profile/card#me

When attempting to connect to WebID, the following error occurs:

[I can not find the server IP address at jdh0139.ccl.korea.ac.kr.

DNS_PROBE_FINISHED_NXDOMAIN]

Do you need to build DNS?

I am sorry to ask that you may be basic.

Thank you very much for giving me more detailed instructions.

**Comment by DiegoPino** [comment]
Hi, do you have a wildcard certificate? See please the requisites to run a multi-user server with *.yourdomain.ext resolution at https://github.com/solid/node-solid-server#run-multi-user-server-intermediate

**Comment by jdh0139** [comment]
Thank you for your reply.
I used a self-signed certificate.
I have run solid-server with [solid-test start].

**Comment by melvincarvalho** [comment]
Hi, so it looks like jdh0139.ccl.korea.ac.kr is not pointing to the IP address of your server.

- Add a Wildcard DNS record in your DNS zone (e.g.*.yourdomain.com)

This the part you will need your domain registrar to perform.

**Comment by melvincarvalho** [comment]
@jdh0139 OK to close this issue?

**Comment by jdh0139** [comment]
Thank you.
Thanks to that, I was able to solve it.
Yes. I'll close it.

**Comment by melvincarvalho** [comment]
Thanks! :)
