### ISSUE TITLE
Incorrect Vary header

### ISSUE THREAD

**Issue by RubenVerborgh** [solid/node-solid-server#636]
The server should at least have `Accept` and `Origin` as values for the `Vary` header in responses.

**Comment by dmitrizagidulin** [comment]
@RubenVerborgh happy to take a crack at this, unless you're already fixing?

**Comment by RubenVerborgh** [comment]
All yours 😉

**Comment by dmitrizagidulin** [comment]
@RubenVerborgh Why `Origin` for the `Vary` header? (I agree with the `Accept` part)

**Comment by RubenVerborgh** [comment]
We use the `cors` library, which sets the `Access-Control-Allow-Origin` header based on the `Origin` header of the request.

**Comment by RubenVerborgh** [comment]
That said, `cors` likely sets its own `Vary` header, and I've seen that indeed. We should be careful not to overwrite it.

**Comment by timbl** [comment]
If you don't have a Vary: Origin header then Chrome for example will cache a version from a different origin, and then reject it because the ACAO header doesn't match.

**Comment by dmitrizagidulin** [comment]
Ok, so, just to clarify, we _do_ currently return a `Vary: Origin` header. 
So is the issue about also adding a `Vary: Accept`? Or can we close it?

**Comment by RubenVerborgh** [comment]
Still need to fix Accept.

**Comment by RubenVerborgh** [comment]
Ooh Authorization too

**Comment by dmitrizagidulin** [comment]
@RubenVerborgh sure thing. added.

**Comment by kjetilk** [comment]
Great stuff! Looks good to me, one quick review from one of you commenters on the bug, and I'll merge.

**Comment by kjetilk** [comment]
OK, good, seems like the library prevents duplicate headers anyway, so we're good.
