### ISSUE TITLE
401 error on fetch() after logging in with OIDC

### ISSUE THREAD

**Issue by timbl** [solid/node-solid-server#638]
This may be a bug in the client, as the server rejects the client's credentials but I will log it here, as it is not obvious which side.  To reproduce:

- Start with an incognito browser
- Load the public read thing https://timbl.com/timbl/Public/Solid/2018/03%20Ruben%20visit%20solid%20meeting/index.ttl#this
- Press the "log in" button and then in the popup "login with solidtest.space"
- login with your credentials there
- go back to the meetulator panes and change something, like th enote, or add a message to the chat
- The UI complains that it can't do the patch because of a 401 error.

Server logs are at https://timbl.com/timbl/Public/Solid/2018/Gists/2018-02-24-nss-log-401-bug.txt

**Comment by timbl** [comment]
Rather than use an incognito browser window, starting by
```
delete localStorage["solid-auth-client"]
```
in the js console makes sure you are not previously logged

**Comment by dmitrizagidulin** [comment]
@timbl - is this issue still happening?

**Comment by RubenVerborgh** [comment]
This was fixed by #660.
