### ISSUE TITLE
Installation process: specify nodeJS minimum version

### ISSUE THREAD

**Issue by balessan** [solid/node-solid-server#647]
OS : Ubuntu 16.04

Steps:
- Fresh install of Ubuntu ( VirtualBox in my case )
- Install nodeJS and NPM from the official packages
- Install node-solid-server from NPM
- Launch the solid server : `solid init`

Results:
```sh
balessan@balessan-VirtualBox:~/workspace$ solid init
/usr/local/lib/node_modules/solid-server/bin/lib/cli.js:4
const { spawnSync } = require('child_process')
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/solid-server/bin/solid:2:18)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
```

Workaround:
- Install NVM ( https://www.digitalocean.com/community/tutorials/how-to-install-node-js-on-ubuntu-16-04 )
- Switch to a recent version of NodeJS ( 9.0.0 in my case ): 
```
nvm install 9.0.0
nvm use 9.0.0
```

README to be fixed to specify a minimal version number of NodeJS to be used.

**Comment by dmitrizagidulin** [comment]
@balessan - Thanks, good idea.

**Comment by melvincarvalho** [comment]
Thanks for reporting this.  I'd recommend using LTS versions of node.

https://github.com/nodejs/Release

We should probably set a minimum version to be node 8.  

We'll have to work on getting node solid server working on node 10 too.

I think the engines variable may address this : 

https://docs.npmjs.com/files/package.json#engines

`{ "engines" : { "node" : ">=0.10.3 <0.12" } }`

**Comment by melvincarvalho** [comment]
Right so we already have 

https://github.com/solid/node-solid-server/blob/master/package.json#L131

```JavaScript
  "engines": {
    "node": ">=8.0"
}
```

@balessan which version of node were you using?

**Comment by ninachaubal** [comment]
My understanding is that `engines` in `package.json` is advisory only. https://docs.npmjs.com/files/package.json#engines. We could require people to use the `engine-strict` flag?

**Comment by ninachaubal** [comment]
To @balessan's point about specifying the node version in the README, we could add a badge like [![node](https://img.shields.io/node/v/solid-server.svg)](https://npm.im/solid-server)

**Comment by melvincarvalho** [comment]
FYI: just tried this on ubuntu 18.04 which is the latest LTS, and node defaults to v8.10.0
