### ISSUE TITLE
Wire up LegacyResourceMapper

### ISSUE THREAD

**Issue by RubenVerborgh** [solid/node-solid-server#661]
The `LegacyResourceMapper` introduced in #660 should replace all inline URL to filename (and vice-versa) mapping, so we:
- provide consistent mapping behavior all over, and eliminate bugs in existing mapping code (or at least confine those bugs to one place)
- simplify the transition to the new `ResourceMapper` (#662)

**Comment by RubenVerborgh** [comment]
We possibly might want to do this by changing the interface of `ldp`, such that it accepts URLs rather than filenames. Then, `ldp` itself calls `LegacyResourceMapper` instead of requiring all of its callers to do that.

**Comment by rubensworks** [comment]
Ok, I'm working on this issue now.

I'm still relatively new to the codebase, so I could use some input on where I could find calls that should be changed.
So far, I see the following:
* [`util.js/uriToFileName()`](https://github.com/rubensworks/node-solid-server/blob/feature/wire-legacy-resource-mapper-2/lib/utils.js#L70)
* [`util.js/uriToRelativeFilename() `](https://github.com/rubensworks/node-solid-server/blob/feature/wire-legacy-resource-mapper-2/lib/utils.js#L87)
* [`util.js/getBaseUri() `](https://github.com/rubensworks/node-solid-server/blob/feature/wire-legacy-resource-mapper-2/lib/utils.js#L93)
* [`util.js/getFullUri() `](https://github.com/rubensworks/node-solid-server/blob/feature/wire-legacy-resource-mapper-2/lib/utils.js#L117)
* [`util.js/pathBasename()`](https://github.com/rubensworks/node-solid-server/blob/feature/wire-legacy-resource-mapper-2/lib/utils.js#L121)

I assume there may be others as well?

**Comment by RubenVerborgh** [comment]
My heuristic is: everywhere where multiuser is checked.

**Comment by megoth** [comment]
@rubensworks if you're going to edit `lib/utils.js`, maybe it's a good time those functions to a utility-file in `lib/common`? Trying to make methods a bit more reusable by putting them in more explicitly named utility-files.

**Comment by rubensworks** [comment]
@megoth The plan is actually to remove as much as possible from `lib/utils.js` :-) In favor of the new methods of `ResourceMapper`.

But the remaining functions could indeed be moved to `lib/common` afterwards.

**Comment by rubensworks** [comment]
I assume #911 will be merged before this refactor is done, so I'll have to rebase in any case.

**Comment by rubensworks** [comment]
Done in #952.
