### ISSUE TITLE
401 on preferences file even though logged in

### ISSUE THREAD

**Issue by timbl** [solid/node-solid-server#668]
401 on preferences file while accessing

 https://ruben-just-works.solid.community/public/Kingsley-Test/Chat/chat.ttl  

See Gitter May 8, 09:36

https://gitter.im/solid/node-solid-server?at=5af1d21c97f07c7e137a7327

- Logged in with my TLS webid
- got a “401 on prefs error"

The error is a dialog box from the time index machinery which says more or less "that's funny we are logged in OK but I have gotten a 401 error from your preferences file, and if you can't access your preferences file, that is a weird problem.   As you did have a pointer to it in your public profile.  And it does exist.

Suspect this an effect of the logic (using a suspect and maybe broken model of how this all works) in solid-auth-client which checks a "host auth mode" against the "logged in auth mode".

**Comment by RubenVerborgh** [comment]
> Logged in with my TLS webid

@timbl The first question is whether you are actually logged in, or whether solid-auth-client _thinks_ you are logged in (https://github.com/solid/solid-auth-client/issues/44).

To answer that question, can you check your localStorage on https://ruben-just-works.solid.community/ and tell me whether the value for solid-auth-client contains WebID-TLS?

**Comment by timbl** [comment]
No, I had logged in.    Here is the auth from when  I had done
- Open a new incognito window
- Go to https://timbl.com/timbl/Public/
- Go to the Home Pane.
- Press Log In
- On the popup press Log In With Databox (which I know means log in with TLS)
- Use my normal webid on w3.org with the cert
- The page then complains it can't access my preferences

```
widgets.signInOrSignUpBox
mashlib.js:4708 Logged in, 1 panels to be serviced
/timbl/Data/preferences.n3:1 Failed to load resource: the server responded with a status of 401 (Unauthorized)
mashlib.js:35275 @@ Recording GET failure for <https://timbl.com/timbl/Data/preferences.n3>: 401
mashlib.js:4218 HTTP status 401 for pref file <https://timbl.com/timbl/Data/preferences.n3>

localStorage['solid-auth-client']
 "{"session":{"authType":"WebID-TLS","idp":"https://databox.me/","webId":"https://www.w3.org/People/Berners-Lee/card#i"},"hosts":{"timbl.com":{"authType":"WebID-OIDC"}}}"`
```
I suspect the problem is:  solid-auth-client won't send my credentials because it thinks that there are two ways of being logged in , TLS and OIDC but there are not.   You end up whether yo use a cert or a password, you end up with OIDC creds. The code on solid-auth-client which checks

**Comment by RubenVerborgh** [comment]
Should be fixed by #727.

**Comment by RubenVerborgh** [comment]
I still get 401.

@timbl I have the feeling that the fetcher used to get the preferences file is _not_ SolidAuthClient. Can you verify?

**Comment by RubenVerborgh** [comment]
The problem turned out to be different solid-auth-client versions in mashlib/solid-ui/solid-panes. All have been upgraded to use 2.0.
