### ISSUE TITLE
option to enable/disable OIDC provider mode

### ISSUE THREAD

**Issue by elf-pavlik** [solid/node-solid-server#671]
Capturing from https://github.com/solid/node-solid-server/issues/667#issuecomment-388572613

Non all solid servers have to act as OIDC providers, some will only act as origins for datasets.
Server with OIDC provider mode disabled would always verify identity with other IDPs using WebID-TLS and WebID-OIDC but very unlikely need username/password, password resets and all other IDP specific features.

Possibly all the OIDC provider logic could work as middleware which gets loaded only if config enables it.

**Comment by RubenVerborgh** [comment]
Following up in #672.
