### ISSUE TITLE
Implement Group access in the ACL system

### ISSUE THREAD

**Issue by timbl** [solid/node-solid-server#673]
This functionality is defied in the spec
https://github.com/solid/web-access-control-spec#groups-of-agents
but hasn't actually been implemented in NSS, although it has been discussed a lot.

An issue has always been how to deal with access control using a group whose membership is not public.  A decision was made to anyway implement access by group for the special case where the group is public.  

It is getting to the point where it is becoming annoying not to have this functionality.
Not finding an existing issue here, I raise it now here, not sure whether to flag it as a enhancement or not....

**Comment by kjetilk** [comment]
This should now be very nearly there with with #719 and https://github.com/solid/solid-permissions/pull/24
