### ISSUE TITLE
Verify hostname is a valid subdomain upon account creation

### ISSUE THREAD

**Issue by RubenVerborgh** [solid/node-solid-server#674]
An `ls` on `solid.community:/home/solid/solid.community` shows tens of hostnames like `*.solid.community`, but also two hostnames that are just `pizza` and `croque`.

My suspicion is that these were created by manually passing a hostname somehow.

**Comment by RubenVerborgh** [comment]
I think people were entering spaces.

**Comment by kjetilk** [comment]
This has been fixed.
