### ISSUE TITLE
Implement 'post_logout_redirect_uri' support

### ISSUE THREAD

**Issue by dmitrizagidulin** [solid/node-solid-server#675]
Implement support server-side for handling of the `post_logout_redirect_uri` (see section https://openid.net/specs/openid-connect-session-1_0.html#RPLogout)

**Comment by dmitrizagidulin** [comment]
Just for clarity - this issue still applies. It'll be fixed when https://github.com/solid/oidc-op/pull/7 is merged, then integrated into oidc-auth-manager etc.

**Comment by RubenVerborgh** [comment]
Thanks for clarifying. This bug has the “revisit” label, which means “issue confirmed, not a current priority, reconsider later”. So status can be updated when those things merge.

**Comment by dmitrizagidulin** [comment]
No prob, I figured. Although the bug https://github.com/solid/node-solid-server/issues/695 is essentially a duplicate of this issue. (Tho that one has more details)
