### ISSUE TITLE
Upgrade dockerfile from node 6 to node 8

### ISSUE THREAD

**Issue by melvincarvalho** [solid/node-solid-server#680]
As we move to node 8 LTS it would be better to upgrade docker, which is in line with travis CL and node engines in package.json

**Comment by melvincarvalho** [comment]
see : solid/node-solid-server#691

**Comment by kellyprankin** [comment]
Has this issue been taken care of? It looks like the person who PRed backed it out?

**Comment by melvincarvalho** [comment]
Yes it has

https://github.com/solid/node-solid-server/blob/master/Dockerfile#L1

Closing
