### ISSUE TITLE
Checkbox xsd:boolean PATCH fails to change file (preferences, forms)

### ISSUE THREAD

**Issue by timbl** [solid/node-solid-server#681]
Currenly for instance I have a weird error that a checkbox file  (in the long chat prefernces for chanuging the instance preference or embedded images ) feel won’t turn the thing to false
````
 DELETE DATA { <https://timbl.com/timbl/Public/Test/2018/RWWCrew%20only/Long%20chat%20channel/index.ttl#id1526855085848> <http://www.w3.org/ns/solid/terms#expandImagesInline> "1"^^<http://www.w3.org/2001/XMLSchema#boolean> .
 } 
 ; INSERT DATA { <https://timbl.com/timbl/Public/Test/2018/RWWCrew%20only/Long%20chat%20channel/index.ttl#id1526855085848> <http://www.w3.org/ns/solid/terms#expandImagesInline> "0"^^<http://www.w3.org/2001/XMLSchema#boolean> .
 }
looks right, but the file still has 
```
:id1526855085848 terms:expandImagesInline true;
```

Tim Berners-Lee @timbl May 26 11:47
Bizarre
the numeric values change fine.  And to boolea change to true bu t not to false.
Could be with a slight refactoring of the checkbox to take two sites of graphs instead of just a property.?

**Comment by melvincarvalho** [comment]
2.5.3 Booleans
Boolean values may be written as either 'true' or 'false' (case-sensitive) and represent RDF literals with the datatype xsd:boolean.

https://www.w3.org/TR/turtle/#booleans

I'm probably missing lots of historical stuff here, but should the literal be written

     "0"^^<http://www.w3.org/2001/XMLSchema#boolean>

or

    "false"^^<http://www.w3.org/2001/XMLSchema#boolean>

**Comment by RubenVerborgh** [comment]
@timbl I believe you fixed this, right?
