### ISSUE TITLE
401 on fetch of protected resource on different site when logged in with TLS

### ISSUE THREAD

**Issue by timbl** [solid/node-solid-server#682]
See https://gitter.im/solid/chat?at=5b09efed160c567d16dde225

I get a 401 on my own preferences file when logged in with TLS to https://melvin.solid.live/public/timeline/ . T
o reproduce,

1) start with incognito mode
2) turn on debugger network logs; Chrome;
3) click on https://melvin.solid.live/public/timeline/
4) click on Home pane (house) at outer level (top line, in hover controls)
5) click on “log in”
6) Pick “login with data box”
7) Use a cert
8) See the error "Strange - you are not authenticated (properly logged on) to read preferences file.” in an alert,
9) note the error in the network logs
There may be more direct ways of reproducing the same bug

**Comment by dmitrizagidulin** [comment]
As mentioned in chat, Databox.me is not running an oidc-compatible server. The 401 on your preferences file is expected behavior.

**Comment by highlevellogic** [comment]
Closed: But I ran into this today in case anyone's reading this. 
See the error "Strange - you are not authenticated (properly logged on) to read preferences file.”

Cause: Incorrect turtle syntax for permissions (acl:mode) in account's .meta.acl and .acl files. Very strange. I'd been running for a couple of days with no problems - and suddenly, it happened.
