### ISSUE TITLE
Better error reporting in responses

### ISSUE THREAD

**Issue by RubenVerborgh** [solid/node-solid-server#686]
There should be a good explanation for errors, especially for 401.

In debug mode, we can give extra information on 403 regarding the .acl, and perhaps also on 500.

**Comment by dmitrizagidulin** [comment]
👍 Definitely, that would be very helpful. 

I've long wanted to do that (especially using nested errors via the VError library, as described here: https://www.joyent.com/node-js/production/design/errors )

**Comment by RubenVerborgh** [comment]
And also maybe the exact Solid version number (as per @timbl's comment https://gitter.im/solid/node-solid-server?at=5b39e9a270efc60660a59b78).
