### ISSUE TITLE
Node 10.3 fails on travis -- "eval npm ci"

### ISSUE THREAD

**Issue by melvincarvalho** [solid/node-solid-server#690]
The command "eval npm ci  " failed. Retrying, 3 of 3.

https://travis-ci.org/solid/node-solid-server/builds/385795733?utm_source=github_status&utm_medium=notification

**Comment by dmitrizagidulin** [comment]
I think the relevant part of the error message is: `Invalid: lock file's rdflib@0.16.3 does not satisfy rdflib@^0.17.0`. 

Which sounds like the `package-lock.json` needs to be re-generated.

**Comment by melvincarvalho** [comment]
@dmitrizagidulin thanks for the valuable insight

But why should it pass for node 10.0 then, but not, node 10.3?

**Comment by dmitrizagidulin** [comment]
No idea :)
