### ISSUE TITLE
Consider special handling for robots.txt

### ISSUE THREAD

**Issue by csarven** [solid/node-solid-server#694]
If robots.txt doesn't exist, return a 404, instead of 401, and then its HTML meta redirecting to auth/select-provider (for login).

**Comment by dmitrizagidulin** [comment]
Ah, good idea. 

Do we actually want to include a proper robots.txt, or..?

**Comment by csarven** [comment]
As a general rule of thumb: only if there are paths that are public-read that should not be indexed or archived by other services. Note that, by suggesting that some path should not be crawlable would make proper archiving less effective. So, here the general assumption should be that, if public-read, then go ahead and index/archive.

Having said that, I would default to not having a robots.txt or an empty robots.txt. Return 404. The admin should make these decisions.

**Comment by dmitrizagidulin** [comment]
@csarven - so, there's no good way to have special handling of `robots.txt` requests, in solid-server.

I've added PR #700, though, which adds empty/default robots.txt files to new account templates and server templates, with their corresponding .acls. So, that should cut down on the 401 error spam (which is what I assume prompted you to open this issue).

**Comment by dmitrizagidulin** [comment]
Addressed by PR #700, closing.
