### ISSUE TITLE
Login not asking for credentials after a logout

### ISSUE THREAD

**Issue by PulsarFox** [solid/node-solid-server#695]
I'm currently on Ubuntu 17.10, with node-solid-server v4.0.10
My index.html is hosted on live server extension on Visual Studio Code and it has my js file in it.

In my script I login with OIDCWebclient and I reproduced the exact steps for login as written here : https://hackmd.io/onfGBqczTzClCd2DUKViEg#

Login works fine, the first time it asks me the credentials and redirects me to my html page. 

Then I logout with auth.logout() but when I want to log in again it does not asks me my credentials but log me in directly. And I want to be able to select another account. 

I tried to visit the /logout endpoint with window.location then hit backwards but nothing changed. 
Even if I don't hit backwards or open it in another tab nothing changes, the log in does not ask me for credentials.

**EDIT :**  i've tried with RawGit, it does the same thing.
The only way i've managed to log in again is by stopping the server and run it again

**Comment by dmitrizagidulin** [comment]
Thanks @PulsarFox! I'm working on a fix now, will update this issue as soon as it's ready.

**Comment by PulsarFox** [comment]
Well fixed, the logout seems to need the credentials to logout (yea it's obvious when I think of it) 
so in order to disconnect I did a Get request with fetch function given with OIDC on /logout endpoint

I didn't think of it before but yea if the logout was accessible everywhere, everyone could log you off heh...

**Comment by RubenVerborgh** [comment]
Following up in #675.
