### ISSUE TITLE
Support LetsEncrypt webroot plugin

### ISSUE THREAD

**Issue by kjetilk** [solid/node-solid-server#708]
It seems like we can simplify the LetsEncrypt domain validation by accommodating for the webroot plugin. It [seems](https://certbot.eff.org/docs/using.html#webroot) just making sure files inside ```/.well-known/acme-challenge/``` is served will do this.

**Comment by RubenVerborgh** [comment]
All that requires is a `/.well-known/` at the server root (or, in case of single user, in that user's data folder), and this folder should have a public ACL.

We can provide such a folder by default as a convenience to the user.
