### ISSUE TITLE
Should DELETE requests result in a 200 or 204?

### ISSUE THREAD

**Issue by dmitrizagidulin** [solid/node-solid-server#714]
This is low priority, but I'd love to clarify the expected semantics.

If I'm understanding the docs correctly, a 200 OK is returned after a DELETE if there's a response body (like some sort of html message or whatever), and if there's no content, it should be a 204.

We're currently returning a 200 with no body (aside from the 'OK' I suppose). Should we either return some sort of message or switch the response to a 204?

@timbl ?

**Comment by akuckartz** [comment]
See https://tools.ietf.org/html/rfc7231#section-4.3.5 and https://tools.ietf.org/html/rfc7231#section-6.3.5
