### ISSUE TITLE
Deleting a file should require write permission on the container

### ISSUE THREAD

**Issue by RubenVerborgh** [solid/node-solid-server#729]
Possibly needs to be addressed in solid-permissions.

**Comment by dmitrizagidulin** [comment]
Why on the container? (and not the file itself, which is how it currently is.)

**Comment by dmitrizagidulin** [comment]
That doesn't quite make sense. If I upload the file somewhere, I should be able to delete it. (Without necessarily being able to delete or edit the container where I uploaded it..)

**Comment by dmitrizagidulin** [comment]
(Also, we should probably have this discussion on https://github.com/solid/web-access-control-spec, no?)

**Comment by RubenVerborgh** [comment]
This was just brought up in a meeting today, I'm mainly marking it for follow-up. The idea is that write access should enable people to empty a file, but not delete it. As on Linux systems, deleting should require write permissions on the folder, as you're changing the listing of that folder.

**Comment by dmitrizagidulin** [comment]
Ahh, I didn't realize that was the Linux behavior..

**Comment by RubenVerborgh** [comment]
Handling this in https://github.com/solid/solid-permissions/issues/28.

**Comment by rubensworks** [comment]
Done in #1014.
