### ISSUE TITLE
Fix signup WebID text

### ISSUE THREAD

**Issue by RubenVerborgh** [solid/node-solid-server#730]
The signup text should clarify that you should only enter your existing WebID if you also want to log in with it.

**Comment by kjetilk** [comment]
I don't really understand why you would want to create a WebID if you already have one...?

**Comment by RubenVerborgh** [comment]
You want to create a new pod, but you already have a WebID.

**Comment by kjetilk** [comment]
OK, so like in #743?

**Comment by RubenVerborgh** [comment]
Yes!
