### ISSUE TITLE
Create empty type index on signup

### ISSUE THREAD

**Issue by RubenVerborgh** [solid/node-solid-server#733]
Basically, the default user template should contain empty

```
/settings/privateTypeIndex.ttl
/settings/publicTypeIndex.ttl
```

and a filled

```
/settings/prefs.ttl
```

and the profile should include

```
:me
    pim:preferencesFile </settings/prefs.ttl>;
    solid:publicTypeIndex <settings/publicTypeIndex.ttl>;
    solid:privateTypeIndex </settings/privateTypeIndex.ttl>;
```

**Comment by kjetilk** [comment]
"type" and "index" are a bit too generic for me to understand what the issue is :-)

**Comment by RubenVerborgh** [comment]
@timbl Are there docs for the type indexes?

**Comment by RubenVerborgh** [comment]
Clarified the issue text; these are files used by Databrowser.

**Comment by kjetilk** [comment]
I found https://github.com/solid/solid/blob/master/proposals/data-discovery.md , is that it?

**Comment by RubenVerborgh** [comment]
Yes!

**Comment by kjetilk** [comment]
Actually, it looks to me that these are in: https://github.com/solid/node-solid-server/tree/master/default-templates/new-account/settings , right? 

Non-empty, but that's even better, I suppose :-)

**Comment by RubenVerborgh** [comment]
Ah, and linked too apparently… weird that we get this error then sometimes. But let's assume fixed.

**Comment by RubenVerborgh** [comment]
Fixed by 752.
