### ISSUE TITLE
Handle multilinguality

### ISSUE THREAD

**Issue by csarven** [solid/node-solid-server#735]
In order to store/serve data based on `Content-Language`/`Accept-Language` headers:

- [ ] If no further development needs to be done, document the behaviour/expectations (then close issue)
- [ ] Handle content-negotiation for `Content-Language` eg:
  * allow storing and serving from separate locations per language (perhaps similar to the mapping (file extension) pattern like `$.{ext}`, but `$.{lang}$.{ext}` (or whatever) -- not sure what would be the reasonable/best practice to keep the content equivalent across different languages representations.
  * and/or similar to above but go through `.meta`
- [ ] and/or require `PATCH` for adding multilanguages, and server returns subset (while unique HTTP headers) -- not sure if this is good or bad at this time.. needs to be thought through / documented.
- [ ] and/or..

**Comment by timbl** [comment]
This is different from having localized versions of the software, I take it?  Just the ability to store stuff which will work under Accept-language negotiation?

**Comment by csarven** [comment]
Yes, I meant the data to be stored/served. I'll update the issue.

**Comment by RubenVerborgh** [comment]
Definitely interesting, but snoozing this for now given other priorities.
