### ISSUE TITLE
Only trust apps from a single origin

### ISSUE THREAD

**Issue by RubenVerborgh** [solid/node-solid-server#741]
There are CORS issues with current Solid apps: resources read from one origin cannot be read from another (despite `Vary: Origin`).

While we could fix these issues (for instance, by disabling caching), the question rises whether we should actually allow apps from random domains to access our pods.

Therefore, as a temporary solution for v5.0.0, @timbl proposes a single trusted domain on which apps run.

This domain should be configurable, and perhaps multiple can be allowed on a given server.

For v6.0.0, we should come up with a more flexible security model.

**Comment by kjetilk** [comment]
Yeah, I had taken this down as #738 , feel free to close either.

**Comment by RubenVerborgh** [comment]
Ah sorry! Since this issue expands on the “long story short”, let's keep this one.

**Comment by kjetilk** [comment]
This will be fixed by implementing https://github.com/solid/solid-permissions/issues/26

**Comment by RubenVerborgh** [comment]
Okay, following up there.
