### ISSUE TITLE
/logout should not be a GET request

### ISSUE THREAD

**Issue by RubenVerborgh** [solid/node-solid-server#744]
Since /logout changes state, it should not be GET.

**Comment by RubenVerborgh** [comment]
We can already implement a parallel route with POST for 4.1, and then drop the GET route for 5.0 (semver.major).

**Comment by dmitrizagidulin** [comment]
Heh, so this is the issue that was being addressed in the closed issue #675. (Though I totally get that 675 was named in an overly-specific nondescript manner).

So here's the story. Server-side support for this has been implemented in https://github.com/solid/oidc-op/pull/7 (though that PR still needs some tests, that's been the main holdup). Once that's merged, it'll need to be integrated into node-solid-server.

On the client-side, this has been implemented in PR https://github.com/solid/oidc-rp/issues/5. That changes how an auth client needs to use the logout call, etc.

**Comment by RubenVerborgh** [comment]
> Heh, so this is the issue that was being addressed in the closed issue #675.

 #675 about the post-logout redirection URL, right?
 
#744 is about using HTTP `POST` to log out instead of `GET`.

**Comment by dmitrizagidulin** [comment]
Yeah, so that's what I mean that it was badly named :) 
#675 is about fixing the POST handling of the `/logout` endpoint (and removing the existing `GET /logout` route in webid-oidc.js). And the thing that was blocking /that/ was post-logout redirect handling.

Anyways, I figured I'd give an overview of where the story stands right now.

**Comment by RubenVerborgh** [comment]
Makes sense, thanks.

**Comment by RubenVerborgh** [comment]
Indeed. As long as the GET (or any GET, for that matter) doesn't trigger a state change, it's fine.

**Comment by RubenVerborgh** [comment]
Unfortunately, I see lots of OIDC examples where logout is a GET request, so maybe this is just how it's done.

The OIDC spec itself does not mention anything though: http://openid.net/specs/openid-connect-session-1_0.html#RPLogout

**Comment by kidehen** [comment]
@RubenVerborgh ,

As already stated, GET is appropriate if the request is idempotent (isn't state changing). Otherwise it should be POST, despite under specification in the OIDC docs. 

/cc @cblakeley @smalinin

**Comment by RubenVerborgh** [comment]
> GET is appropriate if the request is idempotent (isn't state changing)

That's incorrect.

- a method is safe if it does not state change
- a method is idempotent is repeated invocations have the same effect as one invocation

GET/HEAD is safe and idempotent; PUT/DELETE is not safe but idempotent; POST is neither.

Logging out is a state change, so GET isn't appropriate.

**Comment by kidehen** [comment]
@RubenVerborgh ,

"a method is idempotent *if* repeated invocations have the same effect as one invocation" in my understanding of English  means it doesn't change state i.e., if you repeat invocations that produce the same effect, the said effect hasn't be changed or altered :) 

BTW -- what is the conclusion to this issue?

**Comment by RubenVerborgh** [comment]
> "a method is idempotent if repeated invocations have the same effect as one invocation" in my understanding of English, means it doesn't change state

No, that's not correct. They do change state on the first successful invocation, but any subsequent invocations do not incur an additional state change. E.g., `DELETE` is idempotent, but _does_ change state.

See the definition of [safe](https://tools.ietf.org/html/rfc2616#section-9.1.1) and [idempotent methods](https://tools.ietf.org/html/rfc2616#section-9.1.2) in the HTTP spec.
 
> BTW -- what is the conclusion to this issue?

I added a POST route because logging out is a state change, but I'm keeping the GET around for now (since removing that requires a major version change).

**Comment by melvincarvalho** [comment]
How about we keep GET around until the openlink work is merged.  Then think about deprecating it, and also updating the patch?

**Comment by kidehen** [comment]
@RubenVerborgh,

With POST and GET in place, what happens next? Is this issue closed or there is something else?

**Comment by RubenVerborgh** [comment]
> With POST and GET in place, what happens next?

Deprecation or removal of GET for 5.0.0 (if that turns out to be compatible with the rest of the OIDC world).

**Comment by kidehen** [comment]
@RubenVerborgh,

If other OIDC implementations are using GET (which is the case) then removing it will make the solid implementation problematic. That said, we have a generic client which could be used to test this claim against a solid server.  Basically, we end up in the same place i.e., when can we test a solid-server implementation of OIDC that has all the recent fixes applied. 

Note, we have Virtuoso and our OSDB tools in place as generic OIDC clients, distinct from what we've done with our solid-server fork. 

/cc @cblakeley @smalinin @dmitrizagidulin

**Comment by RubenVerborgh** [comment]
> If other OIDC implementations are using GET (which is the case)

Indeed, so we should tread carefully here.
