### ISSUE TITLE
Remove Github dependencies

### ISSUE THREAD

**Issue by kjetilk** [solid/node-solid-server#749]
We have dependencies on Github commits, which is fragile. 

We should remove those dependencies,  and upload packages if needed.

**Comment by justinwb** [comment]
Note - these are the current offenders:
@trust/jose
@trust/keychain
@trust/oidc-op
@trust/oidc-rs

However, at this point we may also need to evaluate other items from the @trust npm scope to determine if it's likely that we'll need to fork and modify in the future (and if we'll have similar troubles getting those mods merged back in and released). The other packages from @trust that we're relying on are:
@trust/json-document
@trust/keyto
@trust/oidc-rp
@trust/webcrypto

**Comment by justinwb** [comment]
@dmitrizagidulin reports there isn't an interest in maintaining these packages anymore by the @Trust org, and so we'll be looking take the forks we have, look at whether we need to fork the remaining @Trust dependencies, and then push new packages to our own solid npm org. @timbl needs to follow up with npm to resolve some outstanding issues with access to the solid npm org.

**Comment by timbl** [comment]
Is the trust org a corresponding legal entity or just an NPM construct?

**Comment by justinwb** [comment]
@timbl from what i can tell it is purely an NPM construct.

**Comment by RubenVerborgh** [comment]
More evidence of why depending on npm packages is bad: #756

**Comment by RubenVerborgh** [comment]
Updated dependencies of solid-auth-client (https://github.com/solid/solid-auth-client/issues/61) to avoid any dependencies on old OIDC packages. Updating Mashlib and RDFlib as well:

- https://github.com/solid/solid-ui/pull/42
- https://github.com/linkeddata/mashlib/pull/16
- https://github.com/linkeddata/rdflib.js/pull/249

**Comment by justinwb** [comment]
Confirmed resolved as of v4.1.2-rc.0 - https://github.com/solid/node-solid-server/commit/ae99c390049420ad82f92dde1052635e97c44b50...
