### ISSUE TITLE
Servers should trust themselves as OIDC issuers

### ISSUE THREAD

**Issue by RubenVerborgh** [solid/node-solid-server#755]
Given the following scenario:
- a user arrives on server X
- clicks "log in" and picks "server X" as IDP
- logs in via a client certificate (the WebID of which is on host Y≠X)

What happens now:
- the login is not accepted, because X is not an OIDC issuer for the user

What should happen:
- the server trusts itself as an IDP for client certificates

**Comment by dmitrizagidulin** [comment]
This is interesting.. the code should be there to support that exact same scenario. Does the WebID in the certificate match server X?

**Comment by RubenVerborgh** [comment]
No, it does not. Will clarify.

**Comment by dmitrizagidulin** [comment]
Ok, in that case, that's the expected behavior, no?

**Comment by RubenVerborgh** [comment]
Expected, but we can optimize in the case of a client certificate, since X does have as much reasons to trust the cert (if not more) than Y.

**Comment by dmitrizagidulin** [comment]
Not sure I fully understand or agree, but in case this is helpful, the changes should be made in https://github.com/solid/oidc-auth-manager/blob/master/src/oidc-manager.js#L365 and/or https://github.com/solid/oidc-auth-manager/blob/master/src/preferred-provider.js

**Comment by RubenVerborgh** [comment]
> Not sure I fully understand

So when I log in with my client certificate, X has to trust Y that Y has properly performed the validation (the user indicates to trust Y). When X validates the certificate itself, there's no trust involved. So every server can be assumed to be an IDP for a client certificates.

**Comment by dmitrizagidulin** [comment]
Ahh ok, I think I get it.

(Also, the calling code in the TlsAuthenticator may have to be changed, here: https://github.com/solid/node-solid-server/blob/master/lib/models/authenticator.js#L316 )
