### ISSUE TITLE
Rename acl:defaultForNew into acl:default

### ISSUE THREAD

**Issue by RubenVerborgh** [solid/node-solid-server#758]
The server should:
- read acl:default
- read acl:defaultForNew but warn
- write acl:default

as per the spec

**Comment by melvincarvalho** [comment]
Is this a breaking change?

**Comment by RubenVerborgh** [comment]
Yes, hence the `semver.major` label. However, we will still accept `acl:defaultForNew` for the time being. @timbl will change the client to also follow the above (https://github.com/solid/solid-ui/issues/40).

**Comment by RubenVerborgh** [comment]
https://github.com/solid/solid/issues/100

**Comment by RubenVerborgh** [comment]
Following up in https://github.com/solid/solid-permissions/issues/29.

**Comment by RubenVerborgh** [comment]
Actually, renaming also need to happen in `default-templates/new-account/`.

**Comment by RubenVerborgh** [comment]
Implemented in #768.
