### ISSUE TITLE
Update provider.json when changing port

### ISSUE THREAD

**Issue by PulsarFox** [solid/node-solid-server#764]
The file provider.json in `.db\oidc\op\provider.json` does not update itself when we change the server port (tested in localhost)

**Comment by RubenVerborgh** [comment]
@PulsarFox Thanks for reporting. We agree that this is an issue, but it's not on our priority list for v5.0.0, so I'm tagging "revisit" and closing it for now. We expect that it is likely to be fixed as a side-effect of other fixes (in the OIDC library).
