### ISSUE TITLE
Docker run fails

### ISSUE THREAD

**Issue by PulsarFox** [solid/node-solid-server#771]
When running the solid docker image, a npm error saying "Cannot find module: @solid/oidc-rp"

**Comment by cory2067** [comment]
I got a different issue initially: "Cannot find module '@trust/keychain'"

However, when I did `npm install` before building the Docker image, it runs fine. 
But that's strange -- wouldn't it be better to have `npm install` be included in the Dockerfile?

**Comment by PulsarFox** [comment]
`npm install` on the Dockerfile doesn't change a thing, now it tells me "Cannot find module '@trust/'"

**Comment by PulsarFox** [comment]
Fixed with commit changing package.json
   - "@trust/oidc-op": "solid/oidc-op#rc-0.3.2",
   + "@solid/oidc-op": "0.3.2",
   + "@solid/solid-auth-oidc": "^0.2.2"
