### ISSUE TITLE
Use local mashlib version

### ISSUE THREAD

**Issue by RubenVerborgh** [solid/node-solid-server#773]
The embedded Databrowser currently points to a public mashlib build. We probably want to point to a local copy, such that we can control the version number (as we do with solid-auth-client).

**Comment by timbl** [comment]
Makes sense .. though it has meant it has been easy for us to propogate bug fix to the databrowser without everyone installing new servers.

**Comment by RubenVerborgh** [comment]
> though it has meant it has been easy for us to propogate bug fix to the databrowser without everyone installing new servers

Yeah, the problem is that the server and Databrowser are sharing login state, so we're in trouble when the format of that state changes (as it just did).
