### ISSUE TITLE
Test for careful handling of all errors loading ACL files Group files, etc

### ISSUE THREAD

**Issue by timbl** [solid/node-solid-server#787]
Checking the ACL files involves zooming up the tree looking for the first one which exists.  It is tempting for the developer to just zoom up they get a 200 good load the ACL file, passing over everything that fails, 404 or not.  This is a very bad idea!  It must be explicitly tested for.

*The ACL file must only be skipped over if and only  if generated a only a 404 (not found) error*

Failure scenarios include:

- The net being down for a second, giving an error, when in fact the file exists. (with net access)

- The process has some internal fleeting problem for a second, giving an error, when in fact the file exists. 

- The ACL file has a parse error, and then  is treated as though it didn't exist.  

- The ACL file is not authorized at the unix file permissions level.

and so on.  As the ACL file in question may be more constraining than the default one higher in the tree, and so these error would end up giving access to someone who would not have been allowed it.

An ACL file parse error must generate a 500 response.

(Some but not all of these considerations apply to Group membership resources.)

**Comment by timbl** [comment]
When I say "generates a 404" I don't mean you have to do an HTTP request.  You do hae to chek that the file does not exist (as opposed to anu other error like no such file system or parse error etc

**Comment by RubenVerborgh** [comment]
We have had a privilege escalation bug in the past, where an ACL file could not be read (due to a server bug), and it was happily skipped.

So I think the issue here is: if an ACL file exists on disk, never ever read the parent.

**Comment by kjetilk** [comment]
Right, good point.

**Comment by Ryuno-Ki** [comment]
> https://github.com/solid/node-solid-server/blob/master/test/integration/acl-oidc-test.js#L176

As a side note: If you hit <kbd>y</kbd> while on that page, GitHub will expand the URL to a canonical form, which does not change over time. This way, you can look up what was referred to in a few month from now (when the page likely changed). Hit <kbd>?</kbd> to learn about more GitHub shortcuts :-)

**Comment by kjetilk** [comment]
> Neither; it's a 401/403.
> (Reasoning: it is a valid Turtle file, and specifies no access rights for the current user.)

Come to think of it, when codifying this in tests: Wouldn't an empty .acl for a file lead to loss of control (i.e., you cannot again change the controls) for that file?

I haven't got time to look into this now, but we should have some strategies to mitigate the effects of stuff like that happening by mistake, error or malice.

**Comment by dmitrizagidulin** [comment]
@kjetilk Yes, writing an empty .acl does lead to a loss of control for that resource or container.

**Comment by kjetilk** [comment]
Should be done with the merge of #970.
