### ISSUE TITLE
Content-type on HEAD is text/plain, text/turtle on GET

### ISSUE THREAD

**Issue by RubenVerborgh** [solid/node-solid-server#789]
Why is https://rubentest.solidtest.space/profile/card suddenly text/plain?

**Comment by timbl** [comment]
If you open that uri in the data browser it seems to get turtle

**Comment by akuckartz** [comment]
Another reason to create an automatic test suite...

**Comment by RubenVerborgh** [comment]
And another reason to rethink the architecture 😄 
The fact that it works for GET but not for HEAD shows that they have different logic paths, which should not be the case.

While we can fix this bug by fixing the HEAD implementation, the actual issue is deeper.

**Comment by RubenVerborgh** [comment]
Basically we should use the exact same logic, except for `stream.pipe` and `res.send` calls. And also skip `contentRange`.

**Comment by elf-pavlik** [comment]
I reported similar issue 2 years ago https://github.com/solid/node-solid-server/issues/454 In most recent comment there you suggest that #662 might fix that.

**Comment by RubenVerborgh** [comment]
Duplicate of #454 indeed; straightforward #662 wouldn't fix it indeed. Closing in favor of #454.
