### ISSUE TITLE
Add option to link to ToS, privacy notice, etc in the register file

### ISSUE THREAD

**Issue by kjetilk** [solid/node-solid-server#799]
For people (like ourselves) hosting PODs for others, there needs to be a privacy policy, Terms of Service, and stuff like that in place, and we need to link to it from the register account page. I suppose we might need to have a box that they can tick to indicate that they're read it too.

**Comment by mintunitish** [comment]
I would like to take this up!

**Comment by megoth** [comment]
@mintunitish give it a go ^_^

This is my proposal for how to solve it:
- Add an option to the init-script where the service-provider can link to their terms of service
- If option is in use, link to it from the register account page
- If option is in use, add checkbox that needs to checked to be able to create account

**Comment by megoth** [comment]
@mintunitish did you ever get going on this? I'm planning on taking this task if not ^_^

**Comment by mintunitish** [comment]
@megoth sorry about the delay. I have been caught up with some stuff and unable to proceed on this. Please go ahead.

**Comment by megoth** [comment]
This was fixed in https://github.com/solid/node-solid-server/pull/892 and https://github.com/solid/node-solid-server/pull/869. Closing this issue.
