### ISSUE TITLE
why are we "stuck" with servers?

### ISSUE THREAD

**Issue by ReinsBrain** [solid/node-solid-server#808]
If we really wanted to have distributed/decentralized control of information then why aren't we using IPFS? Without even ranting about use of angular, I can't get behind this project because it has ignored the superior work done with IPFS. Please go back to the drawing board.

**Comment by RubenVerborgh** [comment]
> superior work done with IPFS

Superior in what regard specifically?

Solid and IPFS are solving different problems. IPFS could be used as a Solid backend, but doesn't have to be.

Note that one of the initial server developers (@nicola) is now with Protocol.ai, so we are very well aware of the space.

> Without even ranting about use of angular

Why would that be a problem?

Some repositories of Solid use Angular, but you don't need any of them for a working system.

**Comment by ReinsBrain** [comment]
> Solid and IPFS are solving different problems
If the problems IPFS and Solid are solving are mutually exclusive then Solid is not solving core problems. Solid should be built upon IPFS and can add some extra "problem-solving".

**Comment by RubenVerborgh** [comment]
> Solid is not solving core problems

Just different problems 😄 

> Solid should be built upon IPFS

As I wrote above, it can be one of the backends we support. There are other options, like https://safenetwork.tech/
