### ISSUE TITLE
Check usernames for invalid characters at character creation 

### ISSUE THREAD

**Issue by stuartyeates** [solid/node-solid-server#810]
Currently on https://inrupt.net/ you can register with a username of  (for example) "stuart yeates" which then generates a "Welcome to Solid" email with a bad link of https://stuart/profile/card#me

Either the entire system needs to properly handle and encode non-alphabetic characters  (probably fairly hard) or the input form needs to check and warn when non-alphabetic characters are present.

**Comment by kjetilk** [comment]
Indeed, we have to address quickly. Also reported in https://github.com/solid/solid/issues/157

**Comment by fourcube** [comment]
@kjetilk I'd be happy to work on this tonight.
