### ISSUE TITLE
Can't find SSL key 

### ISSUE THREAD

**Issue by ricklyman** [solid/node-solid-server#815]
re: https://stackoverflow.com/questions/10175812/how-to-create-a-self-signed-certificate-with-openssl

<html>
<pre>
openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -days 365 -subj &apos;/CN=localhost&apos;
Generating a 4096 bit RSA private key
..................................................................................++
................................++
writing new private key to &apos;key.pem&apos;
Enter PEM pass phrase:
Verifying - Enter PEM pass phrase:
-----
</pre>
</html>

Error message: Can't find SSL key 

Q. Is a different file name expected? or?

**Comment by ricklyman** [comment]
Also: bash: /bin/solid-test: No such file or directory

**Comment by FrancisVilaAxway** [comment]
I have the same message 
ERROR Can't find SSL key in ./keys 
(I specified keys as the folder containing keys, when doing solid init). I have .pem files, .ppk files, .pub files...
I used the following commands:
	openssl genrsa -out privkey.pem 4096
	openssl ssh-keygen -t rsa -b 4096 -f privkey.pem
	ssh-keygen -t rsa -b 4096 -f privkey.pem
	openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -days 365
I also created a key pair with puttygen, then converted the .ppk file to a .pem file, as indicated here: https://aws.amazon.com/premiumsupport/knowledge-center/convert-pem-file-into-ppk/ 
Here's the list of files I have now in my folder:
.rnd
cert.pem
key.pem
privkey.pem
privkey.pem.pub
solid.pem
solid.ppk
solid.pub

**Comment by dmitrizagidulin** [comment]
@FrancisVilaAxway Solid init (and config.json) require a path to an individual file (not just the directory), so I suspect that's the issue.
