### ISSUE TITLE
Add password confirmation field to the registration page

### ISSUE THREAD

**Issue by justinwb** [solid/node-solid-server#822]
We have seen many cases of users entering their password into the "Full Name" field thinking that it was a password confirmation field because it comes immediately after the single password input.

We need to add a second password confirmation field on the registration page. This is standard practice, and seen by the amount of people sharing the password as their full name, is causing some credential leakage and some rightfully unhappy users.

**Comment by akuckartz** [comment]
This might be an alternative: Warn users when they enter identical Password and Full Name.

**Comment by justinwb** [comment]
Fair point but the common convention is to have a secondary password confirmation field. Not following standard UX is what got us into this mess in the first place ;)

**Comment by megoth** [comment]
#839 will close this issue, but it needs revision (@justinwb)

**Comment by michielbdejong** [comment]
@kjetilk can this be closed?
