### ISSUE TITLE
Provide a more information on the index page for the server itself

### ISSUE THREAD

**Issue by justinwb** [solid/node-solid-server#825]
Currently if you go to the server (e.g. https://solid.community), you get a completely vanilla index page, with no identifiable detail about the server in question. We need to expose the following (which should be unique per solid server and (probably) pulled from the config.json.

The lack of this information, especially related to who to contact for problems or issues, is leading to many people coming to the general community chat looking for help.

**Server Name** - Friendly name for the server - e.g. (Solid Community Provider)
**Server Description** - Short description of what the  server is about - e.g. (A free provider for the Solid community, by the Solid community).
**Server Logo** - Logo file to present (if available).
**Link to Project Status** - Link to a page at https://solid.inrupt.com that provides a brief status of where major elements of the ecosystem and project currently stand. For example, current state of documentation against the total projected work to be done. Current state of user experience. Current state of security model. Etc.
**Support Contact** - What e-mail address to reach out to for help, problems, issues

**Comment by megoth** [comment]
So a lot of this is quite easy to fix, but I think we should have a discussion on what we want to do with the front page, if anything; @justinwb and the team is working on a very good MVP for a new interface for the front page, so we might want to just wait until then. Or we might want to patch the current front page a bit, to make it a bit more useful for newcomers. 

But I suggest not doing to much, as it is going to replaced at some point anyway.

**Comment by megoth** [comment]
@justinwb Btw, where should we get the friendly name of the server, description, and logo? And which URLs should we use for for project status and support? (I'll try to suggest some as soon as I've worked more on this issue.)

Should it be config-properties that POD providers can fill in manually (i.e. not as part of the `solid init` script) perhaps?

@timbl (to include your requests on #844):
- **More explanation:** Do we have a good text we can use here? And what do you mean with IDS? (Perhaps Identity server? Shouldn't it decentralized identity server, in that case?)
- **LINKS to help:** Which URLs should we include? Perhaps https://solid.inrupt.com/docs ?
- **Links to solid:** I'm guessing we should link to https://solid.mit.edu/ ?
- **Main material which the server operator can make with background pictures and styling and an explanation of what this particular community is, serves, etc, who runs it, where it hosted etc.** This ties into a lot of what @justinwb suggested.

**Comment by dmitrizagidulin** [comment]
@megoth The server index page is created in [`ensureWelcomePage()`](https://github.com/solid/node-solid-server/blob/master/lib/server-config.js#L39) (which is called from `create-app.js`).

Oh also, it looks like there's a bug in the logic there - that function only copies the index.html and its corresponding .acl, but it should be copying the whole contents of the `templates.server` (which is `./default-templates/server`) dir into `serverRootDir` (which also includes things like the favicon, robots.txt, etc).

**Comment by timbl** [comment]
It could be a file index.ttl which only the owner has write access to

The HTML page could fill the dicument with a mixrure of our solid messaging and the owner’s readme.

The owner must of course have the option to replace the whole thing in their own style

**Comment by megoth** [comment]
@dmitrizagidulin FYI I've fixed the bug that you noted. I had to extend the list of files to be deleted after tests, and have refactored that into a utils-method for tests. (I tried using `emptyDirSync`, but that created a slew of other problems =P )

**Comment by megoth** [comment]
@timbl I think maybe we're talking about different things here? This is for the server info page in general, not the individual index.html in users' PODs. Or am I misunderstanding you?

**Comment by megoth** [comment]
For now I'm going to work with data being provided by config.json (as that is a concept that the providers should be familiar with), but it should be easy to move it elsewhere if people think that's better.

**Comment by megoth** [comment]
I might have a PR ready, but want to check in with some people first: @justinwb @dmitrizagidulin maybe you want to look at https://github.com/solid/node-solid-server/compare/develop...feature/server-info to see if I'm going the right way on this?

- Copy all files from `default-templates/server` (and modifying tests to handle this)
- Added a section on `default-templates/server/index.html` that's processed by Handlebar
- Adding server-info from config.json (is by default nothing, and will simply output host for server name if none is given)
- Added a .gitkeep for `common/img` as I think a lot of people will put their logo there

If we want to load server-info from config.json I think we should add some documentation on it, and maybe even extend the init-script.

**Comment by dmitrizagidulin** [comment]
@megoth the `server-info` branch looks good to me.

Although, why move the `processHandlebarTemplate` etc functions from `account-template.js` into the more generic `utils`?

**Comment by megoth** [comment]
It was the "natural" place for me to put it, but I do admit I didn't think much before putting it there.

Which other files would it be "natural" to put it in? Or should I've created a new file perhaps?

**Comment by dmitrizagidulin** [comment]
@megoth makes sense. Yeah, maybe a new file? like a template manager or something?

**Comment by megoth** [comment]
@dmitrizagidulin I've updated https://github.com/solid/node-solid-server/compare/develop...feature/server-info; I propose we move the utils functionality into `lib/common`, where we would distinguish more on what util-methods we have.

I've created `lib/common/fs-utils` and `lib/common/template-utils` for now, and we should move the functionality from `lib/utils` to more specific files later (didn't want to do this as part of this task).

**Comment by megoth** [comment]
Apart from that, should I continue with the assumption that custom info reg the server should be in `config.json`? I need to know if this is the way to go before I can continue this.

@kjetilk @RubenVerborgh @timbl

**Comment by RubenVerborgh** [comment]
Yes.

**Comment by michielbdejong** [comment]
@kjetilk can this be closed?

**Comment by kjetilk** [comment]
I think so.
