### ISSUE TITLE
Attempts to fetch/edit anything fails with errors in Fetch.

### ISSUE THREAD

**Issue by adamemerson** [solid/node-solid-server#826]
Looking at my profile gives me a large blank rectangle with the error
`Outline.expand: Unable to fetch <https://azure.solid.fox.blue/profile/card>: Failed to load  <https://azure.solid.fox.blue/profile/card> Fetcher: <https://azure.solid.fox.blue/profile/card> Internal Server Error status: 500` beneath it.

Same for the public folder. The inbox invites me to log in, but just gives an unauthorized error. It looks like one part is generating data another part can't parse, from the logs:

[solid.log](https://github.com/solid/node-solid-server/files/2436317/solid.log)

[config.json.txt](https://github.com/solid/node-solid-server/files/2436328/config.json.txt)

**Comment by shybyte** [comment]
I get at inrupt.net:
```
Outline.expand: Unable to fetch <https://shybyte.inrupt.net/profile/card>: 
Failed to load <https://shybyte.inrupt.net/profile/card>
Fetcher: <https://shybyte.inrupt.net/profile/card> Internal Server 
Error status: 500
```

**Comment by megoth** [comment]
@adamemerson @shybyte sorry for late response (we have been and are still a bit swamped with work): Is this still an issue for you? If so, please send an email to support@inrupt.com so that we can help you there.

I'll close this issue for now.

**Comment by kevin-smets** [comment]
I have the same issue for a local solid server... 500 could mean anything, no?

**Comment by kjetilk** [comment]
OK, @kevin-smets , was that with the latest 5.0.0-beta.5?

**Comment by kevin-smets** [comment]
May have been pebcac I'm afraid. I did not set  `export NODE_TLS_REJECT_UNAUTHORIZED=0` and `--no-reject-unauthorized` when using a self signed certificate. I tested now with the 5.0.0-beta.5 and it seems to working as expected. Sorry! 😭

**Comment by kjetilk** [comment]
Good to hear :-)
