### ISSUE TITLE
No permission to access this resource

### ISSUE THREAD

**Issue by Shuunen** [solid/node-solid-server#829]
Hi there :)

I just tryed solid, here is what I did : 

- installed solid globally
- created a "solid-test" directory & cd into it
- created cert/key for localhost
- run solid init & provided cert/key above
- run solid start
- went to https://localhost:8443/
- clicked register & created an account
- then clicked login & "Log in with localhost:8443"
- used previously created account
- saw "Logged in!" appears and then login popup closed

and now I'm stuck on this screen : 

![image](https://user-images.githubusercontent.com/439158/46337714-852e4f00-c62e-11e8-944a-e45925bdaa1a.png)

I think I'm missing something 😛

**Comment by megoth** [comment]
Hey, sorry for late response.

I think running node-solid-server globally has some reported bugs earlier, but cannot remember more right now. Maybe @dmitrizagidulin, @kjetilk or @RubenVerborgh knows more?

**Comment by kjetilk** [comment]
Huh, yeah, that's pretty weird. Sorry I didn't see it before. We need to follow up on that, so I'll give it the bug label.

**Comment by RubenVerborgh** [comment]
Dear @Shuunen, seems like you are hitting https://github.com/solid/solid-auth-client/issues/73, and what is worse, hitting it from `https:`. Will follow up over there.

**Comment by RubenVerborgh** [comment]
The bug in solid-auth-client leading to the `getItem` message has been fixed, and node-solid-server has been upgraded to include the fixed version bb8e9e62ed242a3cd3e284d2d68da069e5892f34.

However, I think your actual problem might have been a different one, namely the 500, so don't hesitate to reopen this issue if the problem persists in the latest develop.
