### ISSUE TITLE
Issues with non-standard port (not 8443)

### ISSUE THREAD

**Issue by batje** [solid/node-solid-server#830]
I installed and chose to use port 9443 on my localhost. I ran into security issues. doing a grep for port 8443 reveales the following:

```
grep -r 8443 *
config.json:  "serverUri": "https://localhost:8443",
data/.meta:<https://localhost:8443/profile/card#me>
data/.meta.acl:        <https://localhost:8443/profile/card#me>;
data/index.html.acl:        <https://localhost:8443/profile/card#me>;
data/inbox/.acl:        <https://localhost:8443/profile/card#me>;
data/favicon.ico.acl:        <https://localhost:8443/profile/card#me>;
data/settings/prefs.ttl:<https://localhost:8443/profile/card#me> foaf:mbox <mailto:me@example.com> .
data/settings/prefs.ttl:<https://localhost:8443/profile/card#me>
data/settings/publicTypeIndex.ttl.acl:        <https://localhost:8443/profile/card#me>;
data/settings/.acl:        <https://localhost:8443/profile/card#me>;
data/public/.acl:    acl:agent <https://localhost:8443/profile/card#me>;
data/.well-known/.acl:    acl:agent <https://localhost:8443/profile/card#me>;
data/robots.txt.acl:        <https://localhost:8443/profile/card#me>;
data/profile/card.acl:        <https://localhost:8443/profile/card#me>;
data/profile/card:    foaf:maker <https://localhost:8443/profile/card#me> ;
data/profile/card:    foaf:primaryTopic <https://localhost:8443/profile/card#me> .
data/profile/card:<https://localhost:8443/profile/card#me>
data/index.html:        <a href="https://localhost:8443/profile/card#me"><mark>https://localhost:8443/profile/card#me</mark></a>.
data/.acl:    acl:agent <https://localhost:8443/profile/card#me> ;
reinier@batjessd /var/www/solid/server $ grep -r 9443 *
config.json:  "port": "9443",
```

One of the issue I run into, is that in the popup window with 4 different types of login, when clicking on the button 'localhost:9443' the code fetches https://localhost:9443/.well-known/openid-config where the top of the file (and all other instances of localhost) look like:

```
issuer | https://localhost:8443
-- | --
authorization_endpoint | https://localhost:8443/authorize
token_endpoint | https://localhost:8443/token
userinfo_endpoint | https://localhost:8443/userinfo
jwks_uri | https://localhost:8443/jwks
registration_endpoint | https://localhost:8443/register
```
The next call is then to https://localhost:8443/jwks which is wrong.

**Comment by kjetilk** [comment]
That's weird... Most of these things are generated by `solid init` or `solid start`, I believe, i.e. they are not in the source tree. So, the question is what may have generated this...? I haven't got this problem, I run on port 8444 on my internal test system myself...

**Comment by batje** [comment]
It is slightly better if I redo it. I think I messed up the first `solid init` by giving a non-standard https port, and then pressing enter on the next question, where the default is `https://localhost:8443`. Could the uri not be replaced with just asking for servername? https:// seems to be default and the port was already asked for.

Anyways, with this config, the grep command dothat es not find port 8443 anymore.

```
solid init
? Path to the folder you want to serve. Default is /var/www/solid/server/data
? SSL port to run on. Default is 9445
? Solid server uri (with protocol, hostname and port) https://localhost:9445
? Enable WebID authentication Yes
? Serve Solid on URL path /
? Path to the config directory (for example: /etc/solid-server) ./config
? Path to the config file (for example: ./config.json) ./config.json
? Path to the server metadata db directory (for users/apps etc) ./.db
? Path to the SSL private key in PEM format ../localhost.key
? Path to the SSL certificate key in PEM format ../localhost.cert
? Enable multi-user mode No
? Do you want to set up an email service? No
``` 

However, I am clicking through the (magical still) UI, and i get to the point where the login screen with the 4 buttons pops up. I press the https://localhost:9443 button. The openid-configuration is fetched and it contains:

```

issuer | https://localhost:8443
-- | --
authorization_endpoint | https://localhost:8443/authorize
token_endpoint | https://localhost:8443/token
userinfo_endpoint | https://localhost:8443/userinfo
jwks_uri | https://localhost:8443/jwks
registration_endpoint | https://localhost:8443/register
```
So the next query then goes to jwks on port 8443.

So, we are closing in. I dont know where the openid-configuration is (i tried searching the github repo), so I can not help you with that.

**Comment by PulsarFox** [comment]
The provider.json file located in .db folder (created at the first server startup) does not update itself if you change the port, maybe that's the case here

**Comment by hubert-associates** [comment]
> The provider.json file located in .db folder (created at the first server startup) does not update itself if you change the port, maybe that's the case here

Bingo. Many thanks!

**Comment by kjetilk** [comment]
So, I suppose this is resolved. If not, please reopen.
