### ISSUE TITLE
Mount path configuration not working

### ISSUE THREAD

**Issue by Kemyke** [solid/node-solid-server#840]
I would like to access the solid server on the `https://192.168.200.100:8443/solidserver` path so my configuration is:
```
{
  "root": "/data",
  "port": "8443",
  "serverUri": "https://192.168.200.100:8443",
  "webid": true,
  "mount": "/solidserver",
  "configPath": "/",
  "configFile": "./config.json",
  "dbPath": "./.db",
  "sslKey": "/cert/privkey.pem",
  "sslCert": "/cert/cert.pem",
  "multiuser": false
}
```

So when i try to access ˙https://192.168.200.100:8443` i get 404 and when i try to access `https://192.168.200.100:8443/solidserver` i get 200 and the page loads. But the css is not loaded because it tries to loaded it from `https://192.168.200.100:8443/common/css/bootstrap.min.css`. Also the buttons points to addresses without the mount path (eg: `https://192.168.200.100:8443/register?`)
Am i miss something to configure it properly or is this a essential bug here?

**Comment by dmitrizagidulin** [comment]
Hi @Kemyke. The `mount` option is [slated to be removed](https://github.com/solid/node-solid-server/issues/493) when there's more bandwidth. It's unmaintained and untested, so there's very likely bugs there.

**Comment by Kemyke** [comment]
Oh i see. In this case i won't have the option to use the server on a different path then root (`/`)?

**Comment by dmitrizagidulin** [comment]
I think the best way to use the server on a different path is through proxy rewrite rules (using [Nginx rules](https://www.nginx.com/blog/creating-nginx-rewrite-rules/) or Apache or HAProxy).

**Comment by Kemyke** [comment]
Ok, then i forget this feature and solve it in the proxy.  :)
Thanks!

**Comment by kjetilk** [comment]
I'll add the revisit label, so we remember to do it later.
