### ISSUE TITLE
Server home page needs huge amount of work

### ISSUE THREAD

**Issue by timbl** [solid/node-solid-server#844]
When someone fires up (especially an IDOP server but a singkle user one too)
They  get currently:

![image](https://user-images.githubusercontent.com/1254848/46478172-593fd480-c7ba-11e8-915b-
54c89f8c1f0d.png)

There is no poin

Welcome to the Solid Prototype
This is a prototype implementation of a Solid server. It is a fully functional server, but there are no security or stability guarantees. If you have not already done so, please create an account.

This needs things like
- More explanation. Thie is a server allowing people to crete their own IDS, and get their own storage.
- LINKS to help -- general help documentation but also specific help for thsi page.
- Links to solid
- Main material which the server operator can make with background pictures and styling and an explanation of what this particular community is, serves, etc, who runs it, where it hosted etc.

**Comment by timbl** [comment]
Well maybe not a lot of work just some user-configured stuff and some more fixed HTML

**Comment by kjetilk** [comment]
Yeah, but is this something @justinwb 's could be doing? It is in  https://github.com/solid/node-solid-server/blob/develop/default-templates/server/index.html

**Comment by justinwb** [comment]
Similar ticket pushed the other night - should combine these together I think - https://github.com/solid/node-solid-server/issues/825

**Comment by megoth** [comment]
I'll do this as part of #825.
