### ISSUE TITLE
solidtest.space gives the wrong mime type for html

### ISSUE THREAD

**Issue by melvincarvalho** [solid/node-solid-server#851]
looking at

    curl -I https://schorsch.solidtest.space/public/u/xxx.html 
    HTTP/1.1 200 OK
    X-Powered-By: solid-server
    Content-Type: text/plain; charset=utf-8

I would expect text/html.  Any ideas why its text/plain?

**Comment by kjetilk** [comment]
Yeah, it is architecturally b0rked and built without having a proper HTTP implementation underneath... And where's that red-eyed devil emoji when you need it ;-) The fix is in the pipeline as #831, so I hope you don't mind me closing.
