### ISSUE TITLE
Implement simple system for updating user's index.html (and other resources that live inside a user's POD)

### ISSUE THREAD

**Issue by megoth** [solid/node-solid-server#853]
Today the `index.html`-file and similar resources that live in users PODs do not have a way of being updated by the POD providers. I think we need a simple system to allow for this so that user's can opt-in by default whenever there are updates. (As for the update that brings this functionality itself I think we have to force an update; this needs to be communicated to the community.) A result of not having this system in place prevents us from exposing the link to `/delete/account` that has been implemented in #177.

I don't quite know how to solve this, but my idea is the following:
1) Upon the forced update, all index.html get a version id
2) Include a script that checks this version with an API that returns whether or not there is an update
2a) If no update, then do nothing (End of actions)
3) If there is an update available, notify the user of this and give them options:
3a) To do an update, see 4
3b) To skip that specific update; this will add the version id of the updated to somewhere (cookie, localStorage, maybe as data somewhere in the user's POD) that tells the checkForUpdate-script to ignore this version in the future (End of actions)
4) Calls an API that does the update of the index.html and other resources, and lastly refreshes the page (End of actions)

We could add to this more information on what the update entails (maybe have a link returned from the API) that allows people more insight. It could also list which files will be affected, but I think that's maybe version 2 of this script.

**Comment by megoth** [comment]
This is related to https://github.com/solid/node-solid-server/issues/688.

**Comment by Ryuno-Ki** [comment]
Your description reads like a Progressive Web App. Especially service workers: https://serviceworke.rs/strategy-cache-update-and-refresh_demo.html

**Comment by megoth** [comment]
As there is a PR merged for this (https://github.com/solid/node-solid-server/pull/953), I hope it's ok for me to close this issue.
