### ISSUE TITLE
document.origin should read window.origin or self.origin

### ISSUE THREAD

**Issue by melvincarvalho** [solid/node-solid-server#870]
There is a warning in chromium saying that document origin will be removed in October.

        $rdf.Fetcher.crossSiteProxyTemplate = document.origin + '/xss/?uri={uri}'

https://github.com/solid/node-solid-server/blob/c7ee4aa19be43b934d0b0e60c382717aeccc2a7a/static/databrowser.html#L14

> document.origin is deprecated and will be removed in M70, around October 2018. Please use self.origin (window.origin) instead.

https://www.chromestatus.com/features/5701042356355072

**Comment by melvincarvalho** [comment]
This should be pushed asap, or to master, as chrome says it's landing in october 2018

**Comment by RubenVerborgh** [comment]
Feel free to ping @kjetilk for a release.

**Comment by RubenVerborgh** [comment]
BTW Nothing popular is really going to break; `document.origin` will simply be `undefined`. Cross-site fetching is off by default on the server.

**Comment by kjetilk** [comment]
We are *this* (holds up two fingers together) close to closing #858 , which would prompt 4.2.0. This should go along. I really hope we can do that today.
