### ISSUE TITLE
Logging in on a PDF resource doesn't work

### ISSUE THREAD

**Issue by RubenVerborgh** [solid/node-solid-server#878]
### Context

Given a pod with a PDF file at https://pod.com/file.pdf.
The PDF file is ACL-protected.

### Expected behavior
1. When going to the URL, you are asked to log in.
2. You log in.
3. The page refreshes and you see the PDF.

### Actual behavior
3. Log in fails, 401.

**Comment by RubenVerborgh** [comment]
Possibly/likely for all binary or non-Turtle files.

**Comment by rubensworks** [comment]
For reference, I'm not able to reproduce this with `.pdf` files, so it might be browser-dependent. But I can reproduce it with `.zip` files.
