### ISSUE TITLE
text/turtle parser N3.js on client side?

### ISSUE THREAD

**Issue by rimmartin** [solid/node-solid-server#881]
Hi,
when text/turtle is returned to the client side from a GET of a container
```
https://roger.localhost:8443/public/scad/
```
do you recommend using https://github.com/rdfjs/N3.js to parse and work with the list of quads?

**Comment by megoth** [comment]
Hey, I think maybe this is a better question to ask in the forum? https://forum.solidproject.org/

**Comment by timbl** [comment]
The fetcher automatically uses n3parser.js to parse a turtle file, putting the result on the store.
https://github.com/linkeddata/rdflib.js/blob/master/src/n3parser.js

https://github.com/linkeddata/rdflib.js/blob/master/src/fetcher.js#L643

**Comment by rimmartin** [comment]
hi @timbl, I began switching to and using solid-auth-client. I don't know if it gives access to a store.

testing using N3 myself on client side; learned I have to do some heuristics to gather all quad data together for given child Resource.  This is doable; I'm thinking about where the demarcation between server and client functionality is stabilizing.  Realising the power of rdf maybe should remain exposed to the client otherwise would limit to a subset of capability.  Yet how to get client developers to use...
