### ISSUE TITLE
Validation of LD-files

### ISSUE THREAD

**Issue by megoth** [solid/node-solid-server#882]
When posting triples as TTL, RDF+XML, JSON-LD, etc, I think we should do validation on the server. I don't think this should be to hard to implement, but the devils probably in the detail, so want to have a good discussion on this.

Also, I'm uncertain if this should be part of 5.0.0. or v.next. Any thoughts?

**Comment by kjetilk** [comment]
I think it is clearly a part of the v.next architecture, but it seems to touch all the handlers in the current architecture.

**Comment by akuckartz** [comment]
What happens when there is no validation?

**Comment by kjetilk** [comment]
The server would respond with a `400`. It is no replacement for client-side validation, but it is a last stand against breaking stuff.

**Comment by megoth** [comment]
I also think this would limit some of the issues that people have experienced (https://github.com/solid/solid/issues/165, https://github.com/solid/solid/issues/206, https://github.com/solid/node-solid-server/issues/826)

**Comment by megoth** [comment]
I think https://github.com/solid/node-solid-server/issues/826 also relates to this issue.

**Comment by megoth** [comment]
I'm discontinuing my work on this until we have a broader consensus on validation in general (currently discussed in [Validation and filter feature and Discourse](https://forum.solidproject.org/t/validation-and-filter-feature/548)).

I've pushed my work on https://github.com/solid/node-solid-server/tree/feature/simple-validation, in case it's interesting to continue at some point.

**Comment by megoth** [comment]
After a discussion with @timbl, @kjetilk, and @rubensworks on this earlier it seems that validation on the ACL-files might be a good compromise. If noone objects to this, I'll continue working on that tomorrow (it's should be almost done in that regard).

**Comment by megoth** [comment]
This issue has been fixed, we implemented syntax validation for ACL files in https://github.com/solid/node-solid-server/pull/937
