### ISSUE TITLE
Getting 401 after login

### ISSUE THREAD

**Issue by kjetilk** [solid/node-solid-server#883]
I'm trying to access https://timbl.com/timbl/ getting a `401`. I click Log In, and get a pop up. I log in with my WebID https://solid.kjernsmo.net/profile/card#me and it says "Logged In". The popup disappears, nothing seems to happen, so I reload the page, and I get a `401`.

I'll be around to help debug tomorrow.

**Comment by melvincarvalho** [comment]
I can report the same issue with my WebID 

https://melvincarvalho.com/#me

**Comment by rubensworks** [comment]
> The popup disappears, nothing seems to happen, so I reload the page, and I get a 401.

I don't experience the exact same issue.
For me, the popup disappears, and I am redirected to the page "No permission to access this resource".

I'm not sure what the .acl configuration for that folder looks like,
but this may be correct behaviour?

In any case, this may be related to #878.

**Comment by kjetilk** [comment]
@rubensworks yeah, you get the correct behaviour. 

What browser are you using? I only see this with Firefox, it works in Chrome...

**Comment by rubensworks** [comment]
@kjetilk I'm using Chrome (69.0.3497.100, mac). But I just tested it in Firefox (63.0.1), and it seems to work there as intended as well.

**Comment by RubenVerborgh** [comment]
I think this issue should move to solid-auth-client, where it is currently https://github.com/solid/solid-auth-client/issues/95

**Comment by kjetilk** [comment]
OK, great!
