### ISSUE TITLE
Unresponsive Log In button in popup

### ISSUE THREAD

**Issue by kjetilk** [solid/node-solid-server#884]
Again visiting https://timbl.com/timbl/ and getting a 401. Hitting "Log in" and getting a popup, choosing custom provider. I enter my WebID, but when I hit "Log In", there is apparent response.

In the console, I see
```
Error logging in with WebID-OIDC
popup.html:24:102872
TypeError
​
columnNumber: 0
​
fileName: ""
​
lineNumber: 0
​
message: "NetworkError when attempting to fetch resource."
​
stack: ""
​
__proto__: Object { stack: "", … }
popup.html:24:102921
w
https://timbl.com/common/popup.html:24:102921
```

(perhaps there is a better way to paste this log?)

There is no network activity when I do this. I'll be around to help debug.

**Comment by timbl** [comment]
Note you should have got 403 as there is no public access to the root.  This works for me logging in with my webid.
What happens if you try https://timbl.com/timbl/Public/ ?

**Comment by megoth** [comment]
Just to leave my experience on this:

- I went to the URI, clicked Log in button
- Got a popup
- Logged in with my solid.community WebID
- Popup closed, and page refreshed
- I'm getting a 403

(So all in all, the way I expected it to work.)

I'm sitting on macOS Mojave, Version 10.14, and used Chrome Version 69.0.3497.100.

**Comment by kjetilk** [comment]
@timbl https://timbl.com/timbl/Public/ works as expected on both my boxes.

There is no network activity when hitting "Log In", so it seems like a client side problem.

It works in Chrome (I end up with a `403`), but not in FF 60.2.1esr on Debian Jessie.

**Comment by RubenVerborgh** [comment]
Cannot reproduce in FF62 on macOS.

**Comment by james-martin-jd** [comment]
To add my experience, when trying to log in with the custom provider option, I add my webId and the login button does nothing. 

In the browser console, I see the following errors:
GET https://janeirodigital.exchange/jwks net::ERR_CERT_DATE_INVALID
popup.html:24 Error logging in with WebID-OIDC
TypeError: Failed to fetch

For me it is making network calls, though.

**Comment by kjetilk** [comment]
Uh, weirdness... Looks like this is yet another problem. At least, it sounds like we should have better error handling.

In my case, the cert has not expired (I'm seeing an email every night :-) ).

Also, it sounds like this is a problem in solid-auth-client?

**Comment by RubenVerborgh** [comment]
Sounds like a cert problem?

**Comment by kjetilk** [comment]
For @james-martin-jd and Luis, it was, but in my case,  I'm pretty sure it isn't. My certs haven't expired...

**Comment by RubenVerborgh** [comment]
Thanks all, following up in https://github.com/solid/solid-auth-client/issues/82.
