### ISSUE TITLE
Webid-TLS -> Error: self signed certificate

### ISSUE THREAD

**Issue by JeromeK13** [solid/node-solid-server#886]
Hey Guys
I recently created my SolidServer(local).
So i created an account called "adminswiss".
Solid POD URL: https://adminswiss.localhost:8443
Solid WebID: https://adminswiss.localhost:8443/profile/card#me

I also create a Certification with this Script where i entered my Name + WebID:
https://github.com/njh/gen-webid-cert

Now:
If i wannt to Login with the Certification i get this error:
![image](https://user-images.githubusercontent.com/28542882/47416280-a558b600-d775-11e8-8ce8-4e92eefdd653.png)

Config.json of the Server:

{
  "root": ".../solidServer/data",
  "port": "8443",
  "serverUri": "https://localhost:8443",
  "webid": true,
  "mount": "/",
  "configPath": "./config",
  "configFile": "./config.json",
  "dbPath": "./.db",
  "sslKey": ".../localhost.key",
  "sslCert": ".../localhost.cert",
  "multiuser": true
}

Can i fix this somehow?

**Comment by kjetilk** [comment]
When using a self-signed certificate, you have to start the server with `bin/solid-test` rather than the usual `solid` binary. Can you try that?

**Comment by JeromeK13** [comment]
`solid start --no-reject-unauthorized`
Started the Server with this command, but the error still appeared.

I also tried this one:
`solid start --auth tls --no-reject-unauthorized`
(Here i have to enter my Password for the Certification like 4 times to enter the website)

**Comment by kjetilk** [comment]
Yeah, you need to replace `solid start` with `solid-test start`

**Comment by JeromeK13** [comment]
Input:
`solid-test start`
Result:
`-bash: solid-test: command not found`

Cant find the command but it is located at ` /usr/local/lib/node_modules/solid-server/bin`

Thanks for your help 👍

**Comment by JeromeK13** [comment]
worked perfectly with `/usr/local/lib/node_modules/solid-server/bin/solid-test start` 👍

**Comment by kjetilk** [comment]
Great! Good to hear
