### ISSUE TITLE
Solid incompatible with Privacy Badger?

### ISSUE THREAD

**Issue by kjetilk** [solid/node-solid-server#921]
I have done some further investigation of #883 and #884 , and it turns out that if I disable EFF's [Privacy Badger](https://www.eff.org/privacybadger), both of those problems are resolved.

I think Privacy Badger is an important add-on, and we should make sure Solid works with Privacy Badger turned on. Whether it is us or Privacy Badger that needs to change, I don't know yet, but I suggest we look into that post-5.0.0.

**Comment by RubenVerborgh** [comment]
I think this issue should move to solid-auth-client, where it is currently https://github.com/solid/solid-auth-client/issues/95

**Comment by kjetilk** [comment]
OK, great!
