### ISSUE TITLE
Add meta tag to homepage to indicate whether it can be overwritten

### ISSUE THREAD

**Issue by RubenVerborgh** [solid/node-solid-server#936]
When a user creates a new account, we generate their homepage from `default-templates/new-account/index.html`.

A problem is that, when `default-templates/new-account/index.html` gets updated, users keep their old homepage.

However, some users might want that, and it shouldn't be up to the server to decide what they want. Some might prefer the new page.

I propose to add something like the following to the homepage template:
```html
<!-- Delete the next line if you do not want your homepage to be automatically updated whenever a new version becomes available. -->
<meta name="solid-allow-automatic-updates" content="true">
```

That way, we can update people to the latest version, unless they opt out.

**Comment by megoth** [comment]
I like this solution better than https://github.com/solid/node-solid-server/issues/853; if we choose this approach, we can close that one.

**Comment by rubensworks** [comment]
Another alternative might be to use some kind of templating system, where for example the `new-account/index.html` would just contain a reference to an internal Solid file, perhaps with some parameters.
This would allow users to make (partial) changes to their views, and still remain up-to-date with the built-in Solid views if they want to.

This would require some more work than the `<meta>` approach though.

**Comment by Ryuno-Ki** [comment]
Hm, what happens if the user allowed an update - and then the next comes in?
That is, would users have to edit the file if they want to opt-in/-out?

Alternatively you could set the `content` to a version (like `5.0`?) to estimate how much would break…

**Comment by RubenVerborgh** [comment]
They allow all updates.

**Comment by megoth** [comment]
As there is a PR merged for this (https://github.com/solid/node-solid-server/pull/953), I hope it's ok for me to close this issue.
