### ISSUE TITLE
Closing tickets with reference to forum

### ISSUE THREAD

**Issue by Ryuno-Ki** [solid/node-solid-server#939]
Recently, several issues were closed here without any notice about the reason.

See #820, #821 for example.

I remember having seen a bot in some GitHub repos which listens to a label assigned to an issue (IIRC „question”). It posted a comment telling the author that this is not the right place to ask question, pointing to the forum and closed the issue.

I can imagine this would be helpful here as well.

I can't remember the name of that GitHub org / repo right now, but bots can be created using [Probot](https://github.com/probot).

What do you think?

**Comment by Mitzi-Laszlo** [comment]
Hi @Ryuno-Ki, 

I was the one closing #820 and #821, my apologies for not giving enough explanation and I will stop doing this. I have reopened the issues so that the conversation can continue in GitHub. 

Let me know if there is anything else you would like me to do. 

Mitzi

**Comment by megoth** [comment]
If there are no more comments reg this, I'll close this issue for now. Hope that is ok.
