### ISSUE TITLE
update: destination <https://XXXX> inconsistent with delete quad https://XXXX

### ISSUE THREAD

**Issue by JornWildt** [solid/node-solid-server#940]
During development I ran into this error message while updating with the update-manager:

    update: destination <https://XXXX> inconsistent with delete quad https://XXXX

While it is correct, it is not an error in update-manager, it is still a rather confusing error message to get when you are new to Solid ... what is a "delete quad"? What does this actually mean? What did I do wrong? It would be nice if you could clarify the text of this error message.

In my exact situation the problem was that the second URL was a string, not a RDF Node object, and thus they are different even though they look identical (you can see it due to the missing angle brackets) - but it did take a while to figure out what was wrong.

**Comment by RubenVerborgh** [comment]
Thanks, this error message comes from RDFlib.js, let's follow up there: https://github.com/linkeddata/rdflib.js/issues/278

**Comment by JornWildt** [comment]
Ah, bummer, I know that, but didn't think about it ... sorry.

**Comment by RubenVerborgh** [comment]
No worries 🙂
