### ISSUE TITLE
GET on storage root returns double slash in description

### ISSUE THREAD

**Issue by csarven** [solid/node-solid-server#942]
```
curl -H'Accept: text/turtle' -H'Authorization: Bearer ...' https://csarven.solid.community/

[snippet]

@prefix : <#>.
@prefix n0: <>.
@prefix ldp: <http://www.w3.org/ns/ldp#>.
@prefix terms: <http://purl.org/dc/terms/>.
@prefix XML: <http://www.w3.org/2001/XMLSchema#>.
@prefix n1: <https://csarven.solid.community//.well-known/>.
@prefix inbox: <https://csarven.solid.community//inbox/>.
@prefix pro: <https://csarven.solid.community//profile/>.
@prefix pub: <https://csarven.solid.community//public/>.
@prefix set: <https://csarven.solid.community//settings/>.
@prefix st: <http://www.w3.org/ns/posix/stat#>.
@prefix ld: <http://www.w3.org/ns/iana/media-types/application/ld+json#>.
@prefix vnd: <http://www.w3.org/ns/iana/media-types/image/vnd.microsoft.icon#>.
@prefix html: <http://www.w3.org/ns/iana/media-types/text/html#>.
@prefix pl: <http://www.w3.org/ns/iana/media-types/text/plain#>.
@prefix c: <https://csarven.solid.community/profile/card#>.
@prefix ter: <http://www.w3.org/ns/solid/terms#>.
@prefix cs: <https://csarven.solid.community/>.

n0:
    a ldp:BasicContainer, ldp:Container;
    terms:modified "2018-11-16T23:23:10Z"^^XML:dateTime;
    ldp:contains
        n1:,
        <https://csarven.solid.community//528dc35d-4112-4a03-b226-628b5eb373b8.jsonld>.

<https://csarven.solid.community//528dc35d-4112-4a03-b226-628b5eb373b8.jsonld>
    a ld:Resource, ldp:Resource;
    terms:modified "2018-11-16T23:01:21Z"^^XML:dateTime;
    st:mtime 1542409281.311;
    st:size 2481.
```

**Comment by melvincarvalho** [comment]
Strange.  I am normally used to seeing these are relative links.

**Comment by NoelDeMartin** [comment]
I'm also facing the same problem, and it's causing some issues when I want to create documents within containers. For example if I get a url such as this: `https://localhost:8443//tasks/` and I try to create a document within doing a POST, it seems to ignore the container path and creates the document on the root. If I remove the duplicated slash it works, so as a workaround I am doing that in the client.

**Comment by kjetilk** [comment]
OK, thanks for following up! 

@NoelDeMartin are you running this on the latest beta? It would be interesting to know if the bug is still there in the most recent code.

**Comment by NoelDeMartin** [comment]
@kjetilk Yes I am running version 4.4.1, in particular this commit: https://github.com/solid/node-solid-server/commit/e9a5739a1840a9df16ec981aa51942ced774b6af

**Comment by csarven** [comment]
@NoelDeMartin @kjetilk 

* Issue occurs in v4.4.1-3-g9515d3c
* No issue in v5.0.0-beta.7-6-g217e8e3

**Comment by NoelDeMartin** [comment]
@csarven Ok I didn't know there was a newer version than the one in master, I'll check it out then. Thanks.

**Comment by kjetilk** [comment]
Great if you check it out, @NoelDeMartin ! If you work from git, you can check out the `release/v5.0.0` branch.

Basically, there have been lots of bugs like this, since most URIs are manipulated as strings. We've ironed out a bunch of them, but there are likely more bugs like this lurking.

**Comment by NoelDeMartin** [comment]
@kjetilk I faced an issue when trying the new version, which I reported at #1120. It was fixed yesterday, so I'll check it out and let you know if this has been solved as well :).

**Comment by NoelDeMartin** [comment]
@kjetilk Ok, I can confirm that this is fixed :) I tried in `master`, because `release/v5.0.0` doesn't have the fix for the issue I mentioned in the previous comment.

**Comment by kjetilk** [comment]
Ah, great! Indeed, the v5 branch was closed when we released it. I should delete it.
