### ISSUE TITLE
Browser localStorage not updated

### ISSUE THREAD

**Issue by mguiral** [solid/node-solid-server#945]
Hi,

When i updated my solid-server package to the last version, my browser localStorage solid-auth-client was not updated and when i tried to login, the login popup window redirected me to an url starts with https://login.<domain>/ (the previous issuer url from solid-auth-client localStorage key) and i am not able to login anymore.

After cleaning my localStorage everything is working well.

Does exists a server option that will update the browser localStorage solid-auth-client key when solid server is updated ?

Best regards

**Comment by scenaristeur** [comment]
It will never append anymore, you Can close
