### ISSUE TITLE
Update new pod template filenames to follow ResourceMapper mappings

### ISSUE THREAD

**Issue by RubenVerborgh** [solid/node-solid-server#948]
For example, `profile/card` needs to become `profile/card$.ttl`.

**Comment by rubensworks** [comment]
I'll start working on this.

I assume that _all_ extensionless files should always be seen as Turtle, right? Unless there are any specific edge-cases?

**Comment by RubenVerborgh** [comment]
In our pod templates, yes.

**Comment by melvincarvalho** [comment]
There is also the case when some slugless turtle is POSTed to an inbox and a UUID is created without an extension, iirc

Mainly posted this because I wanted to be the first use the phrase "slugless turtle" :)
