### ISSUE TITLE
Missing root .acl on new and existing servers

### ISSUE THREAD

**Issue by rubensworks** [solid/node-solid-server#977]
With the recent acl-check changes, .acl on root (such as `data/localhost/.acl`) is required.
However, this is not being generated because it is missing in `default-templates`.

An even bigger problem is that existing servers also won't have this .acl file, so all servers that upgrade will suddenly throw 401's everywhere.
An easy fix would be to auto-generate this root .acl file (from default-templates) when it can not be found at startup time.

**Comment by kjetilk** [comment]
Good catch!

Indeed, the root ACL is [required by the spec](https://github.com/solid/web-access-control-spec#acl-inheritance-algorithm), so we need to have it there.

**Comment by kjetilk** [comment]
Just to add a clarification: This is an issue on multi-user servers, not on single-user or accounts generated on multi-user servers, there the root ACL is sourced from `new-account`. 

BTW, it is the integration code that croaks when it doesn't find the root ACL, not the acl-check module itself.

**Comment by megoth** [comment]
I would imagine `localhost/.acl` would give READ-access to the public (at least when it's a multiuser)? Then it should be something like

```
@prefix acl: <http://www.w3.org/ns/auth/acl#>.
@prefix foaf: <http://xmlns.com/foaf/0.1/>.

# The public has read permissions
<#public>
    a acl:Authorization;
    acl:agentClass foaf:Agent;
    acl:accessTo <./>;
    acl:defaultForNew <./>;
    acl:mode acl:Read.
```

For non-multiuser servers it would be the default for users account, maybe with READ-access for the public:

```
# Root ACL resource for the user account
@prefix acl: <http://www.w3.org/ns/auth/acl#>.

<#owner>
    a acl:Authorization;
    acl:agent <OWNERS-WEBID> ;
    acl:accessTo </>;
    acl:defaultForNew </>;
    acl:mode
        acl:Read, acl:Write, acl:Control.

<#public>
    a acl:Authorization;
    acl:agentClass foaf:Agent;
    acl:accessTo <./>;
    acl:defaultForNew <./>;
    acl:mode acl:Read.
```

**Comment by kjetilk** [comment]
I started thinking that there is an `index.html.acl` and that is practically the same as the root... 

I think that I would not have a default in there, but read for the container, indeed.

**Comment by kjetilk** [comment]
Perhaps:
```turtle
@prefix acl: <http://www.w3.org/ns/auth/acl#>.
@prefix foaf: <http://xmlns.com/foaf/0.1/>.

<#public>
    a acl:Authorization;
    acl:agentClass foaf:Agent;  # everyone
    acl:accessTo </>;
    acl:mode acl:Read.
```

**Comment by megoth** [comment]
@kjetilk just to verify; so we would not give owners full control of the root by default, but add ACLs for files that would give them full control to those files (e.g. `index.html`)?

**Comment by rubensworks** [comment]
I'm doing some testing, and `acl:defaultForNew </>` would be needed if we also want to allow default access to `/common`.

Unless we want to add dedicated .acl files for those?

**Comment by kjetilk** [comment]
> @kjetilk just to verify; so we would not give owners full control of the root by default, but add ACLs for files that would give them full control to those files (e.g. `index.html`)?

I'm not sure, because we don't really have a clear concept of "owner", i.e. owner is just whoever has read-write-control. So, I just opted for the most conservative option.

**Comment by kjetilk** [comment]
So, first, `acl:defaultForNew` is deprecated in 5.0.0 and replaced by simply `acl:default`.

I'm not sure how the access to `/common` is enforced in the code, but couldn't we have a triple 
```turtle
<#public> acl:default </common/>  .
```
in the root ACL?

**Comment by rubensworks** [comment]
Sure, that also works :-)

**Comment by rubensworks** [comment]
Done in #984
