### ISSUE TITLE
Is "solid" http or https?

### ISSUE THREAD

**Issue by JornWildt** [solid/node-solid-server#995]
At https://github.com/solid/solid/blob/master/proposals/data-discovery.md we have:

    @prefix solid: <https://www.w3.org/ns/solid/terms#>

That is relevant for looking up `solid:publicTypeIndex`.

But in my profile document I have:

    @prefix solid: <http://www.w3.org/ns/solid/terms#>.

    <https://elfisk.solid.community/profile/card#me>
        solid:publicTypeIndex </settings/publicTypeIndex.ttl> ;

Now - which is right? The HTTPS version of `solid` or the HTTP :-)

Should I fix my profile document to use HTTPS - or should I fix my code to look for HTTP?

**Comment by megoth** [comment]
I'm not able to find documentation that backs it up, but I would say the correct version should be HTTPS.

Some vocabularies and ontologies are using HTTP for legacy reasons, but if you dereference `http://www.w3.org/ns/solid/terms#` you'll see that it redirects to `https://www.w3.org/ns/solid/terms#`.

**Comment by JornWildt** [comment]
I would also expect HTTPS ... and since I haven't touched my profile document, I'll be so free as to report it as a bug: solid-node-server should put HTTPS in the default profile document it generates for new users.

**Comment by megoth** [comment]
Very good, I actually see a lot uses of `http://www.w3.org/ns/solid/terms#` in the default templates... Will fix very soon.

**Comment by RubenVerborgh** [comment]
@timbl Which one is correct?

**Comment by elf-pavlik** [comment]
It seems to have `http://` set with `@base`
https://github.com/solid/vocab/blob/master/solid-terms.ttl

**Comment by JornWildt** [comment]
So does all this mean the spec at at https://github.com/solid/solid/blob/master/proposals/data-discovery.md is wrong and the solid-node-server template is right?

**Comment by melvincarvalho** [comment]
> So does all this mean the spec at at solid/solid:proposals/data-discovery.md@master is wrong and the solid-node-server template is right?

It's a spec proposal.  Just a typo.  I've fixed it now.

> https://elfisk.solid.community/settings/privateTypeIndex.ttl 

I cant read that file, but looking at my own it seems to do the right thing.

**Comment by csarven** [comment]
To strictly answering this issue: the canonical namespace was always http. To the best of knowledge, while the https resolved, it wasn't used (or intended). Both servers (Gold and node-solid-server), as well as (all of or at least most?) the (oldest) apps, docs and everything else used http. The instances of https out there can be considered to diverge from that for whatever reason (eg. possibly fetched on the clientside [common in JSON-LD libraries using context - but we don't actually have a context to begin with], and to avoid browser blocking / mixed content issues). I would suggest that those instances consider changing back to http.

If you are satisfied with this answer, would you care to close this issue? As for whether it should be http or https... that should be followed up in https://github.com/solid/vocab/issues/20 .

**Comment by melvincarvalho** [comment]
> If you are satisfied with this answer, would you care to close this issue?

I am!

**Comment by melvincarvalho** [comment]
> If you are satisfied with this answer, would you care to close this issue? As for whether it should be http or https... that should be followed up in solid/vocab#20

I already closed that issue, but it got reopened.  Im somewhat horrified by that.

My advice : [Don't break the web!](https://www.w3.org/DesignIssues/Security-NotTheS.html)

**Comment by JornWildt** [comment]
> > So does all this mean the spec at at solid/solid:proposals/data-discovery.md@master is wrong and the solid-node-server template is right?
> 
> It's a spec proposal. Just a typo. I've fixed it now.

That's cool. Thank you - then there is no doubt. It may just be a "proposal" but none the less is it what you guys are recommending to use right now.

**Comment by JornWildt** [comment]
> > https://elfisk.solid.community/settings/privateTypeIndex.ttl
> 
> I cant read that file, but looking at my own it seems to do the right thing.

Sorry, that was my private type index.

But the problem is still there. I just created a new account as "Ragnaros". Here is what I get:

In https://ragnaros.inrupt.net/profile/card we have the correct namespace:

    @prefix solid: <http://www.w3.org/ns/solid/terms#>.
  

But in https://ragnaros.inrupt.net/settings/publicTypeIndex.ttl I get:

    @prefix solid: <https://www.w3.org/ns/solid/terms#>.
    <> a solid:TypeIndex

So strictly speaking, the type index is *not* a type index since the `solid` prefix with HTTPS is wrong - and when some person later on re-uses the `solid` prefix he or she well get an invalid type registration and it won't work with those applications that look for the correct HTTP registrations.
